### ISSUE TITLE
Ability to supply derived path as an array instead of a string

### ISSUE THREAD

**Issue by DeftNerd** [Bit-Wasp/bitcoin-php#212]
It might be nice to be able to build the derive path by supplying an array of variables (or even an object) rather than supplying a string. 

For instance, instead of
`$bip44ChildKey = $masterKey->derivePath("44'/0'/0'/0/0");`

Someone could do 

`$path = [
  "purpose" => 44,
  "coin_type" => 0,
  "account" => 0,
  "chain" => 0,
  "address_index" => 0];`
`$bip44ChildKey = $masterKey->derivePath($path);`

Or for the unhardened varieties (longer names since it's not as common anymore)

`$path = [
  "purpose_unhardened" => 44,
  "coin_type_unhardened" => 0,
  "account_unhardened" => 0,
  "chain" => 0,
  "address_index" => 0];`

**Comment by DeftNerd** [comment]
To preserve backwards compatibility, there could be a derivePathFromArray function that simply takes the array and builds the string and passes it directly to derivePath. That would also make it so if there is the need, there could be a derivePathFromObject

**Comment by afk11** [comment]
With the way derivePath() works (converts to integers) I see another way to go about it. 

Thinking a new function deriveFromList(), which derivePath() would use. The new function would be typehinted against \Traversible, AFAIK that allows either arrays/objects to work. I dislike forcing conventions on array key's, but so long as they're defined in order all is well. 

```[
   $sequence->getHardened(44), // purpose
   $sequence->getHardened(0), // cointype
   $sequence->fromNode("0h"). // account, using fromNode
   0, // chain
   0 // address_index
];```

HierarchicalKey::derivePath() could then convert the path to this format, and then call the new function. HierarchicalKeySequence::fromNode() accepts a string representation of an index and returns the sequence, so it's output would also be correct for the new function!

I'll try this quickly, but fire a PR if you have something done up already!

**Comment by afk11** [comment]
See https://github.com/Bit-Wasp/bitcoin-php/pull/213

I've tried to keep it open, you can name fields so long as it's in the correct order (it doesn't matter to the underlying code, so long as it can still `foreach()`)

**Comment by DeftNerd** [comment]
You're a talented developer! From a general idea to working code and unit tests in under 24 hours is impressive. 

Thanks for everything you do!

**Comment by afk11** [comment]
Not at all mate, let me know that it works ok! v0.0.18
