### ISSUE TITLE
Importing redeemscript

### ISSUE THREAD

**Issue by starsoccer** [Bit-Wasp/bitcoin-php#227]
Not sure if this is the best place to post this, but I was using bitcoin-php, and was trying to figure out how to import a redeemscript. Basically I already have the redeemscript and multisig address created with a transaction input. I was trying to figure out how to import the redeemscript into the right class and then simply spend the one input.

**Comment by afk11** [comment]
What kind of redeem script? Presently only multisig, pay-to-pubkey, pay-to-pubkey-hash are supported - P2SH or otherwise.

**Comment by starsoccer** [comment]
I think it was a regular multisig, but I managed to get it using 
<code>$rs = new Script(Buffer::hex('redeemscripthere'));</code>

I am not trying to simply spend funds from the multisig. For reference the address is "39jRMSkGDFAMujJRJUL1bncgabeVsTyN3i"

my code for creating the transactioninput is below
<code>$fundTx = TransactionFactory::build()
    ->input('4d7adb19fff03892a11924f2a9188e36dbbdf0f3bb341b6514475e4df238184b', 0)
    ->output(1000000, $os)
    ->get();
</code>

When I try to broadcast it or decode it, it failed and looking at it decoded, the input transaction id seems to have changed to "f168774950daccfd4678ad7273fce7650fc9101cc2706dca40788c27b3c41e14" for some weird reason. If it would be helpful, I can paste my whole code

**Comment by afk11** [comment]
yeah paste the code, and the signed tx that is returned. Let me know what version of the lib your using as well :)

For the unsigned tx, I get this which looks correct. 
0100000001*4b1838f24d5e4714651b34bbf3f0bddb368e18a9f22419a19238f0ff19db7a4d*0000000000ffffffff0140420f000000000017a9149295afc1f08a900e568090654f71f6118cfbc17c8700000000

**Comment by starsoccer** [comment]
Okay, so the signed tx I get is "0100000001141ec4b3278c7840ca6d70c21c10c90f65e7fc7372ad7846fdccda50497768f100000000fda70100483045022100f394dcf5599b5f8f2c284b0b4b9dbd1383a598fccd35385c13078a6fe191c5130220656b9fc66c6a2df7e46b389f9299a95a210e283d96b20f4d6aa216611c3d755001483045022100f394dcf5599b5f8f2c284b0b4b9dbd1383a598fccd35385c13078a6fe191c5130220656b9fc66c6a2df7e46b389f9299a95a210e283d96b20f4d6aa216611c3d755001483045022100f394dcf5599b5f8f2c284b0b4b9dbd1383a598fccd35385c13078a6fe191c5130220656b9fc66c6a2df7e46b389f9299a95a210e283d96b20f4d6aa216611c3d7550014cc95241047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff53ae0000000001a0bb0d00000000001976a9149567aa58709b754a5cb642027d7ed1ebd6c18ab588ac00000000"


My exact code is below excluding the private key.
Also to note, I modified it a bit for this specfic multisig as its a 2 of 3, but its just 3 of the same public keys. so 1 signature = 3 signatures
<code>require_once('/php/bitwasp/vendor/autoload.php');

use BitWasp\Bitcoin\Bitcoin;
use BitWasp\Bitcoin\Key\PrivateKeyFactory;
use BitWasp\Bitcoin\Script\ScriptFactory;
use BitWasp\Bitcoin\Transaction\TransactionFactory;
use BitWasp\Bitcoin\Address\AddressFactory;
use BitWasp\Bitcoin\Script\Script;
use BitWasp\Buffertools\Buffer;

$ecAdapter = Bitcoin::getEcAdapter();

// Two users independently create private keys.
$pk1 = PrivateKeyFactory::fromWif('privatekey here starting with a 5');
$rs = new Script(Buffer::hex('5241047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff53ae'));

$rs = unserialize(serialize($rs));
// They exchange public keys, and a multisignature address is made.
$redeemScript = $rs;
$os = ScriptFactory::scriptPubKey()->payToScriptHash($redeemScript);

// The address is funded with a transaction (fake, for the purposes of this script).
// You would do getrawtransaction normall
$fundTx = TransactionFactory::build()
    ->input('4d7adb19fff03892a11924f2a9188e36dbbdf0f3bb341b6514475e4df238184b', 0)
    ->output(1000000, $os)
    ->get();


// One party wants to spend funds. He creates a transaction spending the funding tx to his address.
$spendTx = TransactionFactory::build()
    ->spendOutputFrom($fundTx, 0)
    ->payToAddress(900000, AddressFactory::fromString('1EcysP9UmvyW1zdD75noVdb8BVaRA7ZC8h'))
    ->get();


// Two parties sign the transaction (can be done in steps)
$signer = TransactionFactory::sign($spendTx);
$signer
    ->sign(0, $pk1, $os, $redeemScript)
    ->sign(0, $pk1, $os, $redeemScript);

$signed = $signer->get();

echo "Fully signed transaction: " . $signed->getHex() . "\n";</code>

**Comment by afk11** [comment]
Ah, I see what it is. I really need to change the examples, several make fake transactions to spend, but you just need to spend a specific txid, vout - spendOutputFrom would hash that new thing, and use that as the input txid. 

Try this out: 
```php
require_once('/php/bitwasp/vendor/autoload.php');

use BitWasp\Bitcoin\Bitcoin;
use BitWasp\Bitcoin\Key\PrivateKeyFactory;  
use BitWasp\Bitcoin\Transaction\TransactionFactory;
use BitWasp\Bitcoin\Address\AddressFactory;
use BitWasp\Bitcoin\Script\Script;
use BitWasp\Buffertools\Buffer;

$ecAdapter = Bitcoin::getEcAdapter();

// Two users independently create private keys.
$pk1 = PrivateKeyFactory::fromWif('privatekey here starting with a 5');
$rs = new Script(Buffer::hex('5241047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff53ae'));

$redeemScript = new \BitWasp\Bitcoin\Script\P2shScript($rs);
$os = $redeemScript->getOutputScript();

$txid = Buffer::hex('4d7adb19fff03892a11924f2a9188e36dbbdf0f3bb341b6514475e4df238184b');
$vout = 0;

// One party wants to spend funds. He creates a transaction spending the funding tx to his address.
$spendTx = TransactionFactory::build()
    ->input($txid, $vout)
    ->payToAddress(900000, AddressFactory::fromString('1EcysP9UmvyW1zdD75noVdb8BVaRA7ZC8h'))
    ->get();

// Two parties sign the transaction (can be done in steps)
$signer = TransactionFactory::sign($spendTx);
$signer
    ->sign(0, $pk1, $os, $redeemScript)
    ->sign(0, $pk1, $os, $redeemScript);

$signed = $signer->get();

echo "Fully signed transaction: " . $signed->getHex() . "\n";
```

**Comment by starsoccer** [comment]
Well that partly worked. Using your script I can decode the signed raw transaction and it appears good, but when trying to broadcast it via blockchain.info I get the following error, "OP_CHECKMULTISIG(VERIFY) with non-null nulldummy: [48, 68, 2, 32, 73, 65, -103, 112, 58, -100, -49, -49, -98, -71, -81, -17, -126, 7, -77, -94, -44, -73, -92, 104, -18, 80, -59, -40, 109, 80, -91, 24, 93, -52, -23, 98, 2, 32, 27, -95, -54, -41, 22, -26, 99, -18, 98, -128, -101, -62, -96, -70, -55, -66, -69, 74, -26, 66, 115, -26, -72, -95, -26, 26, 84, -30, 9, 1, -42, 31, 1]"


The signed raw transaction is below,

"01000000014b1838f24d5e4714651b34bbf3f0bddb368e18a9f22419a19238f0ff19db7a4d00000000fda401004730440220494199703a9ccfcf9eb9afef8207b3a2d4b7a468ee50c5d86d50a5185dcce96202201ba1cad716e663ee62809bc2a0bac9bebb4ae64273e6b8a1e61a54e20901d61f014730440220494199703a9ccfcf9eb9afef8207b3a2d4b7a468ee50c5d86d50a5185dcce96202201ba1cad716e663ee62809bc2a0bac9bebb4ae64273e6b8a1e61a54e20901d61f014730440220494199703a9ccfcf9eb9afef8207b3a2d4b7a468ee50c5d86d50a5185dcce96202201ba1cad716e663ee62809bc2a0bac9bebb4ae64273e6b8a1e61a54e20901d61f014cc95241047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff53ae0000000001a0bb0d00000000001976a9149567aa58709b754a5cb642027d7ed1ebd6c18ab588ac00000000"

**Comment by afk11** [comment]
Hmm, bitcoind decodes and shows it does have a null byte as the dummy. Wonder if that's a bug in BC.I's push-tx page? fda40100... <- decodes properly, maybe they picked the wrong position in the script for that byte. 

I tested that transaction against blockexplorer.com, which uses insight. It failed at first due to General Error -25, but then tried it against bitcoind (the node wasn't synced), so I only used signrawtransaction on the signed tx. 

It turns out, the transaction you produced has two signatures in it, and Bitcoind removed the second signature, because it was by the same public key anyway. I didn't realize it could do that!

Anyway, it produced this transaction, which blockexplorer accepted!
https://www.blocktrail.com/BTC/tx/d9ffa4742c64f197381683987b918a19fcea7062a3fbc99f82fdd1486defa50e

01000000014b1838f24d5e4714651b34bbf3f0bddb368e18a9f22419a19238f0ff19db7a4d00000000fd5c01004730440220494199703a9ccfcf9eb9afef8207b3a2d4b7a468ee50c5d86d50a5185dcce96202201ba1cad716e663ee62809bc2a0bac9bebb4ae64273e6b8a1e61a54e20901d61f014730440220494199703a9ccfcf9eb9afef8207b3a2d4b7a468ee50c5d86d50a5185dcce96202201ba1cad716e663ee62809bc2a0bac9bebb4ae64273e6b8a1e61a54e20901d61f014cc95241047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff53ae0000000001a0bb0d00000000001976a9149567aa58709b754a5cb642027d7ed1ebd6c18ab588ac00000000

**Comment by afk11** [comment]
I'm about to hit the hay, but I'll probably have a fix for this in a day or two.

**Comment by starsoccer** [comment]
hmm thats interesting. sounds like I should change the double signing to a single signing. I changed the double signing line below,

<code>$signer
    ->sign(0, $pk1, $os, $redeemScript)
    ->sign(0, $pk1, $os, $redeemScript);</code>

To a single single below,

<code>$signer
    ->sign(0, $pk1, $os, $redeemScript);</code>


and produced the following,

"01000000014b1838f24d5e4714651b34bbf3f0bddb368e18a9f22419a19238f0ff19db7a4d00000000fda401004730440220494199703a9ccfcf9eb9afef8207b3a2d4b7a468ee50c5d86d50a5185dcce96202201ba1cad716e663ee62809bc2a0bac9bebb4ae64273e6b8a1e61a54e20901d61f014730440220494199703a9ccfcf9eb9afef8207b3a2d4b7a468ee50c5d86d50a5185dcce96202201ba1cad716e663ee62809bc2a0bac9bebb4ae64273e6b8a1e61a54e20901d61f014730440220494199703a9ccfcf9eb9afef8207b3a2d4b7a468ee50c5d86d50a5185dcce96202201ba1cad716e663ee62809bc2a0bac9bebb4ae64273e6b8a1e61a54e20901d61f014cc95241047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff41047a10825f624ee76f2ea88d608caabc1395e70e46dce00f144a4b749099a72cf784e38a4e1b6fa64eb6be6f977b310627b178aa33b81716d3e79c2d84b961e8ff53ae0000000001a0bb0d00000000001976a9149567aa58709b754a5cb642027d7ed1ebd6c18ab588ac00000000"

Which seems to be the same as yours, so that must have fixed it. 
I am going to try to create a new 2 of 3 multisig from scratch later, like you just said, going to bed for the night, but will try it tomorrow.

**Comment by starsoccer** [comment]
Just wanted to follow up with you and say that I have multisig working via the redeemscript and all, but I cant seem to figure out how to import a public key without a private key in order to create a multisignature address from it

**Comment by afk11** [comment]
The factory classes generally contain helper methods for parsing things, and creating instances. `fromHex` methods work on hex OR Buffer instances `PublicKeyFactory::fromHex()` should work!

**Comment by starsoccer** [comment]
Ah okay that seems to have worked. 

Thanks for all your help. I think this issue can be closed

**Comment by starsoccer** [comment]
I hate to reopen this again, but I cant seem to figure out how to get the multisig address from the redeemscript.

<code>
function createmultisig($pubkeyone, $pubkeytwo, $pubkeythree){
$redeemScript = ScriptFactory::scriptPubKey()->multisig(2, [PublicKeyFactory::fromHex($pubkeyone), PublicKeyFactory::fromHex($pubkeytwo),PublicKeyFactory::fromHex($pubkeythree)]);
$os = ScriptFactory::scriptPubKey()->payToScriptHash($redeemScript);
    return array('redeemscript' => $redeemscripttext = $redeemScript->getHex(), 'address' => '');   
}
</code>

**Comment by afk11** [comment]
Any ScriptFactory::scriptPubKey() method can be called using p2sh() as well
    ScriptFactory::p2sh()->multisig(2, [$pk1, $pk2]);

Returning one of these: https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Script/P2shScript.php

**Comment by afk11** [comment]
Or, you can just do AddressFactory::fromScript($redeemScript);

**Comment by starsoccer** [comment]
Thanks, I think I am missing something tho. When var_dump(AddressFactory::fromScript($redeemScript)); or var_dump($addr);

I get object(BitWasp\Bitcoin\Address\ScriptHashAddress)#23 (1) { ["hash":"BitWasp\Bitcoin\Address\Address":private]=> string(40) "df63a07ecfee629de911ef35b352d20e84b0355f" } 

I know that isn't a valid address. am I doing something wrong?

**Comment by afk11** [comment]
Ah, that returns an instance. So you do getAddress on that to get the string :)

**Comment by starsoccer** [comment]
okay that works,

for anyone else reading this, the final working solution is <code>AddressFactory::fromScript($redeemScript)->getAddress()</code>
