### ISSUE TITLE
src/Rpc/Client/Bitcoind.php ->getblockcount()

### ISSUE THREAD

**Issue by yannis79** [Bit-Wasp/bitcoin-php#232]
Function should fetch getblockcount,
not bestblockhash

    /**
     * @return int
     */
    public function getblockcount()
    {
        $count = $this->client->execute('getblockcount');
        return $count;
    }

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/pull/233 should fix it!

**Comment by afk11** [comment]
The 0.0.19.1 release fixes this
