### ISSUE TITLE
Creating Rawtx and signing from multiple inputs

### ISSUE THREAD

**Issue by starsoccer** [Bit-Wasp/bitcoin-php#238]
I am working on creating a script that will scrape a few blockchain websites such as blockchain.info, blockr.io, etc.. From scraping I am taking the transaction ID and the Vout to build a transaction that I can then sign. The code below code is intended to get the inputs list with the transaction id and Vout and convert it into a bitcoin-php transaction factory. Once converted it will be signed with one private key and then displayed to the user in order to sign with a final key. 

With my current code I am getting an error saying "Catchable fatal error: Argument 1 passed to BitWasp\Bitcoin\Transaction\TransactionInput::__construct() must be an instance of BitWasp\Bitcoin\Transaction\OutPointInterface, string given, called in \php\bitcoin.php on line 80 and defined in \php\bitwasp\src\Transaction\TransactionInput.php on line 38"

Let me know if something is not clear, and thanks for any help. Below is most of the code I am using excluding the website scraping

...
function createinputlist($pubkeyone,$pubkeytwo,$privatekey, $inputlist){
    $private = PrivateKeyFactory::fromWif($privatekey);
    $redeemScript = ScriptFactory::scriptPubKey()->multisig(2, [PublicKeyFactory::fromHex($pubkeyone),PublicKeyFactory::fromHex($pubkeytwo),$private->getPublicKey()]);
    $p2sh = ScriptFactory::create()->push($redeemScript->getBuffer())->getScript();
    $inputs = array();
    foreach($inputlist as $transaction){
        $inputs[] = new TransactionInput($transaction['txid'], $transaction['vout'], $p2sh);
    }
    return $inputs;
}
function createrawtx($orderid, $escrowaddress, $escrowamount, $refundaddress, $refundamount){
    $ecAdapter = Bitcoin::getEcAdapter();
    require_once("market.php");
    $depositinfo = getdepositinfo($orderid);
    $pk1 = PrivateKeyFactory::fromWif($depositinfo['privatekey']);
    $rs = new Script(Buffer::hex($depositinfo['redeemscript']));
    $redeemScript = new \BitWasp\Bitcoin\Script\P2shScript($rs);
    $os = $redeemScript->getOutputScript();
// One party wants to spend funds. He creates a transaction spending the funding tx to his address.
$spendTx = TransactionFactory::build()
    ->input(createinputlist($depositinfo['publickeyone'], $depositinfo['publickeytwo'], $depositinfo['privatekey'], getinputs($depositinfo['multisig'])))
    ->payToAddress($escrowamount, AddressFactory::fromString($escrowaddress))
    ->payToAddress($refundamount, AddressFactory::fromString($refundaddress))
    ->get();

$signer = TransactionFactory::sign($spendTx);
$signer
    ->sign(0, $pk1, $os, $redeemScript);

$signed = $signer->get();

return $signed->getHex();

}
...

**Comment by afk11** [comment]
`$inputs[] = new TransactionInput($transaction['txid'], $transaction['vout'], $p2sh);` 

Check the source code for TransactionInput. It's a type mismatch error: you're passing a string instead of an OutPoint. 

The examples might be a little out of date, but always refer to the code for what you should be passing. We make heavy use of type-hinting, which is meant to help you :)

I get quite a lot of questions about transaction signing, but it definitely works!

**Comment by starsoccer** [comment]
Yes the examples a bit out dated. I have a few working code examples that I could give you to update or add to your examples if you want.

 I just looked it over, and it sounds like that line should be 

$inputs[] = new TransactionInput(new OutPoint($transaction['txid'], $transaction['vout']), $p2sh);

Does that look right now?

**Comment by afk11** [comment]
Looks rght!

One thing, the txin.script, you don't have to put the PUSH<redeemScript> in there. Just use the signer, which will regenerate the scriptSig for you.

**Comment by starsoccer** [comment]
okay, not sure that worked correctly. It needed to be Buffer::hex($transaction['txid']) but that seems to have fixed that problem.

Now I am getting an issue with the transaction builder. Is there a good example that shows building a transaction from multiple inputs?

**Comment by afk11** [comment]
Either loop across $inputs and call $builder->input(...), or use $builder->inputs() on your array. 

Since you have many inputs, they all have to be signed. If you have two keys, call it twice for that input with different keys. It should handle partially signed transactions well enough.

**Comment by afk11** [comment]
My best advise would be to rely on the code, not the examples. A good IDE will serve you well!

**Comment by starsoccer** [comment]
I dont understand what you mean.

IDE related, any one you can recommend? Right now I vary between using Brackets and Visual Studio

To make it easier,  below is the code I have for looping through the transaction,
    foreach($inputlist as $transaction){
        $inputs[] = new TransactionInput(new OutPoint(Buffer::hex($transaction['txid']), $transaction['vout']), $p2sh);
    }

After that loop, the $inputs[] is sent to the transactionfactory builder as seen below

$spendTx = TransactionFactory::build()
    ->input($inputs[])
    ->payToAddress($escrowamount, AddressFactory::fromString($escrowaddress))
    ->payToAddress($refundamount, AddressFactory::fromString($refundaddress))
    ->get();

**Comment by afk11** [comment]
I've really enjoyed moving to PhpStorm, but I haven't used those two. You can get 30-day evaluations, just wipe the appdata folder when it's over..

Just change the second line to this:
`   ->inputs($inputs) `

Hrm, you're making an escrow site? Don't keep private keys on the server first of all.. Second, you don't have to sign that redeem transaction, your customers do (unless there's a dispute). Anyways.. You're about to enter a rabbit hole, so, good luck keeping this secure!

**Comment by starsoccer** [comment]
I already made an escrow site, I guess you did some background checking into me ;) , tho I am doing improvements still, this is actually for a different project.

Yes the private keys are kept on a server encrypted. They do not hold any funds so to speak so I consider the risk minimal. The private key is used in a 2 of 3 where 1 person holds 2 keys and we hold one key. So even if we were hacked the best the hacker would get would be 1 key which is useless.

I was about to comment and tell you it ddn't work when I noticed the S in inputs. What a big difference one letter can make.

Well that worked, thanks for your help

**Comment by afk11** [comment]
The BitWasp project was initially a FOSS multisig marketplace, but ended up focusing on the library instead. Might revisit things when it supports a proper SPV client.

**Comment by starsoccer** [comment]
Yes, I am familar with the background. I was quite disappointed when it seemed like it died a while back and was part of the reason why I made my site.

It was quite hard making it due to the lack of native php libraries for bitcoin. I would say this is one of the only ones I am aware of. There are a few other smaller ones but most do not support everything. For example one might only create bitcoin addresses while another might only generate multi-signature address.

**Comment by afk11** [comment]
It worked well enough for ordering/payments, but lacked a whole heap of stuff you'd expect on a site (search, decent menu/layout, etc). There wasn't a lot of interest from developers, so once the bitcoin stuff was finished, it was hard to keep maintaining. 

A lot of time was wasted trying to consolidate various libraries.. But eventually lead to this thing :)

**Comment by starsoccer** [comment]
Yeah, eventually id like to expand and build a marketplace similar to bitmit back in the good ole days.
