### ISSUE TITLE
Request for advice: Easiest way to get balance of entire wallet

### ISSUE THREAD

**Issue by DeftNerd** [Bit-Wasp/bitcoin-php#293]
Is there any function to make it easy to get the balance of a wallet from a seed, pubkey, prvkey, etc?

Or should I just write my own function to derive the first (variable) addresses and iterate through them and check the balances and add them up?

Is this a function that would be useful within Bitwasp? 

In theory, it would accept the seed or pubkey or prvkey, and the number of derived addresses to check, and an optional starting point to allow for a sort of pagination. 

I have noticed a lack of wallet related examples in the examples directory, unless I've missed some.

**Comment by afk11** [comment]
There's no support for it at the moment - it implies the code has access to the full UTXO set. API's are an option, but since they're down to taste, I leave that decision to consumers. 

If you're looking for something reasonably small, maybe write an app to listen for ZMQ notifications of new blocks! Parse each block for payments to your output scripts, and spends of the same. You could set a callback for both events for review. (Payments are always interesting, and depending on your app you might want to check the spend transaction as well)

There is an effort here to get a full node running in PHP: https://github.com/Bit-Wasp/bitcoin-php It gets very slow as the UTXO table gets full.. I've never had it fully sync to date. I'll probably migrate that table to leveldb if it makes it useful..

**Comment by afk11** [comment]
As for adding support, I'd prefer to keep this a purely offline library, and work with persistent data in a repository specific for wallets. We could then expose a WalletInterface and let people load them however they please!

**Comment by DeftNerd** [comment]
I'm having trouble using RpcFactory::bitcoind to execute listunspent

Sample code:
```
<?php
require "vendor/autoload.php";

use BitWasp\Bitcoin\Address\AddressFactory;
use BitWasp\Bitcoin\Rpc\RpcFactory;
use BitWasp\Bitcoin\Bitcoin;

$network = Bitcoin::getNetwork();

$host = getenv('BITCOIN_RPC_SERVER') ?: '127.0.0.1';
$port = getenv('BITCOIN_RPC_PORT') ?: '8332';
$user = getenv('BITCOIN_RPC_USER') ?: 'rpcuser';
$pass = getenv('BITCOIN_RPC_PASSWORD') ?: 'rpcpassword';

$bitcoind = RpcFactory::bitcoind($host, $port, $user, $pass);

$addresses = [
  AddressFactory::fromString('1Mu1NPTTwx9hY2Ehfhs4u665RGvuohZA4f', $network),
  AddressFactory::fromString('129TQVAroeehD9fZpzK51NdZGQT4TqifbG', $network),
  ];

print_r("Block Height: " . $bitcoind->getblockcount() . "\n");
print_r("Array of addresses to check: \n");
print_r($addresses);
print_r("\n");
print_r("Response: \n");
print_r($bitcoind->listunspent(1, 9999999, $addresses, $network));
print_r("\n");

```

Which results in 
```
Block Height: 409750
Array of addresses to check:
Array
(
    [0] => BitWasp\Bitcoin\Address\PayToPubKeyHashAddress Object
        (
            [hash:BitWasp\Bitcoin\Address\Address:private] => e5387418a3614cba40e6de0c1c782b24433ddf17
        )

    [1] => BitWasp\Bitcoin\Address\PayToPubKeyHashAddress Object 
        (
            [hash:BitWasp\Bitcoin\Address\Address:private] => 0c917ec56ded601852e4caaa37d7bf9643773730
        )
)

Response:
Array
(
)
```

As you can see, I can receive getblockcount so bitcoind RPC is working just fine, but when I pass the array of address objects to listunspent, I'm not getting anything in reply. 

Any suggestions? I'm not sure how to determine if the problem is with BitWasp\Bitcoin\Rpc\Client\Bitcoind::listunspent or with my bitcoind. 

```
root@bitcoin18:~# bitcoin-cli -version
Bitcoin Classic RPC client version v0.12.0.0-unk
```

**Comment by DeftNerd** [comment]
Nevermind, it was my mistake. I thought that you could just enter an arbitrary address and it would return the information about it. I didn't realize that you have to import the address into bitcoind before it'll process the listunspent command.
