### ISSUE TITLE
/src/Rpc/Client/ElectrumServer - Doesn't accept arrays of addresses

### ISSUE THREAD

**Issue by DeftNerd** [Bit-Wasp/bitcoin-php#294]
The Electrum API supports arrays of addresses [1] for functions such as blockchain.address.get_history, blockchain.address.get_balance, blockchain.address.listunspent, blockchain.transaction.get

[1] http://docs.electrum.org/en/latest/protocol.html#request

/src/Rpc/Client/ElectrumServer.php only accepts a single AddressInterface object for those functions. 

Your /src/Rpc/Client/Bitcoind.php implementation has a clever way of dealing with this on line 187 where you can pass an array of AddressInterface objects which it them uses array_map and a function to process the objects into strings using $address->getAddress($network) 

Could the applicable functions in the ElectrumServer class be changed to have a similar ability?

I could take a crack at the code but you're a superior coder and I think you would be more effective. If you like, I can try. 

This would be a breaking change since existing code that implements those functions are just passing a singular object rather than an array, so it won't be backwards compatible unless instead of altering the existing functions, new functions were created such as

addressListUnspentArray

**Comment by afk11** [comment]
It looks like that method is just a sample, and parameters are always passed as an array and loaded by index. In most cases only one is ever used, so it mightn't be possible to include this.

https://github.com/spesmilo/electrum-server/blob/62a593569954bcbe3f9b666188d17c9cf9afef55/src/blockchain_processor.py#L511

I'll see about adding some kind of batch functionality the library, but meanwhile something like this would wait for both requests before returning the results:

```php
\React\Promise\all([
   $stratum->addressListUnspent('1address1'),
   $stratum->addressListUnspent('1address2'),
])->then(function (array $results) {
    // blah
});
```

**Comment by afk11** [comment]
FYI - I'm rewriting the stratum library a bit today, it was one of my first react projects so does silly stuff like making a connection per request :s I'll probably move the ElectrumServer class to that library (want to remove the react dependency for bitcoin-php)

**Comment by DeftNerd** [comment]
Implementing the code has been the first time I've used React too so it's been a bit of a learning curve. 

I'm glad you mentioned that you could pass multiple objects in an array in the React\Promise\all. I didn't know that and it makes things significantly easier. Thanks!

**Comment by afk11** [comment]
Closing this as the `ElectrumServer` class was removed in a recent PR, it's home is now stratum-php.
