### ISSUE TITLE
Can't install with composer

### ISSUE THREAD

**Issue by chris41188** [Bit-Wasp/bitcoin-php#295]
Hi
When I use the composer install command the install fails and I get this, (I am using laravel 4)

 Problem 1
    - bitwasp/bitcoin v0.0.23 requires mdanter/ecc ~0.3 -> satisfiable by mdanter/ecc[v0.3.0].
    - Installation request for bitwasp/bitcoin ^0.0.23 -> satisfiable by bitwasp/bitcoin[v0.0.23].
    - Conclusion: remove symfony/console v2.5.12
    - Conclusion: don't install symfony/console v2.5.12
    - mdanter/ecc v0.3.0 requires symfony/console ~2.6 -> satisfiable by symfony/console[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6].
    - Can only install one of: symfony/console[v2.6.0, v2.5.12].
    - Can only install one of: symfony/console[v2.6.1, v2.5.12].
    - Can only install one of: symfony/console[v2.6.10, v2.5.12].
    - Can only install one of: symfony/console[v2.6.11, v2.5.12].
    - Can only install one of: symfony/console[v2.6.12, v2.5.12].

**Comment by afk11** [comment]
It seems there's a conflict between `mdanter/ecc` and Laravels `symfony/console`, unless the console package is being roped in elsewhere in this package. 

Afaict, symfony/console was removed from mdanter/ecc in a recent commit, it must not have been tagged. I'll review this and see what's up, though can't promise an immediate fix as we're due a major release anyway. Will post back in a while!

**Comment by chris41188** [comment]
Thanks for your response,
is there anyway other way to install bitwasp? I just need a function to verify a signed message with a signature and address

**Comment by afk11** [comment]
Could fork phpecc on packagist, setting the dependency to whatever's in your Laravel file?

**Comment by afk11** [comment]
There was a release candidate of phpecc recently, perhaps try v0.0.26?

**Comment by afk11** [comment]
Closing, think was fixed already
