### ISSUE TITLE
 bitcoin-php/examples/transactionBuilder.php doesn't work anymore

### ISSUE THREAD

**Issue by DeftNerd** [Bit-Wasp/bitcoin-php#302]
The example doesn't work anymore. TransactionFactory doesn't seem to allow getHex() (line 15)

Too bad, it was such a clear and simple example. A lot of the other examples are segwit focused.

**Comment by afk11** [comment]
That file works for me, are you calling get() in your code?

**Comment by afk11** [comment]
I see it's described in the docs :) https://github.com/Bit-Wasp/bitcoin-php/blob/master/doc/Transaction.md#simple-output-script-pay-to-pubkey-hash
