### ISSUE TITLE
Electrum deterministic private keys?

### ISSUE THREAD

**Issue by DeftNerd** [Bit-Wasp/bitcoin-php#303]
Am I misunderstanding something? The Deterministic/HierarchicalKey code allows you to get the deterministic child pubkey along with its associated private key. 

There doesn't seem to be the same option for ElectrumKey

The Docblock at https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Key/Deterministic/ElectrumKey.php#L100 says that the deriveChild function should return both a PrivateKeyInterface and a PublicKeyInterface, but all I'm getting back is BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PublicKey

Thoughts?

**Comment by afk11** [comment]
Hrm. It seems the method to derive a private key isn't there. It could be cleaned up.. I think KeyInterface exposes `tweakAdd` on a private/public key, so technically _deriveChild_ ought to return as the doc comment indicates (making it similar to HierarchicalKey)

If you need it ASAP:
```php
$seq = 0;
$isChange = false;
$priv = $elec->getMasterPrivateKey()->tweakAdd($elec->getSequenceOffset($seq, $isChange));
```

I might get to this today, that class doesn't look entirely right.
