### ISSUE TITLE
Composer conflict between Laravel and BitWasp in your dev-master branch

### ISSUE THREAD

**Issue by DeftNerd** [Bit-Wasp/bitcoin-php#308]
Love that you're moving from mcrypt to paragonie/random_compat, but the required version (~2.0) is causing a problem with Laravel. 

Laravel is stuck on the paragonie/random_compat ~1.4 stable branch. 

Can you test BitWasp to see if it works with the 1.4 branch and then before the next release do it this way in the composer.json?

"paragonie/random_compat": "~1.4|~2.0",

**Comment by afk11** [comment]
Fixed in v0.0.25
