### ISSUE TITLE
BIP-70 Payment protocol: random address

### ISSUE THREAD

**Issue by codefuhrer** [Bit-Wasp/bitcoin-php#312]
[BIP-70](https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki#motivation) says:
> Merchant generates a unique payment address ...

But in this [example](https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/bip70.start.php) merchant's address is hardcoded. Could you please point me the [right] way to do this?

**Comment by afk11** [comment]
Indeed, you need to manage private keys. There are a few ways to do it, you definitely don't want them on the same machine as your payment page. A HD wallet would do the trick here.

Your payment page would know the extended public key, and derive a new address for every request. You then watch for payment (it's probably best to have the payment requests expire) somehow, and act accordingly. You need to ensure your server is secure, lest someone replace the payment page with their static address, or change the xpub to one they control.

You would need to keep the extended private key elsewhere, perhaps just generating the private keys you know you received payment on, and moving the funds to a different wallet.

**Comment by afk11** [comment]
Did you get this sorted?

**Comment by codefuhrer** [comment]
Thanks, @afk11! So, am I getting it right?

- first of all I need to generate the private key with PrivateKeyFactory
- then from PrivateKey instance I can get the public key and generate the address with AddressFactory
- repeat for each request

I presume it's impossible to fetch the transactions history using this lib?

**Comment by afk11** [comment]
Not quite, read over BIP32 to some of it's features: you need to avoid creating private keys on your payments server.

Re fetching transaction history, it's not done in the library. I do have something written that can query electrum servers for this: https://github.com/Bit-Wasp/stratum-php or else you could use a block explorer API. Blocktrail has an API for creating webhooks for payments to an address, you can set the number of confirmations too IIRC.

Preparation:
 - Derive a HD root key, keeping the secret key material offline. 
 - Put the HD master-public-key on the server

Accepting payments:
 - Generate next HierarchcalKey in sequence, incrementing a counter saved somewhere. 
 - Take the address of your HierarchicalKey, pass to BIP70 stuff. 

Person pays: 
 - Your script gets notification somehow about a payment. 
 - It emails you the address and counter.
 - Derive the private key from master private key and counter, and use a wallet to move the funds elsewhere.

**Comment by codefuhrer** [comment]
Ok, thank you for the clarification!
