### ISSUE TITLE
Advice: How to decode a transaction from hex?

### ISSUE THREAD

**Issue by in3rsha** [Bit-Wasp/bitcoin-php#373]
I apologize for creating an issue for a simple as this, but I couldn't find anything in the examples to get started.
- What are the steps for taking a raw hex transaction and decoding it to get the same result as bitcoin-cli's `decoderawtransaction`?

I can get each individual part:

```
$hex = '0100000001ed0674bb77827f2c49354e5ca7e98bda5ab533a4ec71402af0450ad303a4b71f010000006b483045022100b658797b9d64ac1982cd51b1ebed2288e5425fffcb41096b9e66ee23ae4af46c022070ae040118d0cfbca39c70eb6b4750fabc20e8b6cdbd85360e8cae757f213d97012103e80379927edaeec03ead411e7e39f4345406296454d182c41e18b7a45296b64effffffff02fc170000000000001976a91482a105517ee064dab22dd455a52c6ee3ebad307588ace0fe0700000000001976a91441a0b8066150491d51b58ec7045360b5d5950d5088ac00000000';
$tx = TransactionFactory::fromHex($hex);

var_dump($tx->getTxId());
```

But is there a `$tx->decode()` for the full output?

**Comment by afk11** [comment]
You'd have to call each method and compile the results yourself. Some don't match 100%, like the script to human readable one. Most of the objects are containers for some minimal piece of state, there's always a way to get the data inside them.

**Comment by afk11** [comment]
hey, just thinking, I've started using __debugInfo magic so var_dump($tx) gives you something useful to look at. It's probably the closest (You can also do $info = $tx->__debugInfo()), but if you really want output to be identical to bitcoind you could just write a function `transactionToArray` or something.
