### ISSUE TITLE
Version v0.0.7 does not work with mdanter/ecc v0.4.0

### ISSUE THREAD

**Issue by josecelano** [Bit-Wasp/bitcoin-php#381]
Hi. We are using v0.0.7 (in https://github.com/blockcypher/php-client) and that version (v0.0.7) contains this dependency in the composer.json:

```
mdanter/ecc": "~0.3",
```
https://github.com/Bit-Wasp/bitcoin-php/blob/v0.0.7/composer.json#L30

That version allows to upgrade to the latest mdanter/ecc version (v.0.4.0). But it seems it does not work with mdanter/ecc version higher than `v0.3.1`. Because the API was changed. Thas class Gmp was renamed.

I think the problem should be fixed if you change the dependency to a fixed version on `v0.0.7` . The latest one compatible (v0.3.1).

We would try to upgrade to your latest relase asap.

More info about the related issue:
https://github.com/blockcypher/php-client/issues/21#issuecomment-259064594

**Comment by afk11** [comment]
Ah, you're certainly right. What I can do is merge a commit fixing phpecc to 0.3 and tag that as v0.0.7.1?

**Comment by josecelano** [comment]
Thanks @afk11 that would be perfect!!
