### ISSUE TITLE
Bitcoin.sign_data question

### ISSUE THREAD

**Issue by toxed** [Bit-Wasp/bitcoin-php#399]
In Ruby there is a bitcoin gem.
How i can reproduce next code within your library and is that is possible?

`      keypair = Bitcoin.open_key priv_key
      sig = Bitcoin.sign_data(keypair, [sighash].pack("H*"))`

Please advice, thank you for your work

**Comment by afk11** [comment]
It is -- there are examples in the docs. The library takes care of creating sighash.

https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/signedmessage.create.php
https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/signedmessage.verify.php

**Comment by toxed** [comment]
thank you, i saw https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/signedmessage.create.php but there is a new private key, how i can use exist key for creating sighash?

**Comment by afk11** [comment]
`PrivateKeyFactory::fromWif()` there's also fromInt() and fromHex(). Once you provide the key as shown in the example it'll produce the signature. Check the source code for the files if you need to see what else the classes do.

**Comment by afk11** [comment]
Did you get this working?

**Comment by toxed** [comment]
Yes thank you.
