### ISSUE TITLE
Create multisignature address from public keys

### ISSUE THREAD

**Issue by coumineol** [Bit-Wasp/bitcoin-php#417]
I'm trying to create a multisig address from three public keys (such as 0379ddc228d8c44a85ae30c877a6b037ec3d627e0507f223a0412790a83a46cd5f) but haven't been able to find how. There is the multisig function in https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Script/Factory/OutputScriptFactory.php, but it takes instances of PublicKeyInterface as input. Should I convert the string to a PublicKeyInterface, and if so, how can I do that? Sorry if it's a trivial question, I'm pretty new to this. Thanks.

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/blob/master/doc/Factory%20Classes.md should help you get started building things, then just check the respective Interface's code (eg, ScriptInterface, PrivateKeyInterface, TransactionInterface) for what you can do with them.

**Comment by coumineol** [comment]
Oops, how didn't I see that document? So the answer to my question seems to be using BlockFactory::fromHex($data). Thanks!

**Comment by afk11** [comment]
Feel free to open another if you get stuck!
