### ISSUE TITLE
Signing a multisignature transaction

### ISSUE THREAD

**Issue by coumineol** [Bit-Wasp/bitcoin-php#436]
I'm trying to get a given transaction signed. It's a 3 of 4 multisignature transaction, and has 1 sign on it. I want to enter its hex code and a private key and get the returned transaction, but I get the "Signing with the wrong private key" error. I'm sure that they match. What am I doing wrong?

Here's the code:

$myTransaction = TransactionFactory::fromHex($transaction);

$myPrivateKey = PrivateKeyFactory::fromHex($privateKey, $compressed = TRUE); 

$txOut = $myTransaction->getOutput(0);
$ec = \BitWasp\Bitcoin\Bitcoin::getEcAdapter();

$signed = (new Signer($myTransaction, $ec))
    ->sign(0, $myPrivateKey, $txOut)
    ->get();

Thanks.

**Comment by coumineol** [comment]
By the way this is the transaction, if it's relevant:

https://coinb.in/?verify=01000000014dbd81ef72c3b0177c790eabcb370ff1020f46237d56462c3d51839c11560a8800000000d60047304402207eca346354c4289c4c782fe0507e36e274ef3ab0dd6246df2433f33410ff5b7002203cabd0b54d045cbe20f1a5ea79fe8a8a34e3dcbc24e0aacd707a83f18ad59af2014c8b53210367ba14ca6d26e60b1f1862b6679a2ae86178773661c9f48410b3d6bd97324d64210228b5d0e6a362bee65f6387df2b82dd76003b90fd404e893eea060886a396289721025e915f753f4aa4d137c0e727fe07e613c023e1103fba98ce32e472ecdf06e1a22102cd1c9ae0fcbd9dbe17dec21c2bc56d1486d8b3ca71dbd2be5a8e2bde88effba354aeffffffff0150c30000000000001976a91493cd53fba0f931efd197309ab57fe552d822d06188ac00000000#verify

**Comment by afk11** [comment]
In this case you need to provide the txOut that you're spending (multsig output), not something from the transaction your creating (a P2PKH output). 

You can generate it yourself from the value and the redeemScript:
```php
$scriptChunks = $tx->getInput(0)->getScript()->getScriptParser()->decode();
$redeemScript = new Script($chunks[count($chunks) - 1]->getData());
$txOut = new TransactionOutput($value, ScriptFactory::scriptPubKey()->p2sh($redeemScript)
```

**Comment by coumineol** [comment]
Thanks, it seems to work. I also had to add this:

$signData = new SignData();
$signData->p2sh($redeemScript);

And added $signData to the signer as follows:

sign(0, $myPrivateKey, $txOut, $signData)

One more question, what is the $value and how did you get it exactly? Sorry if it's a trivial thing, I'm quite a novice in this.

**Comment by afk11** [comment]
I mightn't have tagged a new version yet.. You shouldn't have to pass SignData if it's already signed or has the redeemScript, let me take a look. I ignored that part of your example thinking it would have been fine.

Oh, the value is the BTC amount you received on your multisig address (in satoshis!) I just made `1` up, since it comes from the API or whatever. Coinbin probably looked up the address and found the txid, vout, value and scriptPubKey when you made the transaction.

The value is actually *checked* anywhere if your transaction isn't segwit, but don't rely on this behavior in future versions.

**Comment by afk11** [comment]
What version are you using?

**Comment by coumineol** [comment]
I'm using v0.0.31.1. When I don't pass SignData to the sign function it raises the error "Redeem script requested but not set".

Sorry if I'm repeating myself, but isn't there a way to get the BTC amount from the transaction hex in PHP using this library? Or is there a way at all?

**Comment by afk11** [comment]
Ah ok, just the one before! Yeah, SignData became unnecessary if the details in the transaction are enough. 

Actually, the amount is only set in the transaction that created the

**Comment by coumineol** [comment]
Thanks for taking the time to explain. I was a bit confused on what a transaction consists of, but I think I'm slowly starting to figure things out :)

And by the way, thanks for creating this library too. It's already helped me enormously!
