### ISSUE TITLE
catch exception

### ISSUE THREAD

**Issue by Pekinese** [Bit-Wasp/bitcoin-php#438]
How to catch an exception which for example may occur when bitcoind is offline?
Wasn't able to solve this by using:

    private function getAddress(){

        //...prepare connection
        try{
            $response = $client->sendCommand($command);
            return json_decode($response->getBody()->getContents());
        }
        catch(Exception $e){
            return json_encode([
                'errors' => 'server offline',
                ]);
        }
    }

**Comment by afk11** [comment]
This looks like nbobtc/bitcoind-php, but you opened the issue on bitwasp/bitcoin-php. Are you sure you're posting in the right place, because I didn't write that.
