### ISSUE TITLE
Simple output script example does not work.

### ISSUE THREAD

**Issue by ryny24** [Bit-Wasp/bitcoin-php#441]
I've spent a few days trying to build and sign a transaction with BitWasp, but I can't get past this error. This [example](https://github.com/Bit-Wasp/bitcoin-php/blob/master/doc/Transaction.md#simple-output-script-pay-to-pubkey-hash) has the following code

`$outputScript = ScriptFactory::scriptPubKey()->payToPubKeyHash($privateKey->getPublicKey());`

But this statement returns the following error

` Uncaught TypeError: Argument 1 passed to BitWasp\Bitcoin\Script\Factory\OutputScriptFactory::payToPubKeyHash() must implement interface BitWasp\Buffertools\BufferInterface, instance of BitWasp\Bitcoin\Crypto\EcAdapter\Impl\Secp256k1\Key\PublicKey given, called in /tmp/test.php on line 17 and defined in /home/orangepi/bitcoin-php/src/Script/Factory/OutputScriptFactory.php:90
Stack trace:`

I cannot figure out how to get past this.

**Comment by ryny24** [comment]
I might have resolved this myself by changing the example code to the following...

`$outputScript = ScriptFactory::scriptPubKey()->payToPubKeyHash($privateKey->getPubKeyHash());`

**Comment by afk11** [comment]
Your fix was right. Please PR it to the examples - they fell out of date with a backwards incompatible change, but given the library has not marked a major release according to semver, this can happen (not very often, but sometimes!)

I love PR's that fix technical debt incurred by leaving random unverified examples around ;) Thinking the solution to this problem might be to compile a Jekyll site out of the examples that are tested by travis, these documentation/code mismatches suck.

**Comment by afk11** [comment]
That is, I wish the documentation wasn't causing you trouble, the main reason it exists is for first time users, but it's a bit fragile.
