### ISSUE TITLE
Q: Using regtest mode with the library

### ISSUE THREAD

**Issue by melanholly** [Bit-Wasp/bitcoin-php#442]
While I read the code and the documentation I see that there is a way to use `testnet` but I can't seem to find a way for `regtest` network. 

So can I use `regtest` network with this library?

I don't have a lot of knowledge about the difference between `regtest` network and the `main` one.

**Comment by afk11** [comment]
Yeah it works, I'll add the network to NetworkFactory in a few

**Comment by melanholly** [comment]
Thank you! After [reading some documents](https://bitcoin.org/en/developer-examples#regtest-mode) I seems like `regtest` is just like `testnet` except that the developer can generate blocks on demand.

**Comment by afk11** [comment]
Yeah pretty much, it has difficulty 1/512 or something. The differences probably won't come up in normal applications since it's for testing purposes

**Comment by afk11** [comment]
yeah very few differences as far as this library is concerned, mostly only matters if you're implementing the proof of work stuff. Since the p2p message bytes differ it's probably worth including it separately to testnet.

**Comment by melanholly** [comment]
Thank you for the fast response I will wait for this pull request to be merged.

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/releases/tag/v0.0.32.1
