### ISSUE TITLE
Php error occured 

### ISSUE THREAD

**Issue by dbdeadka** [Bit-Wasp/bitcoin-php#467]
https://github.com/Bit-Wasp/bitcoin-php/blob/master/doc/Transaction.md#simple-output-script-pay-to-pubkey-hash

If I use code line 
$outputScript = ScriptFactory::scriptPubKey()->payToPubKeyHash($privateKey->getPublicKey());
then code falls down with

**PHP Catchable fatal error:  Argument 1 passed to BitWasp\Bitcoin\Script\Factory\OutputScriptFactory::payToPubKeyHash() must implement interface BitWasp\Buffertools\BufferInterface, instance of BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PublicKey given, called in /tmp/index.php  line 18 and defined in /tmp/vendor/bitwasp/bitcoin/src/Script/Factory/OutputScriptFactory.php on line 89**

but if i change this code line to 

$outputScript = ScriptFactory::scriptPubKey()->payToPubKeyHash($privateKey->getPubKeyHash());

then error does not appears.

It seems to me that getPubKeyHash has to be here, no getPublicKey.

**Comment by olegabr** [comment]
see #468

**Comment by afk11** [comment]
Yeah, documentation issue, source code is the best to check. Looking to compile from examples now going forward, I should spend better effort on the docs! 

It's improving soon, thanks for the pull request fixing things

**Comment by afk11** [comment]
fixed with #468
