### ISSUE TITLE
Not an issue, but a question please

### ISSUE THREAD

**Issue by RussianSwiss** [Bit-Wasp/bitcoin-php#469]
Great xpub libs! Thank you very much for them!

1. Would you be so kind to let me know **how can one spend from e.g. 10000000's address?**

I have a list of indexes to which payments were made: 1137's, 93924's, 427104's, 17480001's addresses etc. Usual gap limit for the majority of wallets is 20. I need to be able to spend from exact index of the multitude of addresses.

2. **GAE doesn't support gmp. Maybe you know how to install gmp to GAE?**

3. *Uncaught Error: Class 'HierarchialKeyFactory' not found in ...*

**Comment by sniper7kills** [comment]
@RussianSwiss If you could provide some additional insight to your code I might be able to help;

Does this code help at all?

```
<?php
require_once('vendor/autoload.php');
use BitWasp\Bitcoin\Key\Deterministic\HierarchicalKeyFactory;
//Build Wallet
$key = HierarchicalKeyFactory::fromExtended("xpub661MyMwAqRbcGL2QoVnUfWuSrF9VM2MTvvCr6RrV8NWJRqYbxkmNULpGf1aHcjV7z7ownfg4hv5cr49FPd5TEUZeYRkbjPtsNniRHV34ufS");
echo "Root: ".$key->toExtendedKey().PHP_EOL;
for($x=0;$x<999999;$x=$x+$x+1){
	echo $x.": ".$key->deriveChild($x)->toExtendedKey().PHP_EOL;
}
```

**Comment by afk11** [comment]
1. Well, first derive all the addresses and check them for a balance. Then with the utxos on each address, you add them to the transaction builder. You need to know private keys (by index) signs which utxo. Then sign the inputs with the right key. 

2. If you don't have GMP you'll have a hard time using the library, it's used everywhere.
3. GAE specific?

**Comment by afk11** [comment]
Still need help with this?

**Comment by RussianSwiss** [comment]
Yes, please!

**Comment by RussianSwiss** [comment]
To @afk11:

1. Would you be so kind to help me figure out how to get extended private key for address by index?
2. I'd like to use gmp. But how to use it with GAE.
3. Not GAE specific. Run locally on Mac.

**Comment by afk11** [comment]
Sorry, lost track of this one. Normally pretty easy - deserialize, and call deriveChild / derivePath to get the desired path or index. Check https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Key/Deterministic/HierarchicalKeyFactory.php for parsing extended keys, and https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/bip32.php on calling deriveChild / derivePath.

no idea about number 2, 3 sounds weird if you did a composer install..

**Comment by afk11** [comment]
Closing this for now
