### ISSUE TITLE
Electrum MultiSig

### ISSUE THREAD

**Issue by sniper7kills** [Bit-Wasp/bitcoin-php#470]
First off, Thank you for this amazing library, It makes life much easier!
Secondly; is it possible to use the multisig.HD example to generate a multisig wallet that could be imported into Electrum?

I feel that it should just be a matter of changing the derivePath variable, but I also see the Electrum Key that does not look compatible with the multisig.HD example. Due to my lack on knowledge I thought I'd just ask.

**Comment by sniper7kills** [comment]
After playing around a little bit I've found what I was looking for.

After creating a MultisigHD wallet;
```
...

$hd = new MultisigHD(2, 'm', $k, $sequences, true);
for($ID=0;$ID<20;$ID++){
    $RecieveAddress = $hd->derivePath("0/".$ID);
    status($RecieveAddress);
}
for($ID=0;$ID<20;$ID++){
    $ChangeAddress = $hd->derivePath("1/".$ID);
    status($ChangeAddress);
}

...
```

**Comment by afk11** [comment]
Sorry I missed this, currently away from my machine. Glad you got sorted!
