### ISSUE TITLE
NetworkFactory::litecoin();

### ISSUE THREAD

**Issue by romanornr** [Bit-Wasp/bitcoin-php#478]
Hi when I create an xpub with the Litecoin electrum wallet, I notice there's a slight difference in address.

When I do 
$network = NetworkFactory::litecoin();
$xpub = .....
$hk = HierarchicalKeyFactory::fromExtended($xpub, $network);

I get a Base58ChecksumFailure

**Comment by afk11** [comment]
Is there a difference or does it throw the Base58 exception? Post your xpub?

**Comment by romanornr** [comment]
my xpub 
````xpub661MyMwAqRbcGv41soRbrusmwZbs1HsXaAWBMF1NbQRAJMJ3Ns8RYJLaDpXo5R4pdTm64Ad8YXaTMBfYVkEPSLDifj73YU5CimVwGPSk3EA```

Also I tried ````Ltub661MyMwAqRbcGv41soRbrusmwZbs1HsXaAWBMF1NbQRAJMJ3Ns8RYJLaDpXo5R4pdTm64Ad8YXaTMBfYVkEPSLDifj73YU5CimVwGPSk3EA````

**Comment by romanornr** [comment]
maybe this helps @afk11 
https://github.com/Bit-Wasp/bitcoin-lib-php/blob/master/src/BIP32.php#L60

https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L131

Maybe the magic numbers don't match

Electrum has support for both 
https://github.com/pooler/electrum-ltc/blob/master/lib/bitcoin.py#L44-L46

**Comment by romanornr** [comment]
nvm my bad ! 
http://bip32.org/

**Comment by afk11** [comment]
Sorry, got caught up elsewhere, didn't get to digest this one fully. I know litecoin supports both sets of bytes, I'd just try both.. though I guess knowing litecoin does this helps :P
