### ISSUE TITLE
Can't get address from pubKey

### ISSUE THREAD

**Issue by unvo1d** [Bit-Wasp/bitcoin-php#481]
```
$pubKey = '30440220401186e39a8ff0c64a6be2256ed4c818e09ff35ddf60bb1678f6ceaa3268fa5802203ec554c18a3bcf6eed34c279c4057afb04d4b73d2f6dc46ea97d9f6b9a3c7819';

$publicKey = BitWasp\Bitcoin\Key\PublicKeyFactory::fromHex($pubKey);
```
Gives exception:

> Invalid hex string, must match size of compressed or uncompressed public key
> bitwasp/bitcoin/src/Crypto/EcAdapter/Impl/PhpEcc/Serializer/Key/PublicKeySerializer.php on line 83

Why?

**Comment by afk11** [comment]
That's a signature

**Comment by unvo1d** [comment]
Can I somehow generate public key(s) from it?

**Comment by afk11** [comment]
Not in a way supported by the library, there isn't a huge reason to support it specifically - what is it you're trying to do?

**Comment by unvo1d** [comment]
I was trying to parse list of share holders in one of ALT.
https://github.com/elastic-project/genesis-block/blob/master/genesis-block.json

**Comment by afk11** [comment]
Ah - cool! There's probably enough parts here to do it, but you should also double check it can't be learned by just looking up the txid/vout where you saw the signature, and checking that scriptPubKey for the pubkey.

I think it's a little easier than going the signature recovery route, you'd just use the RPC with txindex.

Did you get the signature above from the txids in that file, or where? I'll post something later, away from keyboard atm

**Comment by afk11** [comment]
Hey, did you check if those txs have the public key in the output script?

**Comment by afk11** [comment]
Closed due to inactivity

**Comment by wirwolf** [comment]
In my local regtest network 
`getrawtransaction bf6ea04bcb18121567bcaaebf8a60e7422cdb2d03b2c9153a93e42893408b1ee 2`

`
{
  "hex": "02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff03510101ffffffff020060a0da38f4010023210317bb6666c8ab66cf392432b66bd83a87f05f81e5169a306038778548b2cee004ac0000000000000000266a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf900000000",
  "txid": "bf6ea04bcb18121567bcaaebf8a60e7422cdb2d03b2c9153a93e42893408b1ee",
  "hash": "bf6ea04bcb18121567bcaaebf8a60e7422cdb2d03b2c9153a93e42893408b1ee",
  "size": 145,
  "vsize": 145,
  "version": 2,
  "locktime": 0,
  "vin": [
    {
      "coinbase": "510101",
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 5500000.00000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "0317bb6666c8ab66cf392432b66bd83a87f05f81e5169a306038778548b2cee004 OP_CHECKSIG",
        "hex": "210317bb6666c8ab66cf392432b66bd83a87f05f81e5169a306038778548b2cee004ac",
        "reqSigs": 1,
        "type": "pubkey",
        "addresses": [
          "mfvF9ynrGPWfvi5WutH8AY9MTEYeh6bLfX"
        ]
      }
    }, 
    {
      "value": 0.00000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_RETURN aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9",
        "hex": "6a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9",
        "type": "nulldata"
      }
    }
  ],
  "blockhash": "20c5969bd967479cb6d23cf72a34d213f8f797f62d340509e5a7292ed64dc661",
  "confirmations": 102,
  "time": 1531221809,
  "blocktime": 1531221809
}

`
`

$transaction = TransactionFactory::fromHex($rawTransaction);
foreach ($transaction->getOutputs() as $n => $item) {
    $addrCreator = new AddressCreator();
    $addrrss = $addrCreator->fromOutputScript($item->getScript());
}

`
