### ISSUE TITLE
How to extract addresses/address from multisig-scriptPubKey (continue of #479).

### ISSUE THREAD

**Issue by dbdeadka** [Bit-Wasp/bitcoin-php#483]
Excuse me, I was not online last weeks. Thank you for the answer, situation is more understandable.
It seems to me that in last case it's better to return that addresses, which it is possible to extract from scriptpubkey (like in https://github.com/bitcoin/bitcoin/blob/8152d3fe57a991e9088d0b9d261d2b10936f45a9/src/script/standard.cpp#L228
 ), but, certainly it's IMHO only.

But story is not finished yet :(. Try please to execute next snippet of code (based on 
https://www.blocktrail.com/BTC/tx/d01a99b5cf7b258d1431822b0fe151772023ca525269369ce6157bf6e32041cb?txoutIdx=3

):

```
<?php

require __DIR__ . "/../vendor/autoload.php";

$hex = "5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba252102b31fd38ae163eeaeeec62aca9e39fd925128b6cb4d579f2a50795d3418cff92752ae";
$script = new \BitWasp\Bitcoin\Script\Script(\BitWasp\Buffertools\Buffer::hex($hex));
$solutions = null;
$decoded = $script->getScriptParser()->decode();
$classifier = new \BitWasp\Bitcoin\Script\Classifier\OutputClassifier();

$type = $classifier->classify($script,$solutions);
print "type = " . $type . PHP_EOL;
print "size of soultions = " . count($solutions) . PHP_EOL;

$a1 = BitWasp\Bitcoin\Key\PublicKeyFactory::fromHex($solutions[0])->getAddress()->getAddress();
$a2 = BitWasp\Bitcoin\Key\PublicKeyFactory::fromHex($solutions[1])->getAddress()->getAddress();
```

Code fails:

username@machinename:~/bitcoinphp-lib/tests$ php multisig1.php
type = multisig
size of soultions = 2
PHP Fatal error:  Uncaught exception 'LogicException' with message '36126036814164657098511955728052231927830236627713106616318751105840950552302 has no square root modulo 115792089237316195423570985008687907853269984665640564039457584007908834671663' in /home/username/bitcoinphp-lib/vendor/mdanter/ecc/src/Math/NumberTheory.php:197
Stack trace:
#0 /home/username/bitcoinphp-lib/vendor/mdanter/ecc/src/Primitives/CurveFp.php(125): Mdanter\Ecc\Math\NumberTheory->squareRootModP(Object(GMP), Object(GMP))
#1 /home/username/bitcoinphp-lib/vendor/bitwasp/bitcoin/src/Crypto/EcAdapter/Impl/PhpEcc/Adapter/EcAdapter.php(331): Mdanter\Ecc\Primitives\CurveFp->recoverYfromX(false, Object(GMP))
#2 /home/username/bitcoinphp-lib/vendor/bitwasp/bitcoin/src/Crypto/EcAdapter/Impl/PhpEcc/Serializer/Key/PublicKeySerializer.php(87): BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Adapter\EcAdapter->publicKeyFromBuffer(Object(BitWasp\Buffertools\Buffer))
#3 /home/username/bitcoinphp-lib/vendor/bitwasp/bitcoin/src/Key/PublicKeyFactory.php(29): BitWasp\Bitcoin\Crypto in /home/username/bitcoinphp-lib/vendor/mdanter/ecc/src/Math/NumberTheory.php on line 197

My php version:
$ php --version
PHP 5.6.11-1ubuntu3.4 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

In the same time:

bitcoind@machinename:/home/username$ bitcoin-cli decodescript 5141046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba252102b31fd38ae163eeaeeec62aca9e39fd925128b6cb4d579f2a50795d3418cff92752ae
{
  "asm": "1 046102da5b459ddd9db7da926ea5a80efb4e13260f155566193f401c9f182e2862df3829aafbc8b014eba374c70d1d2b94cd08f887a29b1aa55ad4e31f906eba25 02b31fd38ae163eeaeeec62aca9e39fd925128b6cb4d579f2a50795d3418cff927 2 OP_CHECKMULTISIG",
  "reqSigs": 1,
  "type": "multisig",
  "addresses": [
    "18888888PPJ8oGeqR6AKmoiKUme9da48Xf",
    "1NLj9gQZwTQBgNApxqcA7fM41E8usnUsXg"
  ],
  "p2sh": "3BySBpZgkeirer6SDBhogQYy6LMEG8b3vc"
}

How could you comment this behaviour?

**Comment by dbdeadka** [comment]
Is anybody here?

**Comment by afk11** [comment]
Hi, took a look at this. It seems the key is invalid, and the multisig class really complains when that happens.. Mastercoin seems to have added an invalid key as the second in that multisig, so the library can't create a PublicKey instance for it (libsecp256k1 errors also).

I'm going to think about this one.. maybe key parsing shouldn't be done in the Multisig class. Currently Mastercoin would not be able to produce that transaction with this library :P

**Comment by dbdeadka** [comment]
Hi, afk11, thank you for the feedback, I waited this ). ASAP I'll try to implement your recommendation.

**Comment by afk11** [comment]
I think I will stop deserializing in the constructor, and remove getKeys from Multisig. Other parts of the library also assume that it will _always_ return PublicKeyInterface[] where len=$n from the multisig.. but it can't guarantee that. The safest thing is just to return the Buffer and let the consumer decide what to do about the invalid key. At least the instance can still be created and return the key count, signature count, etc. 

The InputSigner also assumes the same. I'll change that to gracefully deal with invalid keys (though it by default be disabled) so that the library can spend outputs like these.

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/pull/514 this branch would remove the getKeys function, allowing you to parse the buffers for yourself. That way if you hit the error, you still know it was multisig, the required sigs, the key count, plus the public key buffers, which you can hash to produce the addresses by hand.

It's probably impossible to spend from them however.. so take care before showing them to people. You could use `\BitWasp\Bitcoin\Crypto\EcAdapter\Impl\Key\PublicKey::isCompressedOrUncompressedKey()` (or similar, sorry it's all the way in there) to apply some kind of duck test to the data being hashed for the address.

**Comment by afk11** [comment]
The changes for Multisig are now in a tagged release. It's API is a little different, but it won't explode if some keys are invalid.
