### ISSUE TITLE
How to get xpriv (extended private key) from mnemonic by index?

### ISSUE THREAD

**Issue by RussianSwiss** [Bit-Wasp/bitcoin-php#486]
Can anyone share php code for getting xpriv (extended private key) from mnemonic for $i address?
This must be pretty simple but I still cannot figure out the code. Please help!

**Comment by afk11** [comment]
What mnemonic type? What path did you use to derive them (BIP32 can have multiple levels to key derivation)

Maybe these examples will help https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/bip32.php https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/bip39.php

**Comment by RussianSwiss** [comment]
Hi! I used this one:
```
use BitWasp\BitcoinLib\BIP32;
...
$master = array($xpub, "M");
$def = "0/$i";
$key = BIP32::build_key($master, $def);
$address = BIP32::key_to_address($key[0]);
```

**Comment by afk11** [comment]
That example is from the old library! The bip32 example should get you started. 

* Parse the xpub: ://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/bip32.php#L15 
* Derive the child: 0/1 https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/bip32.php#L31

Get the address:
```php
$address = $hdKey->getPublicKey()->getAddress();
echo $address->getAddress();
```

**Comment by RussianSwiss** [comment]
Ok. And then how do I get priv key?

**Comment by RussianSwiss** [comment]
I've done it. Thanks!

But how can I transfer **mnemonic** (i.e. from Copay) to **xprivkey**?

**Comment by afk11** [comment]
Hmm, you'd need to find out what scheme they use (probably BIP39?) to derive the entropy for the key, then generate the xprv for whatever index you need.

**Comment by RussianSwiss** [comment]
I found out the scheme.

I can’t figure out the code to transfer *mnemonics into xpriv* of any index
address.

сб, 5 авг. 2017 г. в 23:12, Thomas Kerin <notifications@github.com>:

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/bip32.php this does two ways of deriving the index.. it doesn't show hardened keys. what path are you trying to derive?
