### ISSUE TITLE
Create a multisig address from public keys

### ISSUE THREAD

**Issue by zilveer** [Bit-Wasp/bitcoin-php#500]
Hello,
I would like to create a multisig address from 2 public keys .
I have been trying to get this work, it is pretty simple I think but I cannot get it work.

`require __DIR__ . "/../../../../vendor/autoload.php";

use BitWasp\Bitcoin\Bitcoin;
use BitWasp\Bitcoin\Address\AddressFactory;
use BitWasp\Bitcoin\Key\PrivateKeyFactory;
use BitWasp\Bitcoin\Script\ScriptFactory;
use BitWasp\Bitcoin\Script\Factory;
use BitWasp\Bitcoin\Key\PublicKeyFactory;
use BitWasp\Bitcoin\Network\NetworkFactory;
use BitWasp\Buffertools\Buffer;
use BitWasp\Bitcoin\Script\Factory\OutputScriptFactory;

$privateKey1 = PrivateKeyFactory::fromHex('5bce4b3976d53b7cc3743e488f28ea023995332ab36758d3a2411783796b7ec0', true);
$privateKey2 = PrivateKeyFactory::fromHex('48fdcb0d50826f876d9487d31e03124846b735f756914df7b6aa2cb70c4a68c9', true);
echo '<br />';
echo $privateKey1->getAddress()->getAddress();
echo '<br />';
echo $privateKey2->getAddress()->getAddress();
echo '<br />';

$redeemScript = ScriptFactory::p2sh()->multisig(2, array($privateKey1->getPublicKey()->getHex(), $privateKey2->getPublicKey()->getHex()));
print $redeemScript->getAddress()->getAddress();`

But I cannot get it work, can anyone give me advice about how to solve this issue?

All kind of help is appreciated.

**Comment by afk11** [comment]
Don't convert the public keys to hex in the array passed to `multisig()` and it should work

**Comment by zilveer** [comment]
What if I get the public key as a hex format from a user ? 

Thanks for your reply.

**Comment by afk11** [comment]
Parse it from hex :)

\BitWasp\Bitcoin\Key\PublicKeyFactory::fromHex()

**Comment by zilveer** [comment]
@afk11 Thank you for your help, but I still have the issue:

Right now the code looks like this when generating the multisig address:
```
$redeemScript = ScriptFactory::scriptPubKey()->multisig(2, array($privateKey1->getPublicKey(), $privateKey2->getPublicKey()));
echo  $redeemScript->getAddress()->getAddress();
```

But I get this error code:
`Fatal error: Call to undefined method BitWasp\Bitcoin\Script\Script::getAddress()`

How do I get the multisig generated address?

regards

**Comment by afk11** [comment]
Script::getAddress was removed, you can add this back by doing `new P2shScript($multisig)`, which also caches the scriptHash, address, and other bits. Then you'll have getAddress again

**Comment by zilveer** [comment]
@afk11 thanks I got it running now:)

Perhaps we could have an extra directory in the examples called something like "user_examples" and add this to it?

The whole code for generating multisig address looks like this now:
```

<?php

require __DIR__ . "/../../../../../vendor/autoload.php";

use BitWasp\Bitcoin\Bitcoin;
use BitWasp\Bitcoin\Address\AddressFactory;
use BitWasp\Bitcoin\Key\PrivateKeyFactory;
use BitWasp\Bitcoin\Script\ScriptFactory;
use BitWasp\Bitcoin\Script\Factory;
use BitWasp\Bitcoin\Key\PublicKeyFactory;
use BitWasp\Bitcoin\Network\NetworkFactory;
use BitWasp\Buffertools\Buffer;
use BitWasp\Bitcoin\Script\Factory\OutputScriptFactory;
use BitWasp\Bitcoin\Script\P2shScript;

$privateKey1 = PrivateKeyFactory::fromHex('5bce4b3976d53b7cc3743e488f28ea023995332ab36758d3a2411783796b7ec0', true);
$privateKey2 = PrivateKeyFactory::fromHex('48fdcb0d50826f876d9487d31e03124846b735f756914df7b6aa2cb70c4a68c9', true);
echo '<br />';
echo 'priv1: '.$privateKey1->getAddress()->getAddress();
echo '<br />';
echo 'pub1: '.$privateKey1->getPublicKey()->getHex();
echo '<br />';
echo 'pub1: '.PublicKeyFactory::fromHex( $privateKey1->getPublicKey()->getHex() )->getHex();


echo '<br />';echo '<br />';
echo 'priv2: '.$privateKey2->getAddress()->getAddress();
echo '<br />';
echo 'pub2: '.$privateKey2->getPublicKey()->getHex();
echo '<br />';
echo 'pub1: '.PublicKeyFactory::fromHex( $privateKey2->getPublicKey()->getHex() )->getHex();



$redeemScriptHex = ScriptFactory::scriptPubKey()->multisig(2, array($privateKey1->getPublicKey(), $privateKey2->getPublicKey()));
$redeemScript = new P2shScript($redeemScriptHex);

echo '<br />';
echo $redeemScript->getAddress()->getAddress();
echo '<pre>';
print_r($redeemScript);
echo '</pre>';
```
