### ISSUE TITLE
How to better calc current balance

### ISSUE THREAD

**Issue by n0n0n0n0** [Bit-Wasp/bitcoin-php#502]
How to better calculate current balance of specific wallet? How do you guys do it? I need to know how much confirmed/unconfirmed funds but wont load all TX it'll ruin my server if do it with PHP. mb you using some api/etc? Explain please if possible, thanks!

**Comment by rawmaterials** [comment]
query https://chain.so/api/v2/get_tx_unspent/btc/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa

and sum of "value" = current available balance.

**Comment by n0n0n0n0** [comment]
I think better use local base to avoid downtime but didnt find any solution how to do it

**Comment by afk11** [comment]
You could query bitcoind, or better yet, use an API. You could look at using electrum servers (plenty of redundancy) https://github.com/bit-wasp/stratum-php - though it uses ReactPHP which might be a learning curve. You could implement it using synchronous sockets if you like, though.

**Comment by afk11** [comment]
That said, this question is off topic here, you need to find your own data storage solution :)
