### ISSUE TITLE
Text signing

### ISSUE THREAD

**Issue by n0n0n0n0** [Bit-Wasp/bitcoin-php#505]
Are there any examples? How to sign/verify text? Thanks!

**Comment by zilveer** [comment]
Check our the examples:
[https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/signedmessage.create.php](https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/signedmessage.create.php)

[https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/signedmessage.verify.php](https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/signedmessage.verify.php)
