### ISSUE TITLE
How to decode SIGHASH type on a TX hex ?

### ISSUE THREAD

**Issue by zilveer** [Bit-Wasp/bitcoin-php#508]
Hello,
Is it possible to decode SIGHASH type on a TX hex through Bitwasp?
If so, how can I do that ?

Regards

**Comment by afk11** [comment]
I'll push an example of this, but not sure I want to maintain it as library code at the moment. They might differ for Blackcoin, so you may need to change that function slightly. https://github.com/Bit-Wasp/bitcoin-php/pull/509

**Comment by zilveer** [comment]
Hi,
The SIGHASH flags are the same.

Thanks , I am looking forward for your example.

Regards

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/sighash.parse.php

**Comment by zilveer** [comment]
@afk11 thanks, I saw it.
 
Now to the main question, how I can I use this to determine the SIGHASH type on a TX ?
I really dont have any clue.

Regards

**Comment by afk11** [comment]
Transactions have inputs which have signatures. You would be better off explaining why you need to know what the sighash types are...I can tell you what to do then :D

On 6 August 2017 18:23:09 CEST, zilveer <notifications@github.com> wrote:
>@afk11 thanks, I saw it.
> 
>Now to the main question, how I can I use this to determine the SIGHASH
>type on a TX ?
>I really dont have any clue.
>
>Regards
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Bit-Wasp/bitcoin-php/issues/508#issuecomment-320516896

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zilveer** [comment]
@afk11 
Thanks for your reply..
I would rather prefer like to take this privately if you really would like to know what I want to do?
I assume that you got my email address, if not please let me know.
I have searched for your e-mail address but cannot fint it :/

best regards

**Comment by zilveer** [comment]
@afk11 
I am creating a multisig game and need to validate the TX hex, and SIGHASH type will be one of the validations steps to validate it. In my case it needs to be set to SIGHASH single.

If you can come up with an example, I would appreciate it.

Hope to get a reply from you regarding this.

regards
