### ISSUE TITLE
Example with checkSignatureEncoding?

### ISSUE THREAD

**Issue by zilveer** [Bit-Wasp/bitcoin-php#512]
Hello,
is there any example of how I can run checkSignatureEncoding or isValidSignatureEncoding with a signed TX hex?

Any help is appreciated.
regards

**Comment by afk11** [comment]
See the native interpreter uses Checker, which has the functions you want. They're not used much outside of script validation though, you'd probably want to have validated the whole script first.. But then the code would have already ran :)

https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Script/Interpreter/Interpreter.php#L216
https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Script/Consensus/NativeConsensus.php

You're the only person who has asked about this stuff by the way, so please excuse the lack of examples for now.

**Comment by zilveer** [comment]
The reason I would like to do this is to decode the SIGHASH type of a 2-of-2 P2PSH transaction TX which is signed.

I really don't have any clue on where to start.
Since I have the TX hex, we could get the public keys, redeemScript as well as the scriptsig I assume.

But then ? I am stuck and don't really know where to start. I am Still pretty new to Bitwasp and would rralöy appreciate your help if you can show me an example.

**Comment by afk11** [comment]
Read both of these and you should know what to do to create a Checker for a txin

https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Script/Consensus/NativeConsensus.php#L36
https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Script/Interpreter/Checker.php#L95

but if you're not sure where to start.. why are you trying to use those functions? They're reserved only for use _by_ the script interpreter, which you control by setting flags. Not for manually parsing out a signature and validating them in isolation.

**Comment by zilveer** [comment]
I have gone through the examples but I am still stuck , still don't know how to use it:/

If I knew how I could use the flags in the script I would be very glad

But I am still new to this and therefore it's hard for me to fully understand it.

I sent you a reply on the other issue.
Perhaps we can talk privately ?
Give me a chance to talk to you.

Thx once again.

**Comment by zilveer** [comment]
I think I got how the verification flags are working now.
Thanks will close this issue now.

regards
