### ISSUE TITLE
How to create a SIGHASH Single blank check transaction?

### ISSUE THREAD

**Issue by zilveer** [Bit-Wasp/bitcoin-php#513]
Hello,
I wonder if it is possible to create a SIGHASH Single "blank check" with Bitwasp?
If so,how does the code look like when creating the SIGHASH Single "blank check"?

Thanks any reply.

**Comment by afk11** [comment]
It sure is. I don't have time to write up an example however, but check out the protocol documentation on this type of thing, you should be able to make one similar to the other transaction signing examples.

**Comment by afk11** [comment]
I wrote up an example for this at some point, maybe it helps. https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/tx.sighash.single.bug.php
