### ISSUE TITLE
Address validation?

### ISSUE THREAD

**Issue by punto-** [Bit-Wasp/bitcoin-php#516]
Hi. I need to verify that an address that comes from user input is valid. I'm looking at the method AddressFactory::isValidAddress, and it looks like it only checks for the first character of an address, but I understand that addresses include a checksum to verify their own validity, Is there anything that will do that validation? thanks.

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Address/AddressFactory.php#L85

That function is fine to use for validation - it calls `Base58::fromString`, which calls `Base58::decodeCheck` which does checksum part.

**Comment by punto-** [comment]
Ah, I missed that, thanks!
