### ISSUE TITLE
HD Multisig - Generate Extended Keys

### ISSUE THREAD

**Issue by kjsdf9nf89** [Bit-Wasp/bitcoin-php#521]
For my service I have 2 users with their normal public keys. Now I would like derive child public keys from these and generate a 2/3 multisig address. I assume this is possible, as I have seen this before.

Unfortunately, I could not find any examples how to generate the extended public keys from my users normal public keys. If I have understood BIP32 correctly, an extended key is generated with the help of a chain code. 

What I have thought of is this:
pubKey1 -> xpubKey1 -> pubChildKey1 ->
pubKey2 -> xpubKey2 -> pubChildKey2 ->      multisig redeemScript -> multisig address
__________xpubKey3 -> pubChildKey3 -> 

After some bitcoins are paid to the multisig address, the users can sign the address with their private keys.

**Comment by afk11** [comment]
BIP32 doesn't mean you can extend regular public keys, but rather your users would each have a HD root key derived securely (somehow, have fun with that) so you get the xpub and derive the multisignature accounts from them. 

As for using BIP32, search for HierarchicalKeyFactory, and check the BIP32 examples.

**Comment by kjsdf9nf89** [comment]
Thanks for your quick response.
Yes I am aware of that and would generate a HD root key for each user from his public key. Does this library support that?
Will the users then be able to sign multisig transactions generated from the derived child public keys with their own private key?

I know how to use the library for the steps after I have the the xpub keys of my users, but all the examples start with HierarchicalKeyFactory, which takes an extended key as an input, which I do not have yet.

**Comment by afk11** [comment]
>  generate a HD root key for each user from his public key

That's not how BIP32 works. BIP32 keys are derived from an initial entropy source, which must be kept secret (definitely from the service provider)

For key generation, and transaction signing, if it's a web application this should all be taking place in the browser.. this library can do whatever you need it to, but when it comes to users private keys, generating them in PHP is not a good start to the story.

**Comment by kjsdf9nf89** [comment]
I do not want to generate the normal public keys of my users. They have them out of their wallet. So I do not have access to the private keys and they will be able to sign the transaction anywhere.

Anyway, I guess it is not possible to build the extended public key from the users public key on my server. Would it be a good approach to derive child public keys from my own extended keys and use the normal public keys from the users for multisig? Then I would have derivedChildKey + userPubKey1 + userPubKey2 = multisigAddress. 

This would lead to individual addresses for each transaction if I derive a new child key every time right?
