### ISSUE TITLE
segwit xpub

### ISSUE THREAD

**Issue by Head** [Bit-Wasp/bitcoin-php#527]
Is there any documentation how to create segwit addresses out of an xpub? Or isn't that not there yet/even not defined?

**Comment by afk11** [comment]
There's some discussion about such a format on the mailing list, though you can create these addresses from any xpub depending on the script you use! 

I can include a more concrete example shortly, but pretty much it involves taking the key, doing `WitnessProgram::v0($pubkey->getPubKeyHash())` and then calling `AddressFactory::fromWitnessProgram($wp)` I think

**Comment by afk11** [comment]
It depends on the type of address you'd prefer - I'll write an example showing all three addresses for a public key, you can work out which suits you/your users best

**Comment by Head** [comment]
Thank you, that helped a lot!
So for anybody else who's looking for it, that's the code to generate addresses from that new TREZOR xpub, hidden in their beta-wallet:

        $master = HierarchicalKeyFactory::fromExtended('xpub...');
        for($i=0;$i<10;$i++) {
            $pubkey = $master->derivePath( "0/" . $i);
            $wp = WitnessProgram::v0($pubkey->getPublicKey()->getPubKeyHash());
            echo " - m/0'/$i " . AddressFactory::fromScript($wp->getScript())->getAddress() . "<br>";
        }
