### ISSUE TITLE
Confusion regarding hardened/non-hardened keys

### ISSUE THREAD

**Issue by joaojoyce** [Bit-Wasp/bitcoin-php#528]
Hi.

I'm trying to understand BIP32/BIP39/BIP44 and this library is a great help.
Excuse me if this question seems obvious.

I've been doing some code with a test seed and comparing to https://iancoleman.github.io/bip39/
Right now I can get the Root Extended Private Key by doing this.
````
    $mnemonic = "such crystal music eagle attend dragon right hat exclude view measure base dentist involve abuse boat garbage pencil idle ceiling cruise cheap wreck bonus congress song favorite rotate tiny auction vote marriage immune shuffle bullet run item kiss twenty merry change milk unique record school rubber input member";
    $ecAdapter = Bitcoin::getEcAdapter();
    $bip_generator = new Bip39SeedGenerator(MnemonicFactory::bip39());

    $seed = $bip_generator->getSeed($mnemonic);

    $seed = Hash::hmac('sha512', $seed, new Buffer('Bitcoin seed', null, $ecAdapter->getMath()));

    //Root
    $hk = new \BitWasp\Bitcoin\Key\Deterministic\HierarchicalKey($ecAdapter,0,0,0,$seed->slice(32, 32),PrivateKeyFactory::fromHex($seed->slice(0, 32), true, $ecAdapter));
    echo "Root Extended Private Key<br/>";
    print_r($hk->toExtendedPrivateKey(Bitcoin::getNetwork()));

````

My problem is understanding the way child derivation works, particularly in regard to the hardened/non-hardened keys.

In your example it seems that depth=1 keys are always hardened (why is that?) and from then on they are non-hardened. 

How can I explicitly create hardened and non-hardened keys?

Thank you for your work.

**Comment by afk11** [comment]
Uhhh, woops that's a bug in the example! the stuff in echo is wrong :s

You see it's not hardened because when $master->derivePath() is called, the first part `0` doesn't have a `'` (used to specify a hardened key)

So you could compare the results of:

    $key1 = $master->derivePath("0/999999");
    $key2 = $master->derivePath("0'/999999");

**Comment by afk11** [comment]
https://github.com/afk11/bitcoin-php/blob/d4c7b4b9bc54fd4e11463098086cb2beaaca7534/examples/bip32.php is the fixed version, PRing now

**Comment by joaojoyce** [comment]
Oh, that's better, now. 

As soon as I have the time I will take a look at the `derivePath` and `deriveChild` code so I get a better understanding of both.

Some more clarification:

1. Why the double getAddress()?
2. Does this PHP library implement BitID or something similar for auth?

Thank you for your time.

**Comment by afk11** [comment]
1. The AddressInterface implementations capture state about the address, but they don't have a network when constructed (unnecessary coupling). So the second getAddress takes an optional parameter (a $network), if you want to override the default network while converting to a string. 

2. Unfortunately it doesn't - though I imagine it has the parts required. If you find some test fixtures it shouldn't be that hard to test it as pure functions. Probably make it easier to test too!

**Comment by joaojoyce** [comment]
Thank you. 
In case you're interested I'll let you know if I develop something related to BitID.

**Comment by afk11** [comment]
Nice, yea please do! always nice to know where it's being used
