### ISSUE TITLE
Cannot Find Method name getOutput

### ISSUE THREAD

**Issue by arttioz** [Bit-Wasp/bitcoin-php#530]
https://github.com/Bit-Wasp/bitcoin-php/blob/2b8220761ef00efae6a80ac7e6938f796dfe4fa8/examples/offlinetx.p2pkh.testnet.php#L34

**Comment by afk11** [comment]
Can't reproduce, and we have travis tests checking the examples folder.. What version are you using?

**Comment by arttioz** [comment]
I use a version from "composer require bitwasp/bitcoin" (0.0.34). 
I think use object (TXbuilder).

I try to create new Transaction but I don't know how to generate a txHex.
Could you suggest me how to generate the txHex?

**Comment by afk11** [comment]
Yep, just call `getHex()`!

**Comment by arttioz** [comment]
I still cannot generate  $myTx because  
The error is 
ParserOutOfRange in Parser.php line 86:
Could not parse string of required length (too short) 

$privateKey = PrivateKeyFactory::fromHex($private_key);

        **$myTx = TransactionFactory::fromHex($privateKey->getHex());**

        $recipient = AddressFactory::fromString($to_address);

        $spendOutput = 0;
        $spendTx = TransactionFactory::build()
            ->spendOutputFrom($myTx, $spendOutput)
            ->payToAddress($value, $recipient)
            ->get();


        $signer = new Signer($spendTx, Bitcoin::getEcAdapter());
        $signer->sign(0, $privateKey, $myTx->getOutput($spendOutput));

        $new = $signer->get();

        return $new->getHex();

**Comment by afk11** [comment]
>    $myTx = TransactionFactory::fromHex($privateKey->getHex());
this bit doesn't look right, you need `$myTxHex` here

**Comment by afk11** [comment]
Did you get this cleared up?

**Comment by afk11** [comment]
Closed due to inactivity
