### ISSUE TITLE
How to create transaction signature for blockcypher ethereum API

### ISSUE THREAD

**Issue by ftppro** [Bit-Wasp/bitcoin-php#531]
The transaction signing process for the blockcypher ethereum API is explained here:
https://www.blockcypher.com/dev/ethereum/#creating-transactions

When their "addrs" endpoint is called, their API creates a new ethereum address, and a 64-character private key is provided. 

When their "/txs/new" endpoint is called, their API provides a "tosign" string which must be used with the 64-character private key, to produce a signature.

I need to know how to create that signature, which can be used with their "/txs/send" endpoint.

I do not wish to use their signer tool, because it requires that the GO programming language is installed on my server. If I get a new server, I don't want to have to reinstall a bunch of additional libraries.

I looked at the Bitwasp examples, and could not find a method that simply creates a transaction signature.

Please provide specific instructions which describe the simplest method to create a transaction signature for the blockcypher ethereum API.

**Comment by afk11** [comment]
Yeah, this should get you up and running, since they provide the hash...

https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Transaction/Factory/InputSigner.php#L920

On another note, how do you know the hash is for the details you sent? :P

**Comment by ftppro** [comment]
Please describe how I should call this function with the [64-character private key] and the ["tosign" string] as the arguments, to receive the [signature string] as the return value.

**Comment by afk11** [comment]
PrivateKeyFactory creates private keys, and you can use the snippet I already linked to sign. Beyond that, come back with a code snippet and a question that you need help on :)

**Comment by afk11** [comment]
This seems to be what their describing, hopefully it works out.

```php
<?php

require __DIR__ . "/../vendor/autoload.php";

use BitWasp\Bitcoin\Bitcoin;
use BitWasp\Bitcoin\Crypto\EcAdapter\EcSerializer;
use BitWasp\Bitcoin\Crypto\EcAdapter\Serializer\Signature\DerSignatureSerializerInterface;
use BitWasp\Bitcoin\Key\PrivateKeyFactory;
use BitWasp\Buffertools\Buffer;

require __DIR__ . "/../vendor/autoload.php";

$adapter = Bitcoin::getEcAdapter();
$math = Bitcoin::getMath();

if ($argc < 2) {
    die('missing hash to be signed');
}

if ($argc < 3) {
    die('missing private key');
}

$hashToSign = Buffer::hex($argv[1]);
$vchKey = Buffer::hex($argv[2]);

if ($hashToSign->getSize() !== 32) {
    echo "Hash is wrong size";
    exit(-1);
}

if ($vchKey->getSize() !== 32) {
    echo "Private key is wrong size";
    exit(-1);
}

$priv = PrivateKeyFactory::fromHex($vchKey);
$ecSig = $adapter->sign($hashToSign, $priv);

/** @var DerSignatureSerializerInterface $serializer */
$serializer = EcSerializer::getSerializer(DerSignatureSerializerInterface::class);
$vchSig = $serializer->serialize($ecSig);

echo $vchSig->getHex() . PHP_EOL;
```
