### ISSUE TITLE
XPUB to SegWit addresses?

### ISSUE THREAD

**Issue by minioff** [Bit-Wasp/bitcoin-php#533]
Hello,

I have put together a function that will generate a bitcoin address given XPUB from Trezor wallet and provided path:
```
function xpub2address($xpub, $position, $change = false){
	$path = $change ? "1/".$position : "0/".$position;
	return BIP32::key_to_address(BIP32::build_key($xpub, $path)[0]);
}
```

This will create the classic address. Is there a way to use bitcoin-php to generate SegWit address that belongs to provided XPUB? If so, can someone point me to the right direction please?

Thank you!

**Comment by afk11** [comment]
Oh, you're using bitcoin-lib-php! That library isn't maintained anymore, but the stuff for segwit addresses is implemented here.

I think this issue demonstrates how to do it: https://github.com/Bit-Wasp/bitcoin-php/issues/527

**Comment by minioff** [comment]
Thank you, will try that.
