### ISSUE TITLE
[Question] How to create new Network for AltCoin

### ISSUE THREAD

**Issue by arttioz** [Bit-Wasp/bitcoin-php#534]
https://github.com/Bit-Wasp/bitcoin-php/blob/2b8220761ef00efae6a80ac7e6938f796dfe4fa8/src/Network/NetworkFactory.php#L199

I would like to generate FeatherCoin, Namecoin, HyperStake, Primecoin and Quark address.
Could you suggest how to create any new type of Network?

**Comment by afk11** [comment]
Just write a function, not static, somewhere in your application that does the same thing as dash. You'll find the bytes for in chainparams.cpp, ADDR_BYTES or something. note, sometimes they're in decimal, you'll have to convert to hex.

**Comment by arttioz** [comment]
From your recommend, Found chainparams.cpp for feathercoin.
https://github.com/FeatherCoin/Feathercoin/blob/master-0.9/src/chainparams.cpp
  
base58Prefixes[PUBKEY_ADDRESS] = std::vector<unsigned char>(1,14); // FeatherCoin addresses start with F
        base58Prefixes[SCRIPT_ADDRESS_OLD] = std::vector<unsigned char>(1,5);
      //  base58Prefixes[SCRIPT_ADDRESS] = list_of(96);
        base58Prefixes[SCRIPT_ADDRESS] = std::vector<unsigned char>(1,5);
        base58Prefixes[SECRET_KEY] =     std::vector<unsigned char>(1,142);// 14+128
        base58Prefixes[EXT_PUBLIC_KEY] = boost::assign::list_of(0x04)(0x88)(0xBC)(0x26).convert_to_container<std::vector<unsigned char> >();
        base58Prefixes[EXT_SECRET_KEY] = boost::assign::list_of(0x04)(0x88)(0xDA)(0xEE).convert_to_container<std::vector<unsigned char> >();
        //base58Prefixes[EXT_SCRIPT_ADDRESS] = list_of(96);

I change to NetworkFactory::create('e', '5', '8e')
14 -> e
5-> 5
142-> 8e
But I still don't know to find HDPubByte,HDPrivByte and NetMagicBytes.
Could you guild me how to find HDPubByte, HDPrivByte and NetMagicBytes?

**Comment by afk11** [comment]
Pad the values `e`, `5` with a `0` to make it a properly formatted hex character.

Fro the network magic bytes, you need the values for: pchMessageStart. You might need to write them in reverse (compare what I have for bitcoin, and bitcoin chainparams.cpp) for that one.

HD bytes - you just pasted them ;) 
```
base58Prefixes[EXT_PUBLIC_KEY] = boost::assign::list_of(0x04)(0x88)(0xBC)(0x26).convert_to_container<std::vector >();
base58Prefixes[EXT_SECRET_KEY] = boost::assign::list_of(0x04)(0x88)(0xDA)(0xEE).convert_to_container<std::vector >();
```

**Comment by afk11** [comment]
Think this issue was resolved, but any questions reopen the issue! :+1:

**Comment by arttioz** [comment]
Now I can Feather coin address from your advice but now I stuck with Zcash address.  

Feather coin  networkfactory example
```
base58Prefixes[PUBKEY_ADDRESS] = std::vector(1,14); // FeatherCoin addresses start with F
base58Prefixes[SCRIPT_ADDRESS_OLD] = std::vector(1,5);
base58Prefixes[SECRET_KEY] = std::vector(1,142);// 14+128
base58Prefixes[EXT_PUBLIC_KEY] = boost::assign::list_of(0x04)(0x88)(0xBC)
base58Prefixes[EXT_SECRET_KEY] = boost::assign::list_of(0x04)(0x88)(0xDA)
```

```
       $this->network = NetworkFactory::create('0e', '05', '8e')
            ->setHDPubByte('0488bc26')
            ->setHDPrivByte('0488daee')
            ->setNetMagicBytes('dbb6c0fb');
        Bitcoin::setNetwork($this->network);

```
For the Zcash is in different format

```
 // guarantees the first 2 characters, when base58 encoded, are "t1"
        base58Prefixes[PUBKEY_ADDRESS]     = {0x1C,0xB8};
        // guarantees the first 2 characters, when base58 encoded, are "t3"
        base58Prefixes[SCRIPT_ADDRESS]     = {0x1C,0xBD};
        // the first character, when base58 encoded, is "5" or "K" or "L" (as in Bitcoin)
        base58Prefixes[SECRET_KEY]         = {0x80};
        // do not rely on these BIP32 prefixes; they are not specified and may change
        base58Prefixes[EXT_PUBLIC_KEY]     = {0x04,0x88,0xB2,0x1E};
        base58Prefixes[EXT_SECRET_KEY]     = {0x04,0x88,0xAD,0xE4};
        // guarantees the first 2 characters, when base58 encoded, are "zc"
        base58Prefixes[ZCPAYMENT_ADDRRESS] = {0x16,0x9A};
        // guarantees the first 2 characters, when base58 encoded, are "SK"
        base58Prefixes[ZCSPENDING_KEY]     = {0xAB,0x36};
```

I try to generate address with the network below here but it doesn't generate a correct address of Zcash.
 
```
 $this->network = NetworkFactory::create('B8', 'BD', '80')
            ->setHDPubByte('0488B21E')
            ->setHDPrivByte('0488ADE4')
            ->setNetMagicBytes('BFF91AFA');
        Bitcoin::setNetwork($this->network);
```
The result is "2H8Yjyycj77hbsrpaUM6MCmqj2TrWqVmFsX"

**Comment by afk11** [comment]
Ok, looking at the base58Prefixes from zcash, it seems they have two bytes! Try this? Multi-byte prefixes should work, but we can add it if not..
```php
$this->network = NetworkFactory::create('1cB8', '1cBD', '80')
```

**Comment by ofumbi** [comment]
Hello Validation fails, this now throws an exception.msg=> p2pkh base58 prefix must be a 1 byte hex string in /Applications/MAMP/htdocs/vendor/bitwasp/bitcoin/src/Network/Network.php on line 59

**Comment by afk11** [comment]
Hi, what version? Things have changed a bit recently.

**Comment by afk11** [comment]
@ofumbi you should make a new issue :)
