### ISSUE TITLE
How to create a bitcoin wallet?

### ISSUE THREAD

**Issue by nick-chiu** [Bit-Wasp/bitcoin-php#539]

**Comment by afk11** [comment]
Not sure how I can help you, are you asking how do design a wallet? This library has a lot of things you might need, but it really depends on what you want to do!

**Comment by afk11** [comment]
Closing this. You need to come up with the design yourself. The rest is implementation details, which _are_ a question for this library. Re-open if you have specific questions about the library, or it's usage.
