### ISSUE TITLE
Generating address for steem

### ISSUE THREAD

**Issue by davidkevork** [Bit-Wasp/bitcoin-php#547]
I can generate the private key using `PrivateKeyFactory::fromHex($hashSha256)->toWif();` for [steem blockchan](https://github.com/steemit/steem-js) but when i try to generate the public address using `$privateKey->getPublicKey()->getAddress()->getAddress()` I only bitcoin address and cant generate a steem address with the address prefix STM

**Comment by afk11** [comment]
You haven't passed in the details for the Steem network yet, and the library uses bitcoin by default.

You'll need to implement a NetworkInterface for Steem. This is pretty easy, look in NetworkFactory for the parts that are required, then check out steems chainparams.cpp to get the correct values (or look in other implementations for the details)

Then, you have two options:
`\BitWasp\Bitcoin\Bitcoin::setNetwork($yourNetwork)` changes the default, so now your steem network would be used globally. 

If you don't like globally configuring the network, pass $yourNetwork as an argument to `toWif` and `getAddress` to override the default.
