### ISSUE TITLE
how can i get hash160 from btc address ? or other way around ?

### ISSUE THREAD

**Issue by rawmaterials** [Bit-Wasp/bitcoin-php#548]
can this be doable using bit wasp library ?

thanks

**Comment by afk11** [comment]
Yep, see this pull request for an example of this: https://github.com/Bit-Wasp/bitcoin-php/pull/549

**Comment by afk11** [comment]
Other way around is:
```php
$p2pkh = new PayToPubKeyHashAddress($hash160);
$p2sh = new ScriptHashAddress($hash160);
```

**Comment by rawmaterials** [comment]
thank you, looking into it.
