### ISSUE TITLE
How to implement this into marketplace?

### ISSUE THREAD

**Issue by scarar** [Bit-Wasp/bitcoin-php#551]
I was wondering how to implement bitcoin and using this to build a marketplace using bitcoin to buy/sell products?

**Comment by afk11** [comment]
Well, good thing you asked! It would be irresponsible to build a bitcoin product without first understanding bitcoin and how to interact with it safely.

My only advise to you is to learn bitcoin -- which you can do easily by picking up a library and achieve some short term goals with it, and then revisit the issue. 

Also, I just code the library, it's up to you to design applications :D

**Comment by afk11** [comment]
Closing this for now, just open another issue if you get stuck with something.
