### ISSUE TITLE
Can't sign transaction

### ISSUE THREAD

**Issue by Xmaksss** [Bit-Wasp/bitcoin-php#554]
First I created the master key.
```php
$master = HierarchicalKeyFactory::generateMasterKey();
$masterKey = $master->toExtendedPrivateKey();
$address = $master->getPublicKey()->getAddress()->getAddress();
```

Then I got several addresses

```php
$master = HierarchicalKeyFactory::fromExtended($xprv);

$hardened = $master->derivePath("0/999999");

$addr1 = $hardened->deriveChild(0);
$newAddr1 = $addr1->getPublicKey()->getAddress()->getAddress();
$addr2 = $hardened->deriveChild(1);
$newAddr2 = $addr2->getPublicKey()->getAddress()->getAddress();
```

Then I sent satoshi to this addresses.
Now I want to create transaction and send to some address but when I signed new transaction I got error _"Signing with the wrong private key"_.
It seems my utxo are not my.
Then I checked pubKeyHash for this addresses and they are different.
What wrong? I did not correctly generate new addresses? Please help me!

**Comment by Xmaksss** [comment]
I was able to sign a transaction. I just used the private keys of the children for signing.
It's correct?

**Comment by afk11** [comment]
Yes, if you derive a child address, you need to use the same child private key to receive it. 

You can give the public version to a server, so it can only derive the address.. and then another server with the private data to sign.

**Comment by Xmaksss** [comment]
Ok, thank you.
