### ISSUE TITLE
GMP warning from TransactionInterface::getBuffer()

### ISSUE THREAD

**Issue by punto-** [Bit-Wasp/bitcoin-php#555]
Hi. I'm getting this warning from GPM when I call $signed->getBuffer();, I get $signed from Signer::get() (after I've done everything to sign the transaction):

PHP Warning:  gmp_init(): Unable to convert variable to GMP - wrong type in vendor/mdanter/ecc/src/Math/GmpMath.php on line 312

The buffer appears to be correct, I get the transaction serialized and it seems to be correct, but I've no idea where this warning comes from. Is there a way to debug this? At least get a backtrace to see exactly what's causing it?

Thanks

**Comment by afk11** [comment]
I hate that warning.. could I see the code? That normally happens when I pass an object somewhere I shouldn't..

**Comment by punto-** [comment]
The function is a bit bigger, but this is the code that makes the transaction. It takes a list of inputs and keys from $txu, and a list of outputs from $outputs, and makes the transaction and signs it. The warning happens at the bottom:

`
$builder = TransactionFactory::build()->version(1);

foreach ($txu as $tx) {

    $builder->input($tx["tx"]["txid"], $tx["tx"]["output_no"]);
};

foreach ($outputs as $addr) {

    $sat = $addr["value"] * $fee_rate;
    $sat = $sat * 100000000;
    $builder->payToAddress($sat, \BitWasp\Bitcoin\Address\AddressFactory::fromString($addr["addr"], $network[$chain]["net_obj"]));
};

$unsigned = $builder->get();

$ec = \BitWasp\Bitcoin\Bitcoin::getEcAdapter();
$signer = new Signer($unsigned, $ec);

$tcount = 0;
foreach ($txu as $tx) {

    $n = $tx["tx"]["value"] * 100000000;
    $outscript = ScriptFactory::scriptPubKey()->payToPubKeyHash($tx["key"]->getPublicKey()->getPubKeyHash());
    $txout = new TransactionOutput($n, $outscript);

    $signer->sign($tcount, $tx["key"]->getPrivateKey(), $txout);
    $tcount += 1;
};

$signed = $signer->get();
$buf = $signed->getBuffer();    # warning happens here
$ret = $buf->getHex();

return $ret;
`

The transaction produced seems to be valid structurally (although I couldn't publish it, the signature seems to be incorrect), here's an example:

`01000000015494bcc74cd67fc3a0cce1350c4a3f93e020715062917fe54cfedba2f760ff25010000006a4730440220167e2f113c755bff256dcb756c459fe3fe4357e1bdb02e72d811e4015588aeb90220501eed54d0652e8deefa991be67380f06146388f63add30c7da0ad33431ce64a0121030964673d6a9a917d453103b1600bddc957e72112eaddd860191df70a72ea0924ffffffff0100000000000000001976a9141bce73db7f2a1afeb8f70a7f0f9817fbd2975d2b88ac00000000`

Thanks

**Comment by punto-** [comment]
(btw it's for the bitcoin testnet network)

**Comment by afk11** [comment]
`var_dump($tx["tx"]["value"] * 100000000);` does this mention `float`? also var dump the satoshis in the feerate part.. don't see anything too alarming otherwise, but haven't gotten into it fully

**Comment by punto-** [comment]
Ok, it looks like casting the value in satoshis to int fixes it, it also
fixes the issue in the raw transaction that was giving a value of 0 to the
output (so all the input went to fees). I guess those were connected.

Thanks!

**Comment by punto-** [comment]
it also fixed the issue with the signature apparently, so I guess that also
confirms issue #550, the transaction works :)

**Comment by afk11** [comment]
Cool, I'll have a look for places to validate for such usage, an exception would be nicer than that totally useless gmp error :P

Thanks for the report!
