### ISSUE TITLE
Clarify xpub... Derivation only for public keys (watch only)

### ISSUE THREAD

**Issue by seby2k** [Bit-Wasp/bitcoin-php#561]
I am trying to create a watchonly wallet compatible with electrum. I cannot use the xpub... To generate m/0/0 for example. I get a curve error. I have tried in all ways (convert to hex and drop the first bytes version bytes, fingerprint, chain data), only use the public key and so on. Nothing worked. 

How should $mpk be serialized? What data is expected fo use public_key_from_mpk?

I want, given an xpub (no xpriv and no seed) to generate on demand address with $index (any index) watch only mode. 

I also would need commercial support and would be interested in bip173 support can i reach someone?

**Comment by seby2k** [comment]
I run electrum.php and get this

MPK: 819519e966729f31e1855eb75133d9e7f0c31abaadd8f184870d62771c62c2e759406ace1dee933095d15e4c719617e252f32dc0465393055f867aee9357cd52
Public Key: 041f0380002320795ae7f89b3fc238beda62c7c6245382b458abddf0ee77863acbce2f3600b3edb1b08c5adc9826d14769e412d7e6ac98d13794ceae6a4429d3c1

What does mpk come from here?

**Comment by afk11** [comment]
It looks like you are using https://github.com/Bit-Wasp/bitcoin-lib-php, not bitcoinf-php. bitcoin-lib-php is unmaintained, so if your project is new, you should jump straight to bitcoin-php. 

Also for bitcoin-lib-php if you're using xpubs then you want to use the BIP32 class not Electrum, which is an older key derivation method. 

I think if you look around the library a bit you'll find what you need, but unfortunately support isn't possible.

**Comment by seby2k** [comment]
Thanks Thomas for the reply and thank you for writing this library. Can you please give me an example how does bip32 class expect the xpub? In what format do i need to convert it to hex or drop some bytes?

**Comment by seby2k** [comment]
I have succeeded to generate subkeys using an existent master public key using bitcoin-php/src/Key/Deterministic.closing this.

**Comment by seby2k** [comment]
I have succeeded to generate subkeys using an existent master public key using bitcoin-php/src/Key/Deterministic.closing this.
