### ISSUE TITLE
Generating BTC addresses from multi-sig xpubs

### ISSUE THREAD

**Issue by viestursr** [Bit-Wasp/bitcoin-php#562]
Hello,

I see there is possibility (and I've used it a lot!) to generate BTC public keys from one extended public key using \BitWasp\Bitcoin\Key\Deterministic\HierarchicalKeyFactory::fromExtended method.

However I've ran into a case where I've created a multi-sig wallet in Electrum, and the xpubs that Electrum provides do not correspond to the addresses of the multi-sig wallet rather than the addresses of each cosigner.

Is there a method to generate multi-sig wallet addresses using this library? Maybe I've overlooked it.

**Comment by afk11** [comment]
Hmm, actually, there is this.. It exposes an interface similar to `HierarchicalKey` for deriving P2SH multisig addresses according to a path https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Key/Deterministic/MultisigHD.php

I haven't used it a lot, but it should work ok. The code is minimal if you want to implement it yourself.

**Comment by seby2k** [comment]
How did you exaclty get a simple raw public key (compressed or uncompressed) from an xpub? Can you plese give me a simple example?

**Comment by afk11** [comment]
BIP32 keys are always compressed, as per the spec :) https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

You should be able to see in the source code for HierarchicalKey that there is a function `getPublicKey`.. Then you can call `getBuffer()` on that, to get it serialized as a Buffer.. then call `getHex` or whatever. 

I think this library is pretty easy to follow, the odds are if you're not sure how to do something, there's a function on the class to do it :)

**Comment by seby2k** [comment]
Thanks. The problem is something is not working or i am not doing right. I only have the extended public key not the private one also. It is from electrum xpub...

I get a fatal error when i try to generate a subkey fromextended. I know you are very very busy but please could you write a php example file that will:
1. Take an electrum xpub or any xpub (or zpub since serialization changed for native segwit)
2. Use derivation path m/0/<address index>
3. Print the compressed key with the arbitrary index (1,5,100,etc)

**Comment by seby2k** [comment]
If i see this example i will understand and be able to change paths, etc. I see a derivation of m/0/999999 in the library and i am not sure what this is for.  please if you could help, beers are on me.

**Comment by seby2k** [comment]
Let me explain again. I have the master public key (xpub..). I want to generate its child keys from index 0 to unlimited. The derivation path i intend to use is m/0/index where index can be from 0 to unlimited and m is the root. This is electrum's path.
