### ISSUE TITLE
Integrity check on a master public key

### ISSUE THREAD

**Issue by seby2k** [Bit-Wasp/bitcoin-php#563]
I looked in tests and saw test code for some values but i did not find an integrity check for xpub master public keys (bip32). I would like to check for integrity and validate an xpub... String when it is submitted by user, before saving it to db and processing it. Where can i find that?

**Comment by afk11** [comment]
A checksum is computed and verified as part of the base58check encoding, so `HierarchicalKeyFactory::fromExtended` is the safest way to create extended keys.

https://github.com/Bit-Wasp/bitcoin-php/blob/8a13d9f387c97988c9abcdc573cf320cb17b421a/src/Key/Deterministic/HierarchicalKeyFactory.php#L57-L60
https://github.com/Bit-Wasp/bitcoin-php/blob/8a13d9f387c97988c9abcdc573cf320cb17b421a/src/Serializer/Key/HierarchicalKey/Base58ExtendedKeySerializer.php#L39-L41
https://github.com/Bit-Wasp/bitcoin-php/blob/8a13d9f387c97988c9abcdc573cf320cb17b421a/src/Base58.php#L112-L114

**Comment by afk11** [comment]
Think this has been resolved, but reopen if you need!
