### ISSUE TITLE
Time 

### ISSUE THREAD

**Issue by ashish-outlaw** [Bit-Wasp/bitcoin-php#568]
How much time to you need to make a full project

**Comment by Gwinest** [comment]
I took 8 months until I finished a strategy game on Bitcoin transactions. 5
programmers involved.

Em Seg, 27 de nov de 2017 00:54, ashish-outlaw <notifications@github.com>
escreveu:

**Comment by afk11** [comment]
Hard to answer this without the scope, but I feel the issue isn't relevant for this repository in the first place.
