### ISSUE TITLE
Decompress public key

### ISSUE THREAD

**Issue by seby2k** [Bit-Wasp/bitcoin-php#572]
I know as per BIP32 standards the public keys must always be compressed, but i am looking into a separate task that needs the uncompressed version of a compressed public key. 

What is the easiest way to subit in this library a compressed public key (raw public key, not xpub/extended) and get the uncompressed version of the very same public key?
Thanks.

**Comment by afk11** [comment]
Hmm, there's no clean way to do it at the moment, ideally both implementations of PublicKey / PrivateKey would have an `asCompressed()` and `asUncompressed()` function for that.. 

Otherwise, you could just construct your own public key like this (assuming you're using PHPECC and haven't installed secp256k1). https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Crypto/EcAdapter/Impl/PhpEcc/Key/PublicKey.php#L42

```php
use \BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PublicKey;

function decompressKey(PublicKeyInterface $pubkey1) {
    if ($pubkey1->isCompressed()) {
        return $pubkey1;
    }
    return new PublicKey(
        $ecAdapter,
        $pubkey1->getPoint(),
        $newCompressed,
        $pubkey1->getPrefix()
    );
}
```

**Comment by seby2k** [comment]
Thanks. But when i pass the compressed pubkey to decompress i get this:

PHP Catchable fatal error:  Argument 1 passed to decompressKey() must be an instance of PublicKeyInterface, string given, called in ...

**Comment by afk11** [comment]
Ah, sorry. You can decode the public key with this `PublicKeyFactory::fromHex()`, and afterwards you can call `$pubkey->getHex()` - it's a habit of mine to use the instances, there reaches a point if using string parameters that you're decoding 10 times during a code path - extracting a function that works on instances makes all that go away :P

FYI pretty much every object has a serializer class and fromHex function - somewhere, maybe in a related Factory class), and most of the interfaces include getBuffer / getHex / getBinary to encode it as a string.

**Comment by seby2k** [comment]
Now the fatal error is fixed, but it doesn't produce the correct uncompressed key. It produces a hex string which starts with 02 instead of 04, as the correct uncompressed public key should look like. Here is the code, can you please tell me what is wrong that it prints the uncompressed public key with 02... prefix instead of 04.. ?

`$z= 'compressed-key-hex-format';
$key = PublicKeyFactory::fromHex($z);

function decompressKey($key) {

    $ecAdapter = Bitcoin::getEcAdapter();
    
    return new PublicKey(
        $ecAdapter,
        $key->getPoint(),
        false,
        $key->getPrefix()
    );
    
}

$t = decompressKey($key);

echo $z. "\n";
echo $t->getHex() . "\n";`

**Comment by afk11** [comment]
Oh, yea you're right that when decompressing prefix should be '04'

**Comment by seby2k** [comment]
Thank you very much for this. It works.
