### ISSUE TITLE
decode transaction in hex to human-understandable format

### ISSUE THREAD

**Issue by seby2k** [Bit-Wasp/bitcoin-php#575]
Is it possible given this library, to submit the hex of a transaction, and to get information like:
- is it final and complete and can be broadcasted? (all signatures, locktime etc) or does it need another signature?
- decode it to human understandable format, like getting from a hex string:
input_a(address)
input_b(address)  ---> output(s)
input_c(address)
....

**Comment by afk11** [comment]
First question - yea you kinda can tell it's complete when you have all of the scriptPubKeys for the inputs you are spending. There is `isFullySigned` on the InputSigner, you'll find a lot of useful info in that class. It needs everything that sign does, but without the private keys. 

Locktime, the library doesn't know what state the blockchain is in, so you have to write that yourself. CLTV/CSV are supported in any case.

You'll find a bunch of signing/verifying examples in the folder.

Second question - just dump the contents of version/locktime, the txins and txouts..

**Comment by seby2k** [comment]
Thank you. And i guess this is independent if the addresses used are bench32 because that is just a different encoding of the same data, am I right?

**Comment by afk11** [comment]
What exactly are you asking? If the address type matters for checking completeness? It shouldn't - they're only for humans to pass around. The txout.script defines requirements for spending the coin, and generally there are more interesting scripts than address types anyway. 

Bech32 addresses do indicate segwit, which has scripts similar to the existing P2PKH + P2SH addresses. You can read more about both here:
Segwit: https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki
Bech32: https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

**Comment by afk11** [comment]
Btw, here's an example of checking an txin's signature if it helps: https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/tx.spend.p2sh.p2wpkh.php#L46
