### ISSUE TITLE
Trezor/Ledger m/49'/0'/0' derivation path

### ISSUE THREAD

**Issue by romanornr** [Bit-Wasp/bitcoin-php#582]
I am trying to generate public keys that can be used with a hardware wallet like Ledger/Trezor
by using the xpub.

````
$hk = HierarchicalKeyFactory::fromExtended($this->xpub, $this->network);
$master = $hk->derivePath("m/49'/0'/3'");
$address = $master->getPublicKey();

$orderAddress = $address->getAddress()->getAddress($this->network);
return dd($orderAddress);````

but I get this error.

````
Can't derive a hardened key without the private key
````

/vendor/bitwasp/bitcoin/src/Key/Deterministic/HierarchicalKey.php
````
        if (($sequence >> 31) === 1) {
            if ($this->isPrivate() === false) {
                throw new \Exception("Can't derive a hardened key without the private key");
            }
````
Not sure if I am doing something wrong here.

**Comment by afk11** [comment]
This example was added which should demonstrate deriving trezor 44/49 paths: https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/trezor.bip32.php
