### ISSUE TITLE
BIP44 Wallet Implementation

### ISSUE THREAD

**Issue by eltriplet** [Bit-Wasp/bitcoin-php#595]
I am using the wallet implementation of this nice library to generate BTC addresses, but I would like to extend it to BIP44 in order to generate addresses belonging to other cryptocurrencies. Does anyone here have an idea of the effort that this would take? If it is simple I would be willing to help even though my PHP skills are rather limited.

BIP32 (What is currently Implemented): https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

BIP44 (What I'd like to implement): https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

Thanks in advance!

**Comment by afk11** [comment]
Might help you get started? https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/trezor.bip32.php Obviously some of the parameters in that example are hardcoded and only suitable for bitcoin.. but if you're just looking for an example script, tweaking that example should be enough to derive a an account xpub from the seed, and then the addresses derived for an account.

**Comment by eltriplet** [comment]
Thanks! Are you familiar with bip32 implementation? I haven't yet figured out which is the part that is kept constant in bip32 but is changed in bip43 / bip44, do you happen to know?

**Comment by afk11** [comment]
I'm not sure what constant part you mean - BIP32 is the hierarchical key derivation algorithm, BIP43/44 describe how to derive paths (like M/0'/1/1/1) that suit multiple networks, or that namespace public keys into distinct groups by changing a parameter like coinType, change, etc. 

Both the proposals use BIP32, but they describe different ways of generating addresses from a seed (different paths)

**Comment by eltriplet** [comment]
Ok, thanks for the help! I close this and will get back if needed, thanks again!
