### ISSUE TITLE
cashAddr support for bitcoin-cash

### ISSUE THREAD

**Issue by goodProjects** [Bit-Wasp/bitcoin-php#608]
Hi, can you guys support cashAddr for bitcoin cash addresses? 

Maybe we can make BitcoinCash Network with support for cashAddr since all new bitcoin cash versions support cashAddr.

**Comment by afk11** [comment]
I think I'll make a separate package so there isn't a maintenance burden on this organization for bitcoin cash features. We added the signing support, though as mentioned here https://github.com/Bit-Wasp/bitcoin-php/pull/593 the preference is to remove it eventually.
