### ISSUE TITLE
Segwit?

### ISSUE THREAD

**Issue by punto-** [Bit-Wasp/bitcoin-php#613]
Hi.

Is segwit supported? Are there any examples on how to use it? Right now my system receives payments in p2pkh addresses which I generate with the HD wallet API, and later transfers those payments to another address (can be p2sh or p2pkh). As far as I understand, I need to generate a different type of address (that looks like a p2sh), and I also need to generate the transaction with a different script to sign it? The Transactions page in the docs mentions "Witness" in the signing examples, but they all seem to be multisign scripts? Is it possible to create a single-sign segwit address? Also, will it work for litecoin?

Thanks!

**Comment by afk11** [comment]
Yea it is! P2SH|P2WPKH is normally what people use there. You could optionally, also derive P2WPKH addresses which would be even cheaper again, if your users wallets support it! I think there's an example for both.

For signing, the process is identical to P2SH, just set the redeemScript to your witness program (P2WPKH) and it will work. 

Litecoin, it'll work too!

**Comment by punto-** [comment]
Thanks for the reply. Where can I find the example to derive a segwit
address from hte HD wallet? right now I'm doing something like this:

$hkey = HierarchicalKeyFactory::fromExtended($xpub);
$ckey = $hkey->derivePath($path);

$pub_key = $ckey->getPublicKey();

then I give "$pub_key->getAddress()->getAddress()" to the user, that's
where they pay. I have to do something to that key to make it a segwit
address? is the " P2WPKH" a "bech32" address? I think I need the
"P2SH|P2WPKH" because it'll be more compatible with current wallets?

Thanks!

**Comment by afk11** [comment]
Yea I've started removing `getAddress` in later versions because it poses questions like which type, and which should be the default..

P2PKH: 
`new PayToPubKeyHashAddress($pub_key->getPubKeyHash())`
Bech32 (P2WPKH):
`new SegwitAddress(WitnessProgram::V0($pub_key->getPubKeyHash()));`
P2SH P2WPKH:
`new ScriptHashAddress(WitnessProgram::V0($pub_key->getPubKeyHash())->getScript()->getScriptHash())`

**Comment by punto-** [comment]
Thanks, I was able to create the P2SH P2WPKH address, but now when I try to spend an output using it, I get the error " Witness script not provided in sign data or witness". I'm creating the script like this:

```
$prg = WitnessProgram::V0($key->getPublicKey()->getPubKeyHash())->getScript()->getWitnessScriptHash();
$outscript = ScriptFactory::scriptPubKey()->p2wsh($prg);
$txout = new TransactionOutput($value, $outscript);
$signer->sign($tcount, $key->getPrivateKey(), $txout);
```

Am I missing something? Before when I was using a p2pkh address I would simply use payToPubKeyHash() to create the script

Thanks!

**Comment by afk11** [comment]
ok two quick things, first of all that uses P2WSH not P2SH, so the InputSigner is looking for a witnessScript which isn't what you want in this case :) You want a redeemScript that is the v0 witness program. 

```php
$prog = WitnessProgram::V0($key->getPublicKey()->getPubKeyHash());
$p2shScript = ScriptFactory::scriptPubKey()->p2sh($prog->getScript()->getScriptHash());
$txOut = new TransactionOutput($value, $p2shScript);
```

I often will make use of the P2shScript / WitnessScript classes, which decorate a script with methods for producing the scriptPubKey, etc:

```php
$prog = WitnessProgram::V0($key->getPublicKey()->getPubKeyHash());
$redeemScript = new P2shScript($prog->getScript());
$p2shScript = $redeemScript->getOutputScript();
$txOut = new TransactionOutput($value, $p2shScript);
```

second, whenever you use P2SH or P2WSH, and the transaction will be unsigned when you attempt to sign, you need to tell the signer what the redeem/witness script(s) is/(are!)

```php
// for a P2SH output
$signData = new SignData();
$signData->p2sh($redeemScript);

// for a P2WSH output
$signData = new SignData();
$signData->p2wsh($witnessScript);

// for a P2SH P2WSH output
$signData = new SignData();
$signData->p2sh($redeemScript);
$signData->p2wsh($witnessScript);
```

```
$signer->sign($tcount, $key->getPrivateKey(), $txout, $signData);
```

**Comment by afk11** [comment]
Closing this for now, reopen if you have further questions!

**Comment by code2expert** [comment]
I just created a new native segwit UXTO wallet and sent some bitcoins to it. However, I have the following questions:

1.) How can I get the transaction ID or transaction hash from this wallet? 

2.) Also, given a wallet address, and a private key. What methods exist in bitwasp to extract all the details that I need to create, sign, and broadcast a native segwit transaction?

For example, I am trying to send bitcoin from a new native segwit wallet bc1q9pjjydvzyqd8n83znsv6zhh56lk8yztj3m7cjn to 3LGo48mR6vBK2ieBA7SHdCRBmK8JXFBAEt and send the change to bc1qlt95gkn9ufe6z36mgme8nfkjhjavlp79ynjrdz.

I keep getting errors related to wrong transaction hash/ID:

my transaction hash is 010000000001012e1d32ebc3fa508fc740c6b589b32787e7c16132093e49008386ab59118c76f00000000000ffffffff0290b000000000000017a914cbd5aa097c47f7032010616249125b9c79a9c619874623000000000000160014facb445a65e273a1475b46f279a6d2bcbacf87c50248304502210086eff1057d054947beb736553d75a22b6948a67047d9c0458cccb96649c23e7d02203152fcd9ff4439ec8d7a475f018e2769b847299c41efd492af254dc803b7653101210353825959e0f36eff9a1257fa07ad919406a9bba4d100c6df601bc44c63d0ab1100000000

Below is my code:

    $privKeyFactory = new PrivateKeyFactory();
    $privateKey = $privKeyFactory->fromWif("XXXXXXXXXXXXXXXXXXXX");

    $satoshi = 100000000; //one bitcoin in satoshi ie 100 million
    $send_wallet_amount = 0.0005425 * $satoshi;
    $send = 0.0004520 * $satoshi; // satoshis
    $fee = 0.0000002 * $satoshi; // satoshis
    //calculate change
    $change = $send_wallet_amount - $send - $fee;
    
    $addressCreator = new AddressCreator();
    $sendToAddress = $addressCreator->fromString('3LGo48mR6vBK2ieBA7SHdCRBmK8JXFBAEt');
    $changeAddress = $addressCreator->fromString('bc1qlt95gkn9ufe6z36mgme8nfkjhjavlp79ynjrdz');

    $outpoint = new OutPoint(Buffer::hex('f0768c1159ab868300493e093261c1e78727b389b5c640c78f50fac3eb321d2e',32), 0);

    $redeemScript = ScriptFactory::scriptPubKey()->p2wkh($privateKey->getPubKeyHash());

    $txOut = new TransactionOutput(54250, $redeemScript);

    $tx = (new TxBuilder())
        ->spendOutPoint($outpoint)
        ->payToAddress($send, $sendToAddress)
        ->payToAddress($change, $changeAddress)
        ->get();

    $signer = new Signer($tx);
    $input = $signer->input(0, $txOut);
    $input->sign($privateKey);
    $signed = $signer->get();
