### ISSUE TITLE
decoderawtransaction

### ISSUE THREAD

**Issue by goodProjects** [Bit-Wasp/bitcoin-php#614]
is it possible to decode raw transaction to bitcoind-like array readable format?

**Comment by afk11** [comment]
Yea, it would be pretty easy too. Check the Transaction class, you'll find the `getInputs` & `getOutputs`methods.. Once you have the TransactionInput / TransactionOutput, you'll need to look at the OutPoint & Script classes. Most of the objects either contain `Buffer`, which exposes `getHex`. Some (such as Script) need to be serialized _as_ hex, and expose `getHex` too

This demonstrates it for a transaction input, look up what to do for outputs, then write a loop, and you're good to go! 

```php
try {
  $asm = $txin->getScript()->getScriptParser()->getHumanReadable();
} catch (\Exception $e) {
  $asm = "invalid"; // whatever bitcoind is supposed to say here, I'm not sure what it is
}

$input = [
  "txid" => $txin->getOutPoint()->getTxId()->getHex(),
  "vout" => $txin->getOutPoint()->getVout(),
  "scriptSig" => [
    "hex" => $txin->getScript()->getHex(),
    "asm" => $asm,
  ],
  "sequence" => $txin->getSequence(),
];
```

**Comment by afk11** [comment]
It would probably be a cool package to have on packagist, to expose a minimal rawtransaction api that does what bitcoind does. It would have to mimic it fairly well (throw the correct error codes if an error happened). I think I first began writing bitcoin libraries because it would be faster than constantly hitting bitcoind. 

but it's possible to write unit tests against a regtest bitcoind on travis that would verify the library and bitcoind use the same representation for everything, and there aren't that many methods to the raw transaction API...

**Comment by goodProjects** [comment]
I have made this function to decode raw transaction, maybe it's helpful for others.
```

   public function decoderaw($raw ){

        $tx = TransactionFactory::fromHex($raw);

         $result['txid'] = $tx->getTxId()->getHex();
        foreach ($tx->getOutputs() as $key=>$output) {
            try{
                $result['outputs'][$key]['address'] = AddressFactory::fromOutputScript($output->getScript())->getAddress();

            }catch (\Exception $e){
                $result['outputs'][$key]['address'] = 'Newly Generated Coins';
            }
             $result['outputs'][$key]['value'] = $output->getValue() / 100000000;
        }
        foreach ($tx->getInputs() as $key=>$input) {


            $result['inputs'][$key]['txid'] = ($input->getOutPoint()->getTxId()->getHex());
            $result['inputs'][$key]['vout'] = $input->getOutPoint()->getVout();
            $result['inputs'][$key]['address'] = AddressFactory::fromScript($input->getScript())->getAddress();
           // $result['inputs'][$key]['value'] = get
        }

        $result['value'] = $tx->getValueOut() / 100000000; // SAT TO BTC


     return $result;

    } 
```
