### ISSUE TITLE
Why each exception has a separate file? 

### ISSUE THREAD

**Issue by goodProjects** [Bit-Wasp/bitcoin-php#626]
I may be curious but for performance, an extra space may be unwanted. do we really need each exception in a separate file?

**Comment by afk11** [comment]
Oops, did mean to respond to this.. but it just sort of build out that way - there was never enough layering for there to be high level vs low level exceptions, but indeed there's quite a lot! Any suggestions on ways to improve this for developers without many `catch ()` lines would be appreciated!
