### ISSUE TITLE
Transfer Blocks

### ISSUE THREAD

**Issue by ghost** [Bit-Wasp/bitcoin-php#627]
Your wallet passes the blocks to purses that are written in C ++
Or can he only take blocks?
https://bitcoin.org/bin/bitcoin-core-0.15.1/

**Comment by afk11** [comment]
Sorry, I'm not sure what you're asking?

**Comment by DATSEC** [comment]
Synchronization and transmission of blocks

**Comment by afk11** [comment]
Ah, ok. There are endless ways to learn this stuff, but I can't possibly maintain them all here. Use bitcoind / an API / connect to the p2p network, etc. Everyone would implement this differently, and the same for the database layer, so I don't consider these problems part of the scope of this library.

**Comment by afk11** [comment]
There are these related projects github.com/bit-wasp/bitcoin-p2p-php (bitcoin protocol) and github.com/bit-wasp/node-php (bitcoin node), but they both get much less love than this main library! More review and coders are always welcome :)
