### ISSUE TITLE
Push Symfony 4 to Packagist

### ISSUE THREAD

**Issue by faustbrian** [Bit-Wasp/bitcoin-php#628]
The releases on https://packagist.org/packages/bitwasp/bitcoin are all still on Symfony 2.7 and 3.0 even though the composer.json in this repository has Symfony 4.

Could this change be pushed so that this project can be installed in Symfony 4 projects?

**Comment by afk11** [comment]
Ah, oops! Released as v0.0.34.3

**Comment by faustbrian** [comment]
Thanks!

**Comment by faustbrian** [comment]
@afk11 Looks like the packagist webhook might not be configured https://packagist.org/packages/bitwasp/bitcoin

**Comment by afk11** [comment]
That is unusual, weird. Checking now, but without internet soon..

**Comment by afk11** [comment]
Will investigate later, but updated manually for now

**Comment by faustbrian** [comment]
Thanks, now it's available.
