### ISSUE TITLE
Install without composer.

### ISSUE THREAD

**Issue by bchtrue** [Bit-Wasp/bitcoin-php#638]
Hello, 

Maybe somebody can help me, please? I do not have root access at server and want to use some functions from `BitWasp/bitcoin-php` (or bitcoin-lib-php?) to generate addresses from `xpub`. How to install BitWasp without composer? Of course, I can clone the repo and how can I then run `bip32.php` from examples without any issues?

 7th line have `require __DIR__ . "/../vendor/autoload.php";` but it's from composer. What need to use instead of this? Thanks!

Update: Seems it's possible to download composer and run without root. If will try :) Sorry for this ticket. Hope manual download of composer will help.

**Comment by afk11** [comment]
Yea you can install it into the project folder with only PHP!

Nice to see see you got it fixed!
