### ISSUE TITLE
litecoin segwit prefix

### ISSUE THREAD

**Issue by goodProjects** [Bit-Wasp/bitcoin-php#641]
Hi, I'm trying to implement Segwit with litecoin

```
   $p2wpkh = new ScriptHashAddress(WitnessProgram::V0($masterkey->derivePath("m/0/1")->getPublicKey()->getPubKeyHash())->getScript()->getScriptHash());
        
            $new_address = $p2wpkh->getAddress();
```
Response : 2Mt3WdMBvujypE8urmzGYnkXhw67MG22UrA

Now after importing this address to litecoin-core , sending some litecoin to that address and calling listtransaction I see transactions with the same amount to address start with Q

example: Qd1w2zEb3BBqCasjeZTe8N2EcdYmfzMih2

is that an expected behavior? I think we should add Segwit prefix to litecoin network

**Comment by goodProjects** [comment]
Take a look at this discussion here: https://github.com/litecoin-project/litecoin/issues/312

**Comment by afk11** [comment]
Sure, yep you're right. That's the P2SH prefix, I actually have a PR to fix that somewhere, maybe I'll get that merged for 0.0.35.

**Comment by goodProjects** [comment]
Thank you, hope you merge it soon.

**Comment by afk11** [comment]
tagged in 0.0.34.4, and 0.0.35!

**Comment by AdamSEY** [comment]
Hi again, Sorry but I'm still getting the old P2SH format
`2Mt3WdMBvujypE8urmzGYnkXhw67MG22UrA` 

Here's my code: 

```
       $masterKey = HierarchicalKeyFactory::fromExtended($publicKey);
        $addressPath = $masterKey->derivePath("m/$changeAddress/" . $newIndex);
      $p2pkh = new PayToPubKeyHashAddress($addressPath->getPublicKey()->getPubKeyHash());
            $redeemScript = new P2shScript($p2pkh->getScriptPubKey());
            echo $redeemScript->getAddress()->getAddress();

            $p2wpkh = new ScriptHashAddress(WitnessProgram::V0($addressPath->getPublicKey()->getPubKeyHash())->getScript()->getScriptHash());
            echo  $p2wpkh->getAddress();

```

Both are returning address starts with '2'.

**Comment by afk11** [comment]
Create a copy of the litecoin network, then pass it into $pwspkh->getAddress()

` $network = NetworkFactory::litecoin()`
`            echo  $p2wpkh->getAddress($network);`

**Comment by AdamSEY** [comment]
Sorry I forgot to attach this code: 
```
  Bitcoin::setNetwork(NetworkFactory::litecoinTestnet());
```

I'm already setting the network globally. still getting the same result: Address starts with '2' instead of 'q'
