### ISSUE TITLE
Bitcoin Cash Network

### ISSUE THREAD

**Issue by goodProjects** [Bit-Wasp/bitcoin-php#644]
Since Bitcoin cash and Bitcoin now has too many changes like bech32 for Bitcoin and CashAddr for Bitcoin Cash should we make a separate network for Bitcoin Cash?

**Comment by afk11** [comment]
I had some initial stuff in the library, but for BCH I had hoped to have a bridge package set up for it by 0.0.35 (still not tagged). Still have some stuff to implement to make that happen.

BCH networks would be defined in the bridge, along with instances for P2PKH / P2SH cash addresses (I gotta port this from code written in blocktrails sdk), then the CheckerCreator (required for signing transactions)

New BCH features can go into the bridge, or we'll accept PR's here for abstractions enabling this if necessary.

**Comment by afk11** [comment]
Closing this as support has been moved to here: https://github.com/btccom/bitwasp-bitcoin-bch-addon queries about features etc should be directed to that repo!
