### ISSUE TITLE
Address Factory Alternatives

### ISSUE THREAD

**Issue by goodProjects** [Bit-Wasp/bitcoin-php#645]
What to use instead of addressFactory class with 0.35 version? 

`   if ( AddressFactory::isValidAddress($address)) return $address; else return false;`

`   $address= AddressFactory::fromOutputScript($output->getScript())->getAddress();`

**Comment by afk11** [comment]
AddressFactory was mostly moved to AddressCreator (ie, fromOutputScript and fromString). I didn't move `isValidAddress` because the address can just be decoded to learn if it's valid. 

```php
$addressCreator = new AddressCreator();
$validAddress = null;
try {
    $validAddress = $addressCreator->fromString($address);
} catch (\Exception $e) {
}
```
