### ISSUE TITLE
PHP 7.2 Support

### ISSUE THREAD

**Issue by deweller** [Bit-Wasp/bitcoin-php#661]
`mdanter/ecc:^0.4` does not support PHP 7.2.

Can you update the version requirement to `mdanter/ecc:^0.5`?

**Comment by deweller** [comment]
Oh wait.  I see that master is already tagged this way.  :)

Is a release tag imminent?  Thanks.

**Comment by afk11** [comment]
A little bit hard to forecast, I realized I had to make an earlier release first.. Once that's done the focus is back on when we can get proceed with the 7.0+ only release.

**Comment by afk11** [comment]
v1.0.0 was tagged with 7.0+ support, so going to close this one
