### ISSUE TITLE
getting Address output script

### ISSUE THREAD

**Issue by goodProjects** [Bit-Wasp/bitcoin-php#676]
I've been using `electrumx` servers to getting addresses info, but with newer versions of `electrumx` we should use scripts instead of typical base58 addresses. 

is that possible to get address output script and then do SHA265? 

Please take a look on the this comment [here.](https://github.com/kyuupichan/electrumx/issues/390#issuecomment-370056339) 

That what I did try: 
```
        Bitcoin::setNetwork(NetworkFactory::bitcoin());
        $address = new AddressCreator();
        $address->fromString('1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa');
        echo "Base58 Hash160: " . $address->getHash()->getHex().PHP_EOL;
        
```

**Comment by afk11** [comment]
$addr = $addressCreator->fromString('1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa');
$script = $address->toOutputScript(); // a script

For hashing, you'll need $script->getBuffer(), then check out this class!
https://github.com/Bit-Wasp/bitcoin-php/blob/2e902077810a74cd6295847f2450eaf3e81e7dd0/src/Crypto/Hash.php#L27

**Comment by goodProjects** [comment]
Thank you mate, can we reverse byte as well?

**Comment by afk11** [comment]
Yep! Same as how the txid is calculated, buffers can be flipped!

**Comment by goodProjects** [comment]
Thanks @afk11 for sharing that and for this huge library. 

I'm just getting `Call to undefined method BitWasp\Bitcoin\Address\AddressCreator::getScriptPubKey()`

**Comment by afk11** [comment]
Ah, sorry the AddressCreator class isn't mutable, it returns the address from fromString:

```
-    $address->fromString('1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa');
+   $address = $address->fromString('1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa');
```
