### ISSUE TITLE
Bitcoin Address Validator

### ISSUE THREAD

**Issue by addressleakt** [Bit-Wasp/bitcoin-php#678]
Hello,

Is there a function in this project to validate a bitcoin address in php that also works with bech32 addresses?

isValid('1AGNa15ZQXAZUgFiqJ2i7Z2DPU2J6hW62i');

And it would return true because it is valid?

**Comment by afk11** [comment]
If you're on 0.0.34, yes, there is `BitWasp\Bitcoin\Address\AddressFactory::isValidAddress`, but that was removed in 0.0.35, instead it's better to just decode and see if it worked.

0.0.35:
```php
$addressCreator = new AddressCreator();
try {
    $addressCreator->fromString('');
    return true;
} catch (\Exception $e) {
    return false;
}
```
