### ISSUE TITLE
Converting LTC address

### ISSUE THREAD

**Issue by minioff** [Bit-Wasp/bitcoin-php#681]
Hi,

what would be a good way to convert Litecoin addresses starting with '3' to the newer format starting with 'M', if any?

Thanks for any pointers.

This is what I currently use to generate LTC addresses starting with '3';

```
...
$path = $change ? "1/".$position : "0/".$position;
$pubkey = $master->derivePath($path);
$wp = WitnessProgram::v0($pubkey->getPublicKey()->getPubKeyHash());
return AddressFactory::fromScript($wp->getScript())->getAddress();
````

**Comment by afk11** [comment]
Hi, yea I've been wondering about the best thing for that.. Maybe a generic base58 decoder, which swaps out the prefix byte and reencodes in base58 check format. (can be bidirectional, or at least repurposed for different prefixes)

Btw, if you upgrade, I've added the M prefix by default now going forward (had to be done someday), which maybe fixes part of your problem. What cases are you thinking of btw?

As for accepting user input whether the address might begin with 3, we probably want a converter. I'd be tempted to create an `address-utils` package, so it doesn't clutter the main library.

**Comment by minioff** [comment]
Hi,

`address-utils` sounds like a good way to go.

I have upgraded to latest version and that in fact did solve my problem.

Thank you.

**Comment by afk11** [comment]
Awesome!
