### ISSUE TITLE
Release tag request

### ISSUE THREAD

**Issue by AdvancedStyle** [Bit-Wasp/bitcoin-php#689]
Please can you release a new tag (ie 0.36) which is compatible both the new Zcash updates, and the BCH address addon.

Currently https://github.com/btccom/cashaddress-php/ and https://github.com/btccom/bitwasp-bitcoin-bch-addon are not compatible with bitwasp dev-master branch.

**Comment by afk11** [comment]
Hey! They should be compatible with the 0.0.35 branch, but of course if you've been using master, you won't be able to roll back easily.

Haven't had a lot of free time recently, but will try get together a plan for making this release.

**Comment by AdvancedStyle** [comment]
I'm using master because 0.35 doesn't have the Zcash compatibility.
