### ISSUE TITLE
need vendor full 

### ISSUE THREAD

**Issue by alphasquare123456** [Bit-Wasp/bitcoin-php#695]
dear sir ,
we need vendor folder,because we cant download file through composer from mac

**Comment by afk11** [comment]
Composer is the only way we can recommend you install the library, as it takes care of installing the right dependencies for your environment. You should probably find out why it's not working.

**Comment by alphasquare123456** [comment]
[InvalidArgumentException]                                                                                                                                  
  Could not find a matching version of package /Users/mac/bitcoin-php-master/composer.json. Check the package spelling, your version constraint and that th  
  e package is available in a stability which matches your minimum-stability (stable).

**Comment by afk11** [comment]
what's your composer.json look like? the error looks weird, have you put the filesystem path instead of a package somewhere? Composer downloads the versions specified, so you don't need to link to a local version or anything!

**Comment by afk11** [comment]
Closing, you should use composer.
