### ISSUE TITLE
How use multisig to create a transaction and sign it

### ISSUE THREAD

**Issue by cevin** [Bit-Wasp/bitcoin-php#696]
version: 0.0.35.0

my code, likes wrong.
```php
function createTransaction(Array $inputs,Array $outputs,Array $private_key,$script) {
            // Initialize transaction creator
            $transaction = TransactionFactory::build();

            // Initialize address creator
            $addressCreator = new \BitWasp\Bitcoin\Address\AddressCreator();

            // Initialize script
            $script = ScriptFactory::fromHex($script);

            foreach ($inputs as $input) {
                $transaction->input($input['txid'],$input['vout']);
            }

            foreach ($outputs as $address=>$amount)
                $transaction->payToAddress($amount,$addressCreator->fromString($address));

            // Make transaction
            $transaction = $transaction->get();


            // Sign transaction
            $signer = new \BitWasp\Bitcoin\Transaction\Factory\Signer($transaction);
            $signd = new \BitWasp\Bitcoin\Transaction\Factory\SignData();
            $signd->p2sh($script);

            foreach ($transaction->getOutputs() as $index=>$output)
                foreach ($private_key as $pkey) {
                    $pk = PrivateKeyFactory::fromWif($pkey);
                    $signer->input($index,$output,$signd)->sign($pk);
                }

            // Signing and get output
            $hex = $signer -> get() -> getHex();

            return $hex;
}

create( [ ['txid'=>'000000000','vout'=>0] ] , ['address'=>10,'address2'=>10], ['pkey1','pkey2'], 'multisign wallet script hex code' )

// multisig
// $script = ScriptFactory::scriptPubKey()->multisig(2,[pubkey1,pubkey2,pubkey3],true)->getHex();
```

**Comment by afk11** [comment]
Hey, you were pretty close! 

You also need to pass the 'UTXO's of the outputs you are trying to spend. If you look at the way you are calling signer->input->sign(), you should spot a logical error - you are looping over outputs which are the destination, not the source.

Also, in bitcoin, when you receive funds on an address technically someone has created an 'output' structure _paying you_. If you wish to sign something, you need to give the signer that script (for your address) so it can correctly sign the transaction. 

```php
            foreach ($transaction->getInputs() as $index=>$input)
                foreach ($private_key as $pkey) {
                    $pk = PrivateKeyFactory::fromWif($pkey);
                    $signer->input($index,$arrayOfPrevOuts[$index],$signd)->sign($pk);
                }
```

**Comment by cevin** [comment]
@afk11  How to get the output structure? If I have 2 inputs and 1 output, how do I confirm the structure of the output?

so if multisig wallet address is 1FAoam1xaWqVLVfd3BuY8rJJroz4U9dSWD 
the unspent transaction is 
https://api.blockcypher.com/v1/btc/main/addrs/1FAoam1xaWqVLVfd3BuY8rJJroz4U9dSWD?unspentOnly=true

```json
{
  "address": "1FAoam1xaWqVLVfd3BuY8rJJroz4U9dSWD",
  "total_received": 100000000,
  "total_sent": 0,
  "balance": 100000000,
  "unconfirmed_balance": 0,
  "final_balance": 100000000,
  "n_tx": 1,
  "unconfirmed_n_tx": 0,
  "final_n_tx": 1,
  "txrefs": [
    {
      "tx_hash": "918b246327ae90d9bf1a6fda6e880b07f5e1efa3c6db7e08be02d8f61c809693",
      "block_height": 523056,
      "tx_input_n": -1,
      "tx_output_n": 0,
      "value": 100000000,  <- TransactionOutput(value)???
      "ref_balance": 100000000,
      "spent": false,
      "confirmations": 1,
      "confirmed": "2018-05-17T02:56:22Z",
      "double_spend": false
    }
  ],
  "tx_url": "https://api.blockcypher.com/v1/btc/main/txs/"
}
```
and the output amount will be the inputs value (transaction receive admount) ?

output structure will be like this ?
```php
$output = new TransactionOutput('100000000', $script);
```
```php
$inputs = [
    ['txid'=>'transaction id', 'vout'=>0, 'value' => 'unspent amount of current input value ?']
];
foreach ($transaction->getInputs() as $index=>$input)
            foreach ($private_key as $pkey) {
                $pk = PrivateKeyFactory::fromWif($pkey);
                foreach ($inputs as $_i)
                    $signer->input($index,new TransactionOutput($_i['value'], $script),$signd)->sign($pk);
            }
```

like this ?

**Comment by afk11** [comment]
The required 'outputs' in this case are the outputs someone created in order to fund your wallet! 

You already have an array with [[txid,vout]], but you also need [[txid,vout,value,scriptPubKey(or just address]]

That data contains two things: the identifier of the output (txid,vout), the value, and then the script(related to the address). You have to use txid/vout to identify what inputs you want to spend, which you've already done.

But you also need to tell give the signer the (value, script) part. These aren't details YOU want to pay, these are the utxos' you are trying to spend! You've got the details already.

**Comment by afk11** [comment]
Hm, maybe blockcypher has a testnet api you can use, 10000 sats will probably a lot in a few years :P

**Comment by cevin** [comment]
@afk11  ..  that address is a example 🤣🤣. my generate multisig wallet address function
```php
function generate_multisign(Array $pubkeys) {
    try {
        $keys = [];
        foreach ($pubkeys as $pubkey) {
            $keys[] = PublicKeyFactory::fromHex($pubkey);
        }
        $script = ScriptFactory::scriptPubKey()->multisig(2,$keys,true);
        return [
            'address'=> (new P2shScript($script))->getAddress()->getAddress(),
            'script'=> $script->getBuffer()->getHex(),
            'object'=> $script
        ];
    } catch (Exception $e) {
        return false;
    }
}
```
have some wrong?

I know. finally I get a real raw transaction hex code and verified it.

> why not cache this?

just a test 😊

tks.

**Comment by afk11** [comment]
> @afk11 .. that address is a example roflrofl. my generate multisig wallet address function

Ah yes, sorry!

>> have some wrong?

nope, looks just fine! One thing to introduce, the P2shScript class caches some stuff since it's known exactly what kind of script it is. It has the same interface as Script, but a little extra. Makes things a little faster too.
```php
        $script = new P2shScript(ScriptFactory::scriptPubKey()->multisig(2,$keys,true)));
```

>> I know. finally I get a real raw transaction hex code and verified it.

That's excellent, great news!

>> just a test blush

hehe, cool :)

**Comment by cevin** [comment]
@afk11 
Can you give me your email address? There are some questions I would like to consult you about blockchain storage.😂😂
