### ISSUE TITLE
How do I use OP_RETURN when I build a tx？

### ISSUE THREAD

**Issue by RedSue** [Bit-Wasp/bitcoin-php#699]
$network = NetworkFactory::bitcoinTestnet();
        $addrCreator = new AddressCreator();

        $outpoint = new OutPoint(Buffer::hex('c32d31355006eedc37109df9a99a18f250cbf417f5d0b8584504d6d1eba26952'), 0);

        $address_from = 'n25x4njKPLb775YZtcAuvUWEjtrGwaJp6J';
        $address_to = 'muVSc4NMpaN58xHenJ7F1L2LHxs9gUFuNz';
        $balance = sprintf('%.8f', 0.29946286);
        $number = sprintf('%.8f', 0.00000546);
        $fee = sprintf('%.8f', 0.00005);
        $amount_to = intval($number * 100000000);
        $give_change = intval(bcsub(bcsub($balance, $number, 8), $fee, 8) * 100000000);
        $tx_build = TransactionFactory::build();
        $tx_build->version(1);
        $tx_build->spendOutPoint($outpoint);
        $tx_build->payToAddress($amount_to, $addrCreator->fromString($address_to, $network));
        if ($give_change > 0) {
            $tx_build->payToAddress($give_change, $addrCreator->fromString($address_from, $network));
        }
        $privateKey = PrivateKeyFactory::fromWif('KEYS', null, $network);
        $destination = ScriptFactory::scriptPubKey()->p2wkh($privateKey->getPubKeyHash());
        $p2sh = new P2shScript($destination);
        $tx_build->output(0, $p2sh->getOutputScript());
        $transaction = $tx_build->get();
        var_dump($transaction->getHex());

**Comment by afk11** [comment]
Make the script by hand (See ScriptCreator for DIY stuff, or check ScriptFactory::scriptPubKey()->opReturn() - I think it exists, lol)

Then add this output with zero value to $tx_build->output(0, $script);
and the rest to your change address.

Probably a good idea to randomize the order of outputs :)

**Comment by RedSue** [comment]
Thank you for your advice. I've done it.
