### ISSUE TITLE
Read if you used Zpub and Ypub in Slip132

### ISSUE THREAD

**Issue by afk11** [Bit-Wasp/bitcoin-php#703]
I learned recently that the Zpub and Ypub keys _don't_ refer to P2PKH types inside P2SH, P2WSH, as the other prefixes in Slip132. They're actually reserved for multisig.. which means when I added the following methods to Slip132, I published code that didn't follow the spec. 

`Slip132::p2shP2wshP2pkh`
`Slip132::p2wshP2pkh`

Essentially, if you have these Zpub|Ypub keys, wallets will probably expect a multi-signature script, not P2PKH. 

I'm going to mark these methods deprecated, and remove them from the library ASAP. I'll search for people who were interested, and maybe poke them here.

**Comment by dan-da** [comment]
good to know, thx.

**Comment by gits7r** [comment]
Do these go into 0.0.35.0 ? Were they backported? Because composer is telling me I am up to date, there is nothing to update and I do not have the latest commits.

**Comment by afk11** [comment]
@gits7r 0.0.35.1 will just mark them deprecated, and master will throw if you try to use them. Just tagged 0.0.35.1 now.
