### ISSUE TITLE
error in WifPrivateKeySerializer::serialize() with a Decred address.

### ISSUE THREAD

**Issue by dan-da** [Bit-Wasp/bitcoin-php#713]
Decred (and maybe others?) uses 2 byte address prefixes rather than 1 byte.

The line that fails is:
    Buffer::hex($network->getPrivByte(), 1, $math),

It works upon changing to:
    Buffer::hex($network->getPrivByte(), strlen($network->getPrivByte()), $math),

what do you think?  I can submit a pull request if helpful.

**Comment by afk11** [comment]
A PR would be great! I think we can drop setting the length since we know it's coming from a NetworkInterface already? We did the same to support zcash addresses IIRC.

**Comment by dan-da** [comment]
oh, sorry I see that WifPrivateKeySerializer::serialize() is already changed in master.  I was using v0.0.35.0 because it is latest stable release.  I think the changes in master will work, but I will test.

**Comment by dan-da** [comment]
ok, I verified it works in master, so I am closing this.

any idea when the next tagged version of bitcoin-php might be?
