### ISSUE TITLE
Sign multiple input transaction error (Argument 3 passed to sign() must implement interface)

### ISSUE THREAD

**Issue by pedromvpg** [Bit-Wasp/bitcoin-php#724]
I'm trying to get a transaction signed that has multiple inputs but I'm getting multiple errors when I use parameters that are suggested in other threads. Wonder if some one could tell me what I'm doing wrong:

```
$signer = new Signer($spendTx, $ecAdapter);
foreach ($spendTx->getInputs() as $index=>$input) {
	print_r($input);
	$signer->sign($index, $privateKey, $input->getScript());
}
```
and  

```
$signer = new Signer($spendTx, $ecAdapter);
foreach ($spendTx->getInputs() as $index=>$input) {
	print_r($input);
	$signer->sign($index, $privateKey, $input->getScript()->getHex());
}
```

both return

```
BitWasp\Bitcoin\Transaction\TransactionInput Object
(
    [outPoint:BitWasp\Bitcoin\Transaction\TransactionInput:private] => BitWasp\Bitcoin\Transaction\OutPoint Object
        (
            [hashPrevOutput:BitWasp\Bitcoin\Transaction\OutPoint:private] => BitWasp\Buffertools\Buffer Object
                (
                    [size] => 32
                    [buffer] => 0x6732fe6e253cb795b6fd0aecbd879a3670b6b43d04b75c234c98a0ffa8613097
                )
            [nPrevOutput:BitWasp\Bitcoin\Transaction\OutPoint:private] => 0
        )
    [script:BitWasp\Bitcoin\Transaction\TransactionInput:private] => BitWasp\Bitcoin\Script\Script Object
        (
            [hex] => 76a914759cfe30787773b942061846f3fcd280597e99f788ac
            [asm] => OP_DUP OP_HASH160 759cfe30787773b942061846f3fcd280597e99f7 OP_EQUALVERIFY OP_CHECKSIG
        )
    [sequence:BitWasp\Bitcoin\Transaction\TransactionInput:private] => 4294967295
)
```

> **Fatal error:  Uncaught TypeError: Argument 3 passed to BitWasp\Bitcoin\Transaction\Factory\Signer::sign() must implement interface BitWasp\Bitcoin\Transaction\TransactionOutputInterface**

What is the 3rd argument for sign() supposed to be?

**Comment by pedromvpg** [comment]
Or I with this

```
	$signer = new Signer($spendTx, $ecAdapter);
	foreach ($spendTx->getInputs() as $index=>$input) {
			
		$tx = TransactionFactory::fromHex($inputs[$index]['hex']);
		print_r($tx);
		$signer->sign($index, $privateKey, $tx->getOutput($index));
		
	}
```

I get this returned

```
BitWasp\Bitcoin\Transaction\Transaction Object
(
    [version:BitWasp\Bitcoin\Transaction\Transaction:private] => 1
    [inputs:BitWasp\Bitcoin\Transaction\Transaction:private] => Array
        (
            [0] => BitWasp\Bitcoin\Transaction\TransactionInput Object
                (
                    [outPoint:BitWasp\Bitcoin\Transaction\TransactionInput:private] => BitWasp\Bitcoin\Transaction\OutPoint Object
                        (
                            [hashPrevOutput:BitWasp\Bitcoin\Transaction\OutPoint:private] => BitWasp\Buffertools\Buffer Object
                                (
                                    [size] => 32
                                    [buffer] => 0x10be4a5bd4c35744429b892f36743b054fd295dd7a8bb55539857e1dcdd20045
                                )

                            [nPrevOutput:BitWasp\Bitcoin\Transaction\OutPoint:private] => 1
                        )

                    [script:BitWasp\Bitcoin\Transaction\TransactionInput:private] => BitWasp\Bitcoin\Script\Script Object
                        (
                            [hex] => 47304402200ee8855928ccd7f6f4085928710e197f19fb78b49bca9480819ac7ca1fb71ded022052678029f5d5902ab7c423616ee2b4ac81e2bb0bd40002c79dd0a1b881b4c20c012103e7d754a026b832f27a3db747378bd6b6f24e979407be6f3e6d3e6caedd7ab24a
                            [asm] => 304402200ee8855928ccd7f6f4085928710e197f19fb78b49bca9480819ac7ca1fb71ded022052678029f5d5902ab7c423616ee2b4ac81e2bb0bd40002c79dd0a1b881b4c20c01 03e7d754a026b832f27a3db747378bd6b6f24e979407be6f3e6d3e6caedd7ab24a
                        )

                    [sequence:BitWasp\Bitcoin\Transaction\TransactionInput:private] => 4294967295
                )

        )

    [outputs:BitWasp\Bitcoin\Transaction\Transaction:private] => Array
        (
            [0] => BitWasp\Bitcoin\Transaction\TransactionOutput Object
                (
                    [value:BitWasp\Bitcoin\Transaction\TransactionOutput:private] => 8397
                    [script:BitWasp\Bitcoin\Transaction\TransactionOutput:private] => BitWasp\Bitcoin\Script\Script Object
                        (
                            [hex] => 76a914759cfe30787773b942061846f3fcd280597e99f788ac
                            [asm] => OP_DUP OP_HASH160 759cfe30787773b942061846f3fcd280597e99f7 OP_EQUALVERIFY OP_CHECKSIG
                        )

                )

            [1] => BitWasp\Bitcoin\Transaction\TransactionOutput Object
                (
                    [value:BitWasp\Bitcoin\Transaction\TransactionOutput:private] => 0
                    [script:BitWasp\Bitcoin\Transaction\TransactionOutput:private] => BitWasp\Bitcoin\Script\Script Object
                        (
                            [hex] => 6a0450565847
                            [asm] => OP_RETURN 50565847
                        )

                )

        )

    [witness:BitWasp\Bitcoin\Transaction\Transaction:private] => Array
        (
        )

    [lockTime:BitWasp\Bitcoin\Transaction\Transaction:private] => 0
    [wtxid:BitWasp\Bitcoin\Transaction\Transaction:private] => 
    [hash:BitWasp\Bitcoin\Transaction\Transaction:private] => 
)
```


> **Fatal error:  Uncaught BitWasp\Bitcoin\Exceptions\ScriptQualificationError: Invalid script signature - must be PUSHONLY. in /bitwasp/bitcoin/src/Script/FullyQualifiedScript.php:197**

**Comment by afk11** [comment]
Sorry for the delay getting back to you - looking at it now, I see you were passing in the input script as an output script in the first snippet, since I see this
```
            [asm] => OP_DUP OP_HASH160 759cfe30787773b942061846f3fcd280597e99f7 OP_EQUALVERIFY OP_CHECKSIG
```

and in the next comment, I noticed this line:
```
	$signer->sign($index, $privateKey, $tx->getOutput($index));
```
which has a bug. instead of passing `getOutput` $index, it should actually be `$input->getOutPoint()->getVout()`. $index in this snippet is the index of the input in the spend tx, not the index of the output in the tx that paid you.

**Comment by pedromvpg** [comment]
Cool!! thanks for the response! Will try as soon as possible and come back to you if it works.
Great library by the way!

**Comment by afk11** [comment]
Please do! And thanks a lot!

**Comment by pedromvpg** [comment]
Is there and example of a transaction build with multiple inputs, where the script loops through the multiple utxo's until it reaches a total, builds and signs the transaction?

Can't seem to get it to work... :(

Just need a script to make automatic payments but sometimes single inputs are not enough.

Any help would be appreciated.

**Comment by afk11** [comment]
this is pretty much the coin selection / size estimation problem. tldr for that one: label your addresses with what type they are, and pop inputs aggregating size/fee/totalIn until outputs + fee are paid.

I've included a rough idea below. You precalculate your scripts size, and it'll get you a decent answer, however it doesn't deal with variable length integers for inputs or outputs, which can cause problems if you're paying close to min-relay-fee rate or have LOTS of inputs/outputs.

```
    $totalOut = X;
    $feeRate = Y;
    $mapTypeToSize = ['p2pkh' => 149];
    $txWithOutputs = new Transaction(... include outputs);
    $txFee = $txWithOutputs->getSize() * $feeRate;
    $inputs = [];
    $totalIn = 0;
    while($totalIn < $txFee + $totalOut) {
        $coin = array_pop($coins);
        $inputFee = $mapTypeToSize[$coin['type']] * $feeRate;
        $txFee += $inputFee;
        $inputs[] = $coin;
    }
    // deal with change, then sign
}
```

**Comment by joma512900** [comment]
I have the same error, my code is the following ...

`
function Transaction($to,$amount,$privateKey,$from){
    // Load private key
    $ecAdapter = Bitcoin::getEcAdapter();
	$privKeyFactory = new PrivateKeyFactory();
	$private_key = $privKeyFactory->fromWif($privateKey);
	// Generate raw transaction
	$addressCreator = new AddressCreator();
    $transaction = TransactionFactory::build();
    // inputs
    $inputs = file_get_contents("https://testnet-api.smartbit.com.au/v1/blockchain/address/".$from);
    $inputs = json_decode($inputs, true);
	$inputs = $inputs['address']['transactions'];

	$inputs_all = array();
	$ouputs_all = array();
	$i = 0; while ($i < count($inputs)) {
		unset($item_input);
		$item_input = array(
			'txid' => $inputs[$i]['txid'],
			'vout' => $inputs[$i]['inputs'][0]['vout'],
			'sequence' => strval($inputs[$i]['inputs'][0]['sequence']),
			'scriptPubKey' => $inputs[$i]['outputs'][0]['script_pub_key']['hex']
		);
		array_push($inputs_all, $item_input);
		unset($item_ouput);
		$item_ouput = array(
			'satochis' => $inputs[$i]['outputs'][0]['value_int'],
			'address' => $inputs[$i]['outputs'][0]['addresses'][0]
		);
		array_push($ouputs_all, $item_input);
		unset($item_ouput);
		$item_ouput = array(
			'satochis' => $inputs[$i]['outputs'][1]['value_int'],
			'address' => $inputs[$i]['outputs'][1]['addresses'][0]
		);
		array_push($ouputs_all, $item_input);
	$i++; }

	foreach ($inputs_all as $input) {
       	$transaction->input(
           	$input['txid'],
           	$input['vout'],
           	ScriptFactory::fromHex($input['scriptPubKey']),
       		$input['sequence']
       	);
	}
	//foreach ($ouputs_all as $ouput) {
    //    $transaction->payToAddress($ouput['satochis'],AddressFactory::fromString($ouput['address']));
    //}
	$transaction->payToAddress(45000,  $addressCreator->fromString($to));
    //$transaction->payToAddress(10000,  $addressCreator->fromString($from));
    
    $txOut = new TransactionOutput(
        10000,
        ScriptFactory::scriptPubKey()->payToPubKeyHash($private_key->getPubKeyHash())
    );

    // Make transaction
    $transaction = $transaction->get();
    // Sign transaction
    $signer = new Signer($transaction, $ecAdapter);
    foreach ($transaction->getInputs() as $index=>$input) {
            $signer->sign($index, $private_key, $txOut);
    }

    // Signing and get output
    $hex = $signer -> get() -> getHex();

    return $hex;
}
`
ERROR:
Uncaught BitWasp\Bitcoin\Exceptions\ScriptQualificationError: Invalid script signature - must be PUSHONLY

Help me friends :(

**Comment by afk11** [comment]
>        	ScriptFactory::fromHex($input['scriptPubKey']),

When you're building the input script, for some reason you've put the scriptPubKey instead of the scriptSig - scriptPubKey is the field in txout, not txin. The error you've gotten would explain this, because signatures have PUSHONLY opcodes but scriptPubKey have all the rest of the opcodes.

IIRC, you should either pass `new Script()` by itself, or even drop the argument (IIRC that might work). FYI, you are setting your inputs sequence to the same one as the transaction you are spending - but you can just use the default in case that was something else (0xffffffff, but not passing the arg should default to that)

I'm closing this issue because OP's problem was resolved - open another if you still need help!
