### ISSUE TITLE
Signing raw transaction - scriptPubKey not supported

### ISSUE THREAD

**Issue by tulang3587** [Bit-Wasp/bitcoin-php#729]
I've been having a problem when trying to sign a transaction, can you give me some insight?

The raw transaction has been created successfully using this library, and here's the hex:

`01000000017d2adc7945951368549858b0752571198de1ec1a6e923b9d9725ac7d3d197a6c0000000000ffffffff0290010000000000001976a9147c71e6ee867c0f5ceff3374fd99d5c665af1809988acf4010000000000001976a914bae6a34409b768704eccba0fc5344248eb16c34c88ac00000000`

However, I always get this **scriptPubKey not supported** error whenever I'm trying to sign it.

Here's the code:

    $privateKey = $privFactory->fromWif('cNsCfR9TadEJkXeoKMC4fv9g7KfmoHZ4SET6c63cTXY1UwSmecKv');
    $address = new PayToPubKeyHashAddress($privateKey->getPublicKey()->getPubKeyHash());
    $addressPubKey = $privateKey->getPublicKey();

    $amount = 500; // satoshis
    $change = 500; // satoshis
    $fee = 100; // satoshis
    $amountAfterFee = $amount - $fee;

    $transaction = TransactionFactory::build()
        ->input(
            '6c7a193d7dac25979d3b926e1aece18d19712575b05898546813954579dc2a7d', // prev unspent tx id
            0 // vout
        )
        ->payToAddress(
            $amountAfterFee, // the amount to send
            $addrCreator->fromString("mrrxXtvaPrksaVkr3oxjyMgRNSUHUaoZY1")) // target address
        ->payToAddress(
            $change, // the amount to send
            $addrCreator->fromString("mxZCGj76gyznyHCsdTKBQApDaSHbWNAqqJ")) // change address
        ->get();

    $redeemScript = ScriptFactory::scriptPubKey()->p2wkh($privateKey->getPubKeyHash());
    $p2shScript = new P2shScript($redeemScript);
    $signData = new SignData();
    $signData->p2sh($redeemScript);

    $signer = new Signer($transaction, Bitcoin::getEcAdapter());

    // foreach ($transaction->getInputs() as $index=>$input) {
    //     $signer->sign($index, $privateKey, new TransactionOutput(0, ScriptFactory::fromHex($input->getScript()->getBuffer()->getHex())));
    // }

    // foreach ($transaction->getInputs() as $index=>$input) {
    //     $signer->sign($index, $privateKey, $input->getScript());
    // }

    $transactionOutputs = [];
    foreach ($transaction->getInputs() as $idx => $input) {
        $transactionOutput = new TransactionOutput(0, ScriptFactory::fromHex($input->getScript()->getBuffer()->getHex()));
        array_push($transactionOutputs, $transactionOutput);
    }
    $signer = new Signer($transaction, Bitcoin::getEcAdapter());
    foreach ($transactionOutputs as $idx => $transactionOutput) {
        $signer->sign($idx, $privateKey, $transactionOutput, $signData);
    }

    // $signer = new Signer($spendTx, Bitcoin::getEcAdapter());
    // $signer->sign(0, $privateKey, $transaction->getOutput($spendOutput));

    $signedTxHex = $signer->get();

**Comment by afk11** [comment]
>     $transactionOutput = new TransactionOutput(0, ScriptFactory::fromHex($input->getScript()->getBuffer()->getHex()));

Inputs don't contain the script of the output, they contain a different script which provides a solution to the script of the previous output. You're passing $input->getScript() instead of `$p2shScript`

**Comment by tulang3587** [comment]
Got it to work, thanks for the help @afk11!

I tried using the `$p2shScript` and it's always rejected when I tried pushing the hex. However, instead of just using the `$p2shScript` I tried putting the input script from the unspent list instead.

    ->input(
        'd81527287fb23c174e3f75ff6e3fc0f684e68a608c1b7c22d6aa0419c1135f72', // prev unspent tx id
        0, // vout
        new Script(Buffer::hex('76a914bae6a34409b768704eccba0fc5344248eb16c34c88ac')) // scriptPubKey
    )

**Comment by afk11** [comment]
That's great news - best of luck
