### ISSUE TITLE
mdanter/ecc dev-master -> no matching package found

### ISSUE THREAD

**Issue by aakilfernandes** [Bit-Wasp/bitcoin-php#74]
Hey, I'm trying to add this package with `composer require bitwasp/bitcoin` but I keep getting `bitwasp/bitcoin v0.0.4 requires mdanter/ecc dev-master -> no matching package found`. Any thoughts?

Btw thanks for the awesome work. I think it'll be incredibly useful for https://github.com/anonymart/anonymart

**Comment by rubensayshi** [comment]
we're waiting for `mdanter/ecc` to get a `0.3.0` release (which should be soon ... ish ...), to get around it for now just put `"mdanter/ecc": "dev-master"` in your own composer.json (or just type `composer require mdanter/ecc:dev-master`)

**Comment by aakilfernandes** [comment]
Nice! Thanks so much. For anyone using laravel 4.2 you might also have to add `"symfony/console":"2.5.9 as 2.6.0"` since laravel requires an older version of `symfony/console` than `mdanter/ecc`.

**Comment by afk11** [comment]
Hey all - phpecc tagged 0.3.0 today, so about to PR the change to to ~0.3 now. Likely this will also fix the `symfony/console` requirement, since the package was marked `minimum-stability: dev` until now.
