### ISSUE TITLE
1 Page Transaction Builder 

### ISSUE THREAD

**Issue by besoeasy** [Bit-Wasp/bitcoin-php#765]
there are lot of problems on windows with dependent lib, best way to implement below code in single page without any dependices.

require __DIR__ . "/../vendor/autoload.php";
use BitWasp\Bitcoin\Address\AddressCreator;
use BitWasp\Bitcoin\Transaction\TransactionFactory;
$addrCreator = new AddressCreator();
$transaction = TransactionFactory::build()
    ->input('99fe5212e4e52e2d7b35ec0098ae37881a7adaf889a7d46683d3fbb473234c28', 0)
    ->payToAddress(29890000, $addrCreator->fromString('19SokJG7fgk8iTjemJ2obfMj14FM16nqzj'))
    ->payToAddress(100000, $addrCreator->fromString('1CzcTWMAgBNdU7K8Bjj6s6ezm2dAQfUU9a'))
    ->get();
echo $transaction->getHex() . PHP_EOL;

**Comment by afk11** [comment]
What problems, with what lib?

**Comment by besoeasy** [comment]
can you please try to do it, as your system environment is already stetted up

it would be favour, leave me your btc address ill tip if it works.

**Comment by besoeasy** [comment]
link to your documentation broken, in simple how do we sig transaction from unspent inputs ?

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/tx.spend.p2wpkh.php Check out the other tx.spend* examples as well. 

> link to your documentation broken,

huh?

**Comment by besoeasy** [comment]
Documentation
Check out the beginnings of the documentation for the library: [Introduction]


check this link its broken
https://github.com/Bit-Wasp/bitcoin-php/blob/master/doc/Introduction.md

**Comment by afk11** [comment]
My bad, I'll update the readme! I moved the one deeper recently https://github.com/Bit-Wasp/bitcoin-php/tree/master/doc/documentation

**Comment by besoeasy** [comment]
so how do we build a transaction using unspent inputs from here 👍 

https://blockexplorer.com/api/addr/1JfHxhhZnkhZtPJrU2juLbyeokzHaaZcNT/utxo


sorry but your documentation is very complex !

**Comment by afk11** [comment]
Sorry, don't have a lot of time to help. Did you get this working in the end?
