### ISSUE TITLE
Is there a way to increase the byte size of the OP_RETURN script output?

### ISSUE THREAD

**Issue by pedromvpg** [Bit-Wasp/bitcoin-php#772]
I know OP_RETURN is supposed to have a 40bytes limit but I’m seeing a lot of OP_RETURNS with a lot more characters.

Can this be changed for testing? Maybe here: tests/Script/Parser/ParserTest.php

```
public function testDataSize()
    {
        $buffer = new Buffer('', 40);
        $script = ScriptFactory::create()->push($buffer)->opcode(Opcodes::OP_HASH160)->getScript();
        $parsed = $script->getScriptParser();
        for ($i = 0; $i < 1; $i++) {
            $operation = $parsed->current();
            $this->assertEquals($operation->getData()->getSize(), $operation->getDataSize());
        }
    }
```

**Comment by pedromvpg** [comment]
Like this one:
https://www.blockchain.com/btc/tx/45e036c3019a970068feb1b751a34583524144d58cc87136dc1d2ef200bad248



DUP HASH160 PUSHDATA(20)[f1facb86109b72fa6428968440bfbbbb687ef35f] EQUALVERIFY CHECKSIG
--
RETURN PUSHDATA(75)[4557204c6f72656d20697073756d20646f6c6f722073697420616d65742c20636f6e7365637465747565722061646970697363696e6720656c69742e2041656e65616e20636f6d6d6f2021](decoded) EW Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commo !

**Comment by afk11** [comment]
Good catch, looks like it's up to node operators what size to allow. I checked OutputScriptFactory & OutputClassifier and can't find anywhere we create these scripts, but maybe I missed something?

**Comment by pedromvpg** [comment]
Ignore... I was accidentally trimming the string. I got it to broadcast a 40 bytes! Thanks

**Comment by afk11** [comment]
Awesome, great to hear!
