### ISSUE TITLE
Verification of a signature from a client running C# NBitcoin

### ISSUE THREAD

**Issue by EstebanGameDevelopment** [Bit-Wasp/bitcoin-php#775]
Hello,

I'm developing an application with Unity and C# and I'm using [NBitcoin](https://github.com/MetacoSA/NBitcoin) to get a signature so I can verify that same signature on the server with Bit-Wasp. 

So far I've been able to Bit-Wasp install the library with the composer and I've implemented the [example case for signature verification using Bit-Wasp](https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/signedmessage.verify.php). The main problem right now it's that it doesn't seem to recognize as valid the signature, so everytime that I called the verification: **$signer->verify($signedMessage, $address)** I'm getting false when it should be true. I'm **using Test Net both in the client and in the server** so it's not a problem that I'm working on different networks.

What am I missing? Are there multiple ways to verify a signature on Bit-Wasp? What other possible configurations could I use for the verfication process? 

Any help would be greatly appreciated.

**Comment by EstebanGameDevelopment** [comment]
I forgot to put the data:

**The signature on Test Net:**

-----BEGIN BITCOIN SIGNED MESSAGE-----
HOLA MON, COM ESTEM
-----BEGIN SIGNATURE-----
IKQLruydze++zscBBNd4UN9wqNZFV03VaH1PZ2zpqeI9JskSUzrI4RLQhaKMtpkZCZzv3BIDQjZfZNqPGjuyCRA=
-----END BITCOIN SIGNED MESSAGE-----

**The Public Address on Test Net:**

mosRoizxQyCyt7Y2DGpr5rrbyid5FYCNn3

**Comment by EstebanGameDevelopment** [comment]
I've checked with success the verification on these online signature verification webservices:

https://blockexplorer.com/messages/verify

https://reinproject.org/static/bitcoin-signature-tool/index.html#verify

In the last one is pretty similar to the format used by Bit-Wasp. Just copy and paste:

-----BEGIN BITCOIN SIGNED MESSAGE-----
HOLA MON, COM ESTEM
-----BEGIN SIGNATURE-----
mosRoizxQyCyt7Y2DGpr5rrbyid5FYCNn3
IKQLruydze++zscBBNd4UN9wqNZFV03VaH1PZ2zpqeI9JskSUzrI4RLQhaKMtpkZCZzv3BIDQjZfZNqPGjuyCRA=
-----END BITCOIN SIGNED MESSAGE-----

What am I doing wrong? This is the code that I'm using. Any help would be greatly appreciated:

```
		$network = NetworkFactory::bitcoinTestnet();
		Bitcoin::setNetwork($network);		
		$addrCreator = new AddressCreator();
		$sig = "-----BEGIN BITCOIN SIGNED MESSAGE-----
".$original_message_par."
-----BEGIN SIGNATURE-----
".base64_decode($message_signed_par)."
-----END BITCOIN SIGNED MESSAGE-----";
		
		$address = $addrCreator->fromString($publicaddress_par);	
		$compactSigSerializer = EcSerializer::getSerializer(CompactSignatureSerializerInterface::class);
		$serializer = new SignedMessageSerializer($compactSigSerializer);
		$signedMessage = $serializer->parse($sig);
		$signer = new MessageSigner();
		if ($signer->verify($signedMessage, $address)) {
			return true;
		} else {
			return false;
		}
```

**Comment by afk11** [comment]
```php
<?php
require "vendor/autoload.php";
use BitWasp\Bitcoin\Crypto\EcAdapter\EcSerializer;
use BitWasp\Bitcoin\Crypto\EcAdapter\Serializer\Signature\CompactSignatureSerializerInterface;
use BitWasp\Bitcoin\MessageSigner\MessageSigner;
use BitWasp\Bitcoin\Network\NetworkFactory;
use BitWasp\Bitcoin\Bitcoin;
use BitWasp\Bitcoin\Address\AddressCreator;
use BitWasp\Bitcoin\Serializer\MessageSigner\SignedMessageSerializer;

$network = NetworkFactory::bitcoinTestnet();
Bitcoin::setNetwork($network);
$addrCreator = new AddressCreator();
$sig = "-----BEGIN BITCOIN SIGNED MESSAGE-----
HOLA MON, COM ESTEM
-----BEGIN SIGNATURE-----
IKQLruydze++zscBBNd4UN9wqNZFV03VaH1PZ2zpqeI9JskSUzrI4RLQhaKMtpkZCZzv3BIDQjZfZNqPGjuyCRA=
-----END BITCOIN SIGNED MESSAGE-----";

$address = $addrCreator->fromString("mosRoizxQyCyt7Y2DGpr5rrbyid5FYCNn3");
$compactSigSerializer = EcSerializer::getSerializer(CompactSignatureSerializerInterface::class);
$serializer = new SignedMessageSerializer($compactSigSerializer);
$signedMessage = $serializer->parse($sig);
$signer = new MessageSigner();
if ($signer->verify($signedMessage, $address)) {
    echo "yay\n";
} else {
    echo "noooooooop\n";
}
```

I tried this one and it worked. Can you provide the library version, whether secp256k1 is installed, and can you verify what network is in use just before you call `$signer->verify`?

**Comment by EstebanGameDevelopment** [comment]
Sorry, I went with another solution. It was for a punctual problem and I needed a response back then.

**Comment by afk11** [comment]
cool, ok
