### ISSUE TITLE
Segwit message signing?

### ISSUE THREAD

**Issue by pandabadger** [Bit-Wasp/bitcoin-php#781]
Is there support for signing and verifying messages with segwit addresses?
My understanding from looking at bitcoin-php/examples/signedmessage.verify.php and verify() in BitWasp\Bitcoin\MessageSigner is that we must use a P2PKH address? 

I see that it is possible in some wallets, though perhaps not standardised. 

Thanks

**Comment by afk11** [comment]
We currently only support P2PKH message signing.
Saw this one on bitcoin/bips, does this look like the one you're using? https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki
