### ISSUE TITLE
[question] safe to use?

### ISSUE THREAD

**Issue by bitdaric** [Bit-Wasp/bitcoin-php#784]
would like to know if this repo is active and safe to use in an online project for generating addresses on the fly?

**Comment by afk11** [comment]
it's active and receives updates when needed :)

**Comment by bitdaric** [comment]
> 
> 
> it's active and receives updates when needed :)

thanks. can I install for php 5.6?

**Comment by bitdaric** [comment]
thanks. used this source:
https://freedomnode.com/blog/58/generate-bitcoin-wallet-addresses-from-extended-public-key-with-php

```

require_once('vendor/autoload.php');

use BitWasp\Bitcoin\Bitcoin;
use BitWasp\Bitcoin\Util\IntRange;
use BitWasp\Bitcoin\Address\AddressCreator;
use BitWasp\Bitcoin\Key\Deterministic\HdPrefix\GlobalPrefixConfig;
use BitWasp\Bitcoin\Key\Deterministic\HdPrefix\NetworkConfig;
use BitWasp\Bitcoin\Network\Slip132\BitcoinRegistry;
use BitWasp\Bitcoin\Key\Deterministic\Slip132\Slip132;
use BitWasp\Bitcoin\Key\KeyToScript\KeyToScriptHelper;
use BitWasp\Bitcoin\Key\Deterministic\HierarchicalKeyFactory;
use BitWasp\Bitcoin\Key\Deterministic\HierarchicalKeySequence;
use BitWasp\Bitcoin\Key\Deterministic\MultisigHD;
use BitWasp\Bitcoin\Network\NetworkFactory;
use BitWasp\Bitcoin\Serializer\Key\HierarchicalKey\Base58ExtendedKeySerializer;
use BitWasp\Bitcoin\Serializer\Key\HierarchicalKey\ExtendedKeySerializer;

class HD {
  private $network = NULL;
  private $xpub = NULL;
  private $ypub = NULL;
  private $zpub = NULL;
  private $multisig_xpubs = NULL;

  public function __construct($network = 'bitcoin') {
    if (version_compare(PHP_VERSION, '5.3') >= 0) {
      $this->network = NetworkFactory::$network();
    } elseif (version_compare(PHP_VERSION, '5.2.3') >= 0) {
      $this->network = call_user_func("NetworkFactory::$network");
    } else {
      $this->network = call_user_func('NetworkFactory', $network);
    }
  }

  public function set_xpub($xpub) {
    $this->xpub = $xpub;
  }

  public function set_ypub($ypub) {
    $this->ypub = $ypub;
  }

  public function set_zpub($zpub) {
    $this->zpub = $zpub;
  }

  public function set_multisig_xpubs($xpubs) {
    $this->multisig_xpubs = $xpubs;
  }

  public function address_from_master_pub($path = '0/0') {
    if ($this->xpub === NULL && $this->ypub === NULL && $this->zpub === NULL) {
      throw new Exception("XPUB, YPUB or ZPUB key is not present!");
    }

    $adapter = Bitcoin::getEcAdapter();
    $slip132 = new Slip132(new KeyToScriptHelper($adapter));
    $bitcoin_prefixes = new BitcoinRegistry();

    if ($this->xpub !== NULL) {
      $pubPrefix = $slip132->p2pkh($bitcoin_prefixes);
      $pub = $this->xpub;
    } else if ($this->ypub !== NULL) {
      $pubPrefix = $slip132->p2shP2wpkh($bitcoin_prefixes);
      $pub = $this->ypub;
    } else if ($this->zpub !== NULL) {
      $pubPrefix = $slip132->p2wpkh($bitcoin_prefixes);
      $pub = $this->zpub;
    }

    $config = new GlobalPrefixConfig([
      new NetworkConfig($this->network, [
        $pubPrefix,
      ])
    ]);

    $serializer = new Base58ExtendedKeySerializer(
      new ExtendedKeySerializer($adapter, $config)
    );

    $key = $serializer->parse($this->network, $pub);
    $child_key = $key->derivePath($path);

    return $child_key->getAddress(new AddressCreator())->getAddress();
  }

  public function multisig_address_from_xpub($m, $path = '0/0') {
    if (count($this->multisig_xpubs) < 2) {
      throw new Exception("XPUB keys are not present!");
    }

    $keys = array();

    foreach ($this->multisig_xpubs as $xpub) {
      $keys[] = HierarchicalKeyFactory::fromExtended($xpub, $this->network);
    }

    $sequences = new HierarchicalKeySequence();
    $hd = new MultisigHD($m, 'm', $keys, $sequences, TRUE);

    $child_key = $hd->derivePath($path);

    return $child_key->getAddress()->getAddress($this->network);
  }
}


$xpub = 'xpub66....';

$path = '0/0'; // 1st receiving address
// $path = '0/2'; // 3rd receiving address
// $path = '1/0'; // 1st change address
// $path = '1/1'; // 2nd change address

$hd = new HD();
$hd->set_xpub($xpub);
$address = $hd->address_from_master_pub($path);

echo $address;

```
got this error:

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid fingerprint for BIP32 key, must be in range [0 - (2^31)-1] inclusive' in .\bitcoin-php-master\vendor\bitwasp\bitcoin\src\Key\Deterministic\HierarchicalKey.php:81 Stack trace: #0 .\bitcoin-php-master\vendor\bitwasp\bitcoin\src\Key\Deterministic\HierarchicalKey.php(311): BitWasp\Bitcoin\Key\Deterministic\HierarchicalKey->__construct(Object(BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Adapter\EcAdapter), Object(BitWasp\Bitcoin\Key\KeyToScript\Factory\P2pkhScriptDataFactory), 1, '547773452', '0', Object(BitWasp\Buffertools\Buffer), Object(BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PublicKey)) #1 .\bitcoin-php-master\vendor\bitwasp\bitcoin\src\Key\Deterministic\HierarchicalKey.php(327): BitWasp\Bitcoin\Key\Deterministic\HierarchicalKey->deriveChild('0') #2 .\bitcoin-php-master\vendor\bitwasp\bitcoin\src\Key\Deterministic\HierarchicalKey.php(343): BitW in .\bitcoin-php-master\vendor\bitwasp\bitcoin\src\Key\Deterministic\HierarchicalKey.php on line 81
```

I found that IntRange::U32_MAX return 0

```
echo IntRange::U32_MAX;
0

```
Is this the problem?

commented this line and works fine:

`//throw new \InvalidArgumentException('Invalid fingerprint for BIP32 key, must be in range [0 - (2^31)-1] inclusive');
`

**Comment by afk11** [comment]
@bitdaric that code touches some of the crypto stuff, if you uncomment that line you'll have one hell of a panic when you can't find your bitcoins anymore.

use 64bit php.

**Comment by afk11** [comment]
can you paste the output of this please?

```php
<?php
echo PHP_INT_MAX;
echo PHP_EOL;
echo (1<<32)-1;
```

**Comment by bitdaric** [comment]
> 
> 
> can you paste the output of this please?
> 
> ```
> <?php
> echo PHP_INT_MAX;
> echo PHP_EOL;
> echo (1<<32)-1;
> ```

I am using php 5.6 32bit on Win10 64bit

results (last one was null):
```
2147483647
0


```

**Comment by afk11** [comment]
Yea the library isn't supported on 32-bit. I'm not sure how you installed it to be honest, composer should have checked that.

**Comment by bitdaric** [comment]
> 
> 
> Yea the library isn't supported on 32-bit. I'm not sure how you installed it to be honest, composer should have checked that. please install a 64-bit version of PHP.

well I installed in server and then copied in local computer  :D

it is now working fine with php 5.6 64bit on Windows for legacy (xpub) addresses but for zpub (p2wpkh) I get same error:

```
require_once('./HD.php');
$zpub = 'zpub...';//p2wpkh

$path = '0/0'; // 1st receiving address
// $path = '0/2'; // 3rd receiving address
// $path = '1/0'; // 1st change address
// $path = '1/1'; // 2nd change address

$hd = new HD();
//$hd->set_xpub($xpub);
$hd->set_zpub($zpub);
$address = $hd->address_from_master_pub($path);
echo $address;

```

`Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid fingerprint for BIP32 key, must be in range [0 - (2^31)-1] inclusive' in .\bitcoin-php-5_6\vendor\bitwasp\bitcoin\src\Key\Deterministic\HierarchicalKey.php:81 Stack trace: #0 .\bitcoin-php-5_6\vendor\bitwasp\bitcoin\src\Serializer\Key\HierarchicalKey\ExtendedKeySerializer.php(132): BitWasp\Bitcoin\Key\Deterministic\HierarchicalKey->__construct(Object(BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Adapter\EcAdapter), Object(BitWasp\Bitcoin\Key\KeyToScript\Factory\P2wpkhScriptDataFactory), '1', 1598321008, -2147483648, Object(BitWasp\Buffertools\Buffer), Object(BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PublicKey)) #1 .\bitcoin-php-5_6\vendor\bitwasp\bitcoin\src\Serializer\Key\HierarchicalKey\ExtendedKeySerializer.php(142): BitWasp\Bitcoin\Serializer\Key\HierarchicalKey\ExtendedKeySerializer->fromParser(Object(BitWasp\Bitcoin\Network\Networks\Bitcoin), Object(BitWasp\Buffertools\Parser)) #2 .\bitcoin- in .\bitcoin-php-5_6\vendor\bitwasp\bitcoin\src\Key\Deterministic\HierarchicalKey.php on line 81


`

```
PHP Version 5.6.40
System 	Windows NT 6.2 build 9200 (Windows 8 Professional Edition) AMD64
Build Date 	Jan 9 2019 15:05:21
Compiler 	MSVC11 (Visual C++ 2012)
Architecture 	x64 

``````

echo PHP_INT_MAX;
echo PHP_EOL;
echo (1<<32)-1;
die();
```

`2147483647 0`

**Comment by afk11** [comment]
> well I installed in server and then copied in local computer :D

looks like the PHP install is still somehow 32bit, because on 64-bit PHP_INT_MAX is 9223372036854775807

**Comment by bitdaric** [comment]
> 
> 
> > well I installed in server and then copied in local computer :D
> 
> looks like the PHP install is still somehow 32bit, because on 64-bit PHP_INT_MAX is 9223372036854775807

maybe this? https://stackoverflow.com/questions/17837157/php-64-bit-with-php-int-max-2147483647/34189773

**Comment by afk11** [comment]
"64bit builds that don't even use 64bit" heard of that one before - only on windows... I don't suppose you could just use a 64bit linux through docker?

**Comment by bitdaric** [comment]
will use 64bit linux, thanks

**Comment by afk11** [comment]
Cool, good luck!
