### ISSUE TITLE
Need params for network blockcypher testnet

### ISSUE THREAD

**Issue by noistudio** [Bit-Wasp/bitcoin-php#788]
Hello  can you say me some params for that https://live.blockcypher.com/bcy/

**Comment by afk11** [comment]
No idea - do they have source code for the node published? if so, try chainparams.cpp. 

Or get hacky and try base58 decoding an address of theirs (note which type of address it is - p2pkh or p2sh, etc). Once you have em, copy/paste the mainnet or testnet network class and customize in your project.

You should try asking blockcypher for questions related to their stack ;)

**Comment by noistudio** [comment]
https://www.blockcypher.com/dev/bitcoin/#testing

> Testing
We offer two different options for testing your blockchain application: Bitcoin Testnet3, and BlockCypher’s Test Chain. We offer automated faucets for both Testnet3 and BlockCypher’s Test Chain, but we recommend using BlockCypher’s Test Chain for a variety of reasons:

It’s nearly identical in characteristics to Bitcoin Main, with a few differences listed below.
The prefix for standard addreses is ‘B’ or 'C’ (0x1B). The prefix for multisig addresses is ’D’ (0x1F). This is also known as the “address version byte,” which you can read more about here.
The chain is private (no data is broadcasted, only BlockCypher mines the transactions), making it much more predictable than the Bitcoin’s testnet (which is frequently under attack).
New blocks get built every minute, confirming the transactions that have been created using our transaction API.
In case you missed the Resources section, the BlockCypher Test Chain is accessible from this resource:

https://api.blockcypher.com/v1/bcy/test

>

**Comment by afk11** [comment]
P2PKH = standard address
P2SH = multisig address
Copy this file, rename the class & path, https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Network/Networks/Bitcoin.php#L14, put in the hex part '1b' or '1f'
