### ISSUE TITLE
How to generate a private key and get the real public address?

### ISSUE THREAD

**Issue by MrsBookik** [Bit-Wasp/bitcoin-php#791]
I want to generate a new wallet / private key and display the public address where to send coins.

This is what I tried:

```
        $factory = new PrivateKeyFactory();
        $key = $factory->generateCompressed(new Random());
        $addressCreator = new AddressCreator();
```

Now I have to functions, fromString() and fromOutputScript(), nothing works with $key. 
Since there is no further documentation, I get in stuck here.

I found this code on [Stackoverflow](https://bitcoin.stackexchange.com/questions/48023/how-to-generate-addresses-in-php/48025):

```
        $privateKey = PrivateKeyFactory::create(true);
        $publicKey = $privateKey->getPublicKey();
        $address = $publicKey->getAddress();
```

But it doesn't work either. Everything has changed without further documentation, there is no create-method any more, there is not getPublicKey-method any more and so on...

Any help much appreciate!

**Comment by itinance** [comment]
This example should help you:

https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/privatekey.php

**Comment by itinance** [comment]
Also you may find several other examples in the ```example```-Folder for other use cases that might help

**Comment by afk11** [comment]
Yea the example above covers key -> pubkeyhash address

The recommended way is to create the bitcoin script and then convert that with an address with an AddressCreator. This example demonstrates a P2pkhScriptDataFactory: https://github.com/Bit-Wasp/bitcoin-php/blob/9e535f04665ba22ba2b8b63f371ec50d2e7eabb8/examples/addresstypes.script.php#L16-18

there's also an object for p2pk, and for multisig scripts. you can wrap the objects with a [P2sh / P2wsh / P2shP2wsh]ScriptDecorator work with those script types as well.

**Comment by MrsBookik** [comment]
Thanks a lot @afk11! What exactly does "Script" mean here in the context of getting an address? I know the term "Script" in context of making a transaction, which is not necessary here at the moment. Can you please explain the Wording here a bit that is used across this library?

**Comment by afk11** [comment]
It's the same meaning - addresses have about the same information as a bitcoin script. Addresses are only used by humans though - when someone pays BTC to your address, they actually reproduce your bitcoin script and put that in the transaction.

So in reality, the best way to let the software detect potential problems is to derive like this: `keys -> script -> address`. This allows software to check the keys are actually suitable for use in the script (some script types disallow certain public keys, so if you did this by hand without checking all the rules you could wind up with unspendable BTC) before calculating the address.

**Comment by afk11** [comment]
Hope OP's question was answered, reopen if necessary!

**Comment by Schiocco** [comment]
This issue should be open because no one answered the question. It is still impossible to understand how to generate a private key of derived address
