### ISSUE TITLE
Generated addresses are not correct / different / somewhere into nowhere?

### ISSUE THREAD

**Issue by honigkuchenbaer** [Bit-Wasp/bitcoin-php#792]
Creating a masterkey and importing this key with the extended private key into Electrum gives other addresses than with this library. And sending coins to them goes to nowhere but not into the particular wallet:

1. Create the master key:

```
        $network = Bitcoin::setNetwork(NetworkFactory::bitcoinTestnet());

        $random = new Random();
        $hdFactory = new HierarchicalKeyFactory();
        $master = $hdFactory->generateMasterKey($random);
        echo "Master key (m)\n";
        echo "   " . $master->toExtendedPrivateKey($network) . "\n";
```

2. Import this extended private key into Electrum gives me in Electrum on the "receive"-Tab for instance this address: **n28hWyXh8VPBCV6seKty19dW5ZNbqapB58** (running testnet)

3. Inspired by Examples from this repo I used this code to generate P2SH-addresses and P2WSH as well:

```
        $addrReader = new AddressCreator();
        $publicKey = $master->getPublicKey();
        $helper = new P2pkhScriptDataFactory();
        $scriptData = $helper->convertKey($publicKey);
        $script = $scriptData->getScriptPubKey();

        echo "key hash types\n";
        $p2pkh = $scriptData->getAddress($addrReader);
        echo " * p2pkh address: {$p2pkh->getAddress()}\n";

        echo "\nscript hash types:\n";

        $redeemScript = new P2shScript($p2pkh->getScriptPubKey());
        $p2shAddr = $redeemScript->getAddress();
        echo " * p2sh: {$p2shAddr->getAddress()}\n";
        $p2wshScript = new WitnessScript($p2pkh->getScriptPubKey());
        $p2wshAddr = $p2wshScript->getAddress();
        echo " * p2wsh: {$p2wshAddr->getAddress()}\n";
        $p2shP2wshScript = new P2shScript(new WitnessScript($p2pkh->getScriptPubKey()));
        $p2shP2wshAddr = $p2shP2wshScript->getAddress();
        echo " * p2sh|p2wsh: {$p2shP2wshAddr->getAddress()}\n";
```

**Output:**

```
 * p2pkh address: mjCptm7yxr3c7DpA6i17ude5ZkiHQMz7Rr

script hash types:
 * p2sh: 2MsjH4FEdpcwmwaTtbW3HFnx8aw1DCfN74G
 * p2wsh: tb1qnwsk39m5yw4m3h36ddvw9euvl0vxl7vg8mrmyj777pwl74crkassxgg7l2
 * p2sh|p2wsh: 2NFS1fXMuAJuJWaGAwMi7puE86n5XnbLEPo
```

Using the testnet, I have send Coins to all addresses: to the address that was displayed with Electrum and to all addresses that was generated via Bitwasp library.

Only the coins, that was send to Electrum reached the wallet. All other transactions went to somewhere but not into the Wallet presented with my master key from above.

What is wrong here?

**Comment by honigkuchenbaer** [comment]
Does this mean, these addresses doesn't belong to the master key where they was generated from?

**Comment by honigkuchenbaer** [comment]
I tried the following:

Derive a path:

  ```
      $purposePriv = $master->derivePath("{$purpose}'/0'/0'/0/0");
        echo "m/{$purpose}'/0'/0/0/0': ".$purposePriv->toExtendedPrivateKey().PHP_EOL;
        echo "M/{$purpose}'/0'/0/0/0': ".$purposePriv->toExtendedPublicKey().PHP_EOL;

        $purposePriv = $master->derivePath("{$purpose}'/0'/0'");

        $masterAddr = new PayToPubKeyHashAddress($purposePriv->getPublicKey()->getPubKeyHash());
        echo "   Address: " . $masterAddr->getAddress() . "\n\n";

```
I imported the xprv from derived key in Electrum, and send to the address from the very last line in example code some satoshis. Nothing arrived there in electrum.

Is there any example code or documentation available how to get a valid address where can coins really send to?

**Comment by afk11** [comment]
I don't think you should be trying all this at once. First, importing xprvs is kinda strange, I suggest you import the mnemonic so you aren't deriving something wrong unintentionally.

```php
$purpose = 44;
$factory = new HierarchicalKeyFactory();
$root = $factory->fromEntropy($seed);
$accountPriv = $root->derivePath("{$purpose}'/0'/0'"); // m/44'/0'/0' (change and regular addresses come from here)
$addressPriv = $accountPriv->derivePath("0/0"); // // m/44'/0'/0'/0/0 <- 0'th non-change address
$masterAddr = new PayToPubKeyHashAddress($purposePriv->getPublicKey()->getPubKeyHash());
echo "   Address: " . $masterAddr->getAddress() . "\n\n";

```

**Comment by honigkuchenbaer** [comment]
Thank you for your help. I tried this out on main net and got the following:

```
master public key: xpub6CXUv9gQCfQNNksArMAnKyu14vji7cK3V5wG7gYSoVntmtXTwzmhz4tFPzAiwagcdTYXXXjKCuFAQcUXM67k7cZL2sPbBEuZjp3GrwURdCo
   Address: 15e5vNCSE9iBUbRW6kdHx84XFEcQgY4zfC
```

After importing the xpub-key into Electrum, I got the receive-address: **144aHwG4JKtpCjpJLKcB7aZq8nEidrBaKN**

**Comment by afk11** [comment]
Oops, I realized a mistake in the snippet, I was passing $accountPriv instead of $addressPriv :)

I updated the snippet, could you try it again?

**Comment by honigkuchenbaer** [comment]
This works! Thank you very much. I'm still curious about the two times of path derivation.

The first ```$accountPriv = $root->derivePath("{$purpose}'/0'/0'");``` is clear to me.

But why is the second ```$addressPriv = $accountPriv->derivePath("0/0");``` required?

**Comment by afk11** [comment]
You could just do it in the first call to derivePath, it depends on what else you wanna do!

```php
$mnemonic = "blahblahblah";
$seed = (new Bip39SeedGenerator())->getSeed($mnemonic);
$factory = new HierarchicalKeyFactory();
$root = $factory->fromEntropy($seed);
$addressPriv = $root->derivePath("44'/0'/0'/0/0");
$address = new PayToPubKeyHashAddress($addressPriv->getPublicKey()->getPubKeyHash());
echo "   Address: " . $address->getAddress() . "\n\n";
```

**Comment by honigkuchenbaer** [comment]
Understood. Thank you! This works pretty well. But when I want to create P2SH-Addresses or Witness-Addresses, they still don't work.

This code generates a valid address, where coins can be received successfully:

```
        $masterAddr = new PayToPubKeyHashAddress($addressPriv->getPublicKey()->getPubKeyHash());
        echo "X Address: " . $masterAddr->getAddress() . "\n\n";
```

Also working with **AddressCreator** and **p2pkhScriptFactory**:

```
        $addrReader = new AddressCreator();
        $publicKey = $addressPriv->getPublicKey();
        $helper = new P2pkhScriptDataFactory();
        $scriptData = $helper->convertKey($publicKey);
        $script = $scriptData->getScriptPubKey();
        $p2pkh = $scriptData->getAddress($addrReader);
        echo " * p2pkh address: {$p2pkh->getAddress()}\n";
```

But the following address creation is NOT working. These addresses will never receive any coin that is controlled by the initial wallet:

```
        $redeemScript = new P2shScript($p2pkh->getScriptPubKey());
        $p2shAddr = $redeemScript->getAddress();
        echo " * p2sh: {$p2shAddr->getAddress()}\n";
        $p2wshScript = new WitnessScript($p2pkh->getScriptPubKey());
        $p2wshAddr = $p2wshScript->getAddress();
        echo " * p2wsh: {$p2wshAddr->getAddress()}\n";
        $p2shP2wshScript = new P2shScript(new WitnessScript($p2pkh->getScriptPubKey()));
        $p2shP2wshAddr = $p2shP2wshScript->getAddress();
        echo " * p2sh|p2wsh: {$p2shP2wshAddr->getAddress()}\n";
```

The code is based on this [example](https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/addresstypes.script.php). Either I understood something completely wrong or we should definitely remove this example from the Example-directory :)

**Comment by afk11** [comment]
All this is standardized in multiple BIP's - https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki https://github.com/bitcoin/bips/blob/master/bip-0049.mediawiki and https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki. 

My guess is you tried the addresstypes code after the derivation.. but that would be the wrong derivation to use. (purpose=44 is only in bip44)

**Comment by honigkuchenbaer** [comment]
Ok thank you! Understood. I own you something :)

**Comment by afk11** [comment]
Closing this, if there's anything else open another issue :)
