### ISSUE TITLE
How to fetch/send Transactions over the network?

### ISSUE THREAD

**Issue by honigkuchenbaer** [Bit-Wasp/bitcoin-php#793]
I'm curious how I can send my transactions over the network or how to fetch transactions for a specific address? I've found some mentions of something with RPCClient but could not find any classes for this in the repository?

**Comment by afk11** [comment]
> how I can send my transactions over the network?

we have a react-php based library for talking to the p2p network, an example of pushing a transaction is here: https://github.com/Bit-Wasp/bitcoin-p2p-php/blob/master/examples/pushtx.php

> how to fetch transactions for a specific address?

out of scope for this project - it's up to you :)
