### ISSUE TITLE
Generating Electrum compatible multisig addresses

### ISSUE THREAD

**Issue by minioff** [Bit-Wasp/bitcoin-php#794]
I am attempting to generate addresses that I see in Electrum wallet. 
Wallet is configured 2-out-of-2 P2SH-SW MultiSig and below is the script I am using. 
I see similar solutions used https://github.com/Bit-Wasp/bitcoin-php/issues/470 and https://gist.github.com/mariodian/5b67a1f315a74a7753a6f23d0198ec48

However the address that is returned to me does not match what I see in Electrum GUI.

```
<?php

/*
Setup:

cosigner 1
Ypub6jNcCukGn9UHnF9ANJoshTeqSL5hMHp7t8n7Ngxx9UJsJBjX6ZCECxEY516UmsNiW5A7DNyC6idXWAaQo3ZoUZuMkF9Ayi4qu1vjQZkfUys

cosigner 2
Ypub6jh5zBrbXhvG9uVwHb6BwXk6ZYp3teoXsrojxDYVcdWP5Ku152ekMfaqsK2A4vmvqexQoFGTMMK8BJcDMe1to5GmhLm1SoGzAe4GcAHshPq

script type> p2wsh-p2sh / p2sh-sw
path (default electrum): m/48'/0'/0'/1'
gui address 0: 3NQYyyaDSyeTyiXpJBrKvsTq5Kaf5VeTmj
gui address 1: 33mcCHgeHaHFWRWKJVdezKehCW6AHUWPJ2

*/
include_once("bitcoinphp/vendor/autoload.php");
include_once("includes/Network.BitcoinElectrum.php");


use BitWasp\Bitcoin\Key\Deterministic\HierarchicalKeyFactory;
use BitWasp\Bitcoin\Key\Deterministic\HierarchicalKeySequence;
use BitWasp\Bitcoin\Key\Deterministic\MultisigHD;
use BitWasp\Bitcoin\Serializer\Key\HierarchicalKey\Base58ExtendedKeySerializer;

$network = new BitcoinElectrum(); // magic bytes prefix 0295b43f

//as seen in Electrum
$multisig[] = "Ypub6jNcCukGn9UHnF9ANJoshTeqSL5hMHp7t8n7Ngxx9UJsJBjX6ZCECxEY516UmsNiW5A7DNyC6idXWAaQo3ZoUZuMkF9Ayi4qu1vjQZkfUys";
$multisig[] = "Ypub6jh5zBrbXhvG9uVwHb6BwXk6ZYp3teoXsrojxDYVcdWP5Ku152ekMfaqsK2A4vmvqexQoFGTMMK8BJcDMe1to5GmhLm1SoGzAe4GcAHshPq";

$keys = array();
foreach ($multisig as $ms) {
    $keys[] = HierarchicalKeyFactory::fromExtended($ms, $network);
}

//second 'path' parameter has no effect
$hd = new MultisigHD(2, "", $keys, new HierarchicalKeySequence(), true);

$child_key = $hd->derivePath("0/0");
$address = $child_key->getAddress()->getAddress();

var_dump($address); 
// string(34) "35mDzKKqER17vgwtgvsMZt49HhZfx8Xzo1"
// expected result 3NQYyyaDSyeTyiXpJBrKvsTq5Kaf5VeTmj
```

I would appreciate any pointers. 

Thank you!

**Comment by afk11** [comment]
This had me confused for a sec, but now I see you're using MultisigHD which only supports p2sh-multisig, not p2sh-p2wsh-multisig as you are doing. It got killed in newer versions. replace these lines with this:

```php
$pubKeys = array();
foreach ($multisig as $ms) {
    $pubKeys[] = HierarchicalKeyFactory::fromExtended($ms, $network)->derivePath("0/0")->getPublicKey();
}
$multisigScript = new P2shScript(new WitnessScript(ScriptFactory::scriptPubKey()->multisig(2, $pubKeys, $sort=true)));
$scriptPubKey = $multisigScript->getOutputScript();
// newer versions:
$addrCreator = new AddressCreator();
$addr = $addrCreator->fromOutputScript($scriptPubKey);
// older versions:
$addr = AddressFactory::fromOutputScript($scriptPubKey);
```

**Comment by kakobrekla** [comment]
Oh, I never would have caught that! I confirm the output is now correct. I appreciate your help, thank you.

Side note, for anyone else using above code, to get the address add `->getAddress()` to
`$addr = $addrCreator->fromOutputScript($scriptPubKey);`

**Comment by minioff** [comment]
Oh, I never would have caught that! I confirm the output is now correct. I appreciate your help, thank you.

Side note, for anyone else using above code, to get the address add `->getAddress()` to
`$addr = $addrCreator->fromOutputScript($scriptPubKey);`

**Comment by minioff** [comment]
Hey, 
one more question, would you mind explaining the reasoning behind `It got killed in newer versions.` ? Why is this not a thing any more? (Native segwit in bech32 format does not seem to be accepted widely enough yet.)

**Comment by afk11** [comment]
I thought I removed it at one point, but I checked and it's still there :P The latest code support different address types in the MultisigHD class https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Key/Deterministic/MultisigHD.php

**Comment by afk11** [comment]
Closing this, but ping if there's anything else!
