### ISSUE TITLE
Generate keypair for BigChainDB from seed

### ISSUE THREAD

**Issue by stefanvangastel** [Bit-Wasp/bitcoin-php#797]
Hi, I'm quite the crypto noob but have a question on how to generate a reproducible Ed25519 keypair from a seed (a common string, lets say a username or something).

According to the BigchainDB docs (for JS) compared to what this php-lib can do it should be possible: https://docs.bigchaindb.com/projects/js-driver/en/latest/usage.html#ed25519keypair-seed-functionality

How can I accomplish this using this bitcoin-php lib?

**Comment by afk11** [comment]
Unfortunately the library doesn't have any support for ed25519. ext-sodium available in several PHP versions and might support what you're trying to do!
