### ISSUE TITLE
[question] how to create p2sh address that starts with 3

### ISSUE THREAD

**Issue by IRGC** [Bit-Wasp/bitcoin-php#802]
how to create p2sh address that starts with 3 and spend the btc stored in it?
it need not be multisig address 
can you show examples?
from my understanding i need to create script and redeemscript , and use the redeemscript to spend the btc how to do with bitwasp library?

**Comment by afk11** [comment]
> how to create p2sh address 

how to create addresses from script hashes: https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/addresstypes.php#L28

>  and spend the btc stored in it?

example funding a p2sh address: https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/tx.fund.p2sh.multisig.php
example spending the generated utxo: https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/tx.spend.p2sh.multisig.php

I suggest changing the examples to your own keys, trying to spend several inputs at once, etc. Try booting up a bitcoind node in regtest mode (bitcoind -regtest), generating an address with the library, mining some coins to the address, then check you can sign with the lib and broadcast using sendrawtransaction :)

**Comment by IRGC** [comment]
> more likely, you'll be generating addresses with full knowledge of the redeemscript, so check https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/addresstypes.script.php

there are 3 types of address p2sh, p2wsh, p2sh|p2wsh in that example 
in almost all crypto exchanges user deposit address starting with 3, do you know which address type they probably using p2sh or p2sh|p2wsh ?

**Comment by afk11** [comment]
if it's 3, it means it's p2sh. you don't know what the real script code is unless they spend from that address.

**Comment by IRGC** [comment]
can you tell me what kind of address is this?
[3KbyJE2LL4H2tLt9nt1a8vT7CY7PRCYzUQ](https://www.blockchain.com/btc/tx/b93a87c25fb3ad4c820652d3308c0db96aa9b3cf9d03246d419d831820d340b0)
sorry for too many questions,just trying to gain knowledge about bitcoin and build something.

**Comment by afk11** [comment]
you want P2SH|P2WPKH - the address.types example might be of some help, but you should see the example for p2sh.p2wpkh. there's a fund transaction and a spend transaction you can experiment with.

**Comment by afk11** [comment]
Closing this as there doesn't seem to be anything further to this
