### ISSUE TITLE
How make transaction from Extended privatekey

### ISSUE THREAD

**Issue by lordfeo** [Bit-Wasp/bitcoin-php#816]
I did not find any example for making transaction from Extended key.

```
$factory = new HierarchicalKeyFactory();
$root = $factory->fromExtended("xprv...");
```

I don't know how to get Wif from extended private key, shall I do that?

**Comment by afk11** [comment]
Hi! 

Extended private keys have a function called getPrivateKey and getPublicKey
https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/src/Key/Deterministic/HierarchicalKey.php#L166

Does that help get you started?

**Comment by lordfeo** [comment]
Thanks.
