### ISSUE TITLE
How to create ScriptHashAddress from P2WPKH-string

### ISSUE THREAD

**Issue by dbdeadka** [Bit-Wasp/bitcoin-php#817]
Hi, 

I need to send btc to some address, and I have p2wpkh-representation only.
I tried to use advices from 
https://github.com/Bit-Wasp/bitcoin-php/issues/613#issuecomment-361771979
, but result is unexpected.

Code (which is creating address-object only) is below:

```php
require_once __DIR__ . "/vendor/autoload.php";

use BitWasp\Bitcoin\Address\Address;
use BitWasp\Bitcoin\Address\AddressCreator;
use BitWasp\Bitcoin\Address\PayToPubKeyHashAddress;
use BitWasp\Bitcoin\Bitcoin;
use BitWasp\Bitcoin\Script\WitnessProgram;
use BitWasp\Bitcoin\Script\P2shScript;
use BitWasp\Bitcoin\Key\Factory\PrivateKeyFactory;
use BitWasp\Bitcoin\Transaction\TransactionOutput;
use BitWasp\Bitcoin\Network\NetworkFactory;
use BitWasp\Bitcoin\Transaction\Factory\Signer;
use BitWasp\Bitcoin\Transaction\TransactionFactory;
use BitWasp\Bitcoin\Script\ScriptFactory;
use BitWasp\Bitcoin\Address\ScriptHashAddress;
use BitWasp\Buffertools\Buffer;
use BitWasp\Bitcoin\Address\SegwitAddress;


$destinationAddress = '3HnkejzGjAYzRuUt7o2sKRxuba2UKXMjdn';
echo "SRC: " . $destinationAddress . PHP_EOL;

Bitcoin::setNetwork(NetworkFactory::bitcoin());

$addressCreator = new AddressCreator();
$address = $addressCreator->fromString($destinationAddress);

$p2pkh = new PayToPubKeyHashAddress($address->getHash());

$p2wpkhWP1 = WitnessProgram::v0($p2pkh->getHash());
$p2shP2wsh1 = new ScriptHashAddress($p2wpkhWP1->getScript()->getScriptHash());

echo "DST: " . $p2shP2wsh1->getAddress() . PHP_EOL;
```

Output:

```
SRC: 3HnkejzGjAYzRuUt7o2sKRxuba2UKXMjdn
DST: 3DtHVsKx3U224n3vpTjRN6zc5NXxHGdrf4
```

Notice, that first line (SRC) and second line(DST) -  are not equals. What's am I doing wrong?

P. S.
Code for legacy

```php
$destinationAddress = '18Qbd5RWyQ6vmARZRNauXBjzs2xQDHa5Vo';
echo "SRC: " . $destinationAddress . PHP_EOL;

Bitcoin::setNetwork(NetworkFactory::bitcoin());

$addressCreator = new AddressCreator();
$address = $addressCreator->fromString($destinationAddress);
$p2pkh = new PayToPubKeyHashAddress($address->getHash());
echo "DST: " . $p2pkh->getAddress() . PHP_EOL;
```

and code for bech32
```php
$destinationAddress = 'bc1q2yl4j003q8hml5p3wyc9l7lzcmaej4gnwyfpxd';
echo "SRC: " . $destinationAddress . PHP_EOL;

Bitcoin::setNetwork(NetworkFactory::bitcoin());

$addressCreator = new AddressCreator();
$address = $addressCreator->fromString($destinationAddress);
$p2pkh = new PayToPubKeyHashAddress($address->getHash());
$p2wpkhWP1 = WitnessProgram::v0($p2pkh->getHash());
$p2shP2wsh1 = new SegwitAddress($p2wpkhWP1);
echo "DST: " . $p2shP2wsh1->getAddress() . PHP_EOL;
```

is working fine too.

In awaiting of your advice,
Sincerely,
dbdeadka

**Comment by afk11** [comment]
Hi, 

Naively scanning through the first example, I see this: 
```
$address = $addressCreator->fromString($destinationAddress);
```
this will give you the ScriptHashAddress you seem to want? (so call $address->getAddress())

But to be honest from the code examples and from your description, it's not clear what you are trying to do. Is it essentially (pseudocode) `EncodeAddress(DecodeAddress($address))`?

**Comment by afk11** [comment]
Hmm, so the first code tries to convert P2SH address to P2SH(bc1), but shouldn't the input address be bc1?

**Comment by afk11** [comment]
I think this does what you mean, convert a bech32 address to a witness program, and use that in a P2SH address:
```php
require_once __DIR__ . "/vendor/autoload.php";

use BitWasp\Bitcoin\Address\Address;
use BitWasp\Bitcoin\Address\AddressCreator;
use BitWasp\Bitcoin\Address\PayToPubKeyHashAddress;
use BitWasp\Bitcoin\Bitcoin;
use BitWasp\Bitcoin\Script\WitnessProgram;
use BitWasp\Bitcoin\Script\P2shScript;
use BitWasp\Bitcoin\Key\Factory\PrivateKeyFactory;
use BitWasp\Bitcoin\Transaction\TransactionOutput;
use BitWasp\Bitcoin\Network\NetworkFactory;
use BitWasp\Bitcoin\Transaction\Factory\Signer;
use BitWasp\Bitcoin\Transaction\TransactionFactory;
use BitWasp\Bitcoin\Script\ScriptFactory;
use BitWasp\Bitcoin\Address\ScriptHashAddress;
use BitWasp\Buffertools\Buffer;
use BitWasp\Bitcoin\Address\SegwitAddress;

$destinationAddress = 'bc1q2yl4j003q8hml5p3wyc9l7lzcmaej4gnwyfpxd';
echo "SRC: " . $destinationAddress . PHP_EOL;

Bitcoin::setNetwork(NetworkFactory::bitcoin());

$addressCreator = new AddressCreator();
$p2wpkhWP1 = $addressCreator->fromString($destinationAddress);

$p2shP2wsh1 = new ScriptHashAddress($p2wpkhWP1->getScriptPubKey()->getScriptHash());
echo "DST: " . $p2shP2wsh1->getAddress() . PHP_EOL;

```

**Comment by dbdeadka** [comment]
> 
> 
> Hi,
> 
> Naively scanning through the first example, I see this:
> 
> ```
> $address = $addressCreator->fromString($destinationAddress);
> ```
> 
> this will give you the ScriptHashAddress you seem to want? (so call $address->getAddress())
> 
> But to be honest from the code examples and from your description, it's not clear what you are trying to do. Is it essentially (pseudocode) `EncodeAddress(DecodeAddress($address))`?
> 
> Edit:
> by the way getHash is the same result here -so converting to PayToPubKeyHashAddress is unnecessary
> 
> ```
> $p2pkh = new PayToPubKeyHashAddress($address->getHash());
> $p2wpkhWP1 = WitnessProgram::v0($p2pkh->getHash());
> ```

Thank you so much, I followed your words and changed
$p2shP2wsh1 = new ScriptHashAddress($p2wpkhWP1->getScript()->getScriptHash());
to
$p2shP2wsh2 = new ScriptHashAddress($p2wpkhWP1->getProgram());
And now my "SRC" and DST are equals.

**Comment by dbdeadka** [comment]
> 
> 
> I think this does what you mean, convert a bech32 address to a witness program, and use that to create a P2SH address:
> 
> ```
> require_once __DIR__ . "/vendor/autoload.php";
> 
> use BitWasp\Bitcoin\Address\Address;
> use BitWasp\Bitcoin\Address\AddressCreator;
> use BitWasp\Bitcoin\Address\PayToPubKeyHashAddress;
> use BitWasp\Bitcoin\Bitcoin;
> use BitWasp\Bitcoin\Script\WitnessProgram;
> use BitWasp\Bitcoin\Script\P2shScript;
> use BitWasp\Bitcoin\Key\Factory\PrivateKeyFactory;
> use BitWasp\Bitcoin\Transaction\TransactionOutput;
> use BitWasp\Bitcoin\Network\NetworkFactory;
> use BitWasp\Bitcoin\Transaction\Factory\Signer;
> use BitWasp\Bitcoin\Transaction\TransactionFactory;
> use BitWasp\Bitcoin\Script\ScriptFactory;
> use BitWasp\Bitcoin\Address\ScriptHashAddress;
> use BitWasp\Buffertools\Buffer;
> use BitWasp\Bitcoin\Address\SegwitAddress;
> 
> $destinationAddress = 'bc1q2yl4j003q8hml5p3wyc9l7lzcmaej4gnwyfpxd';
> echo "SRC: " . $destinationAddress . PHP_EOL;
> 
> Bitcoin::setNetwork(NetworkFactory::bitcoin());
> 
> $addressCreator = new AddressCreator();
> $p2wpkhWP1 = $addressCreator->fromString($destinationAddress);
> 
> $p2shP2wsh1 = new ScriptHashAddress($p2wpkhWP1->getScriptPubKey()->getScriptHash());
> echo "DST: " . $p2shP2wsh1->getAddress() . PHP_EOL;
> ```

No, I mean another, but this part of code is very useful too!

**Comment by dbdeadka** [comment]
So, glory and victory, now we are able to send money to any type of addresses, it's great!

But in these 3 cases we use different type of address-classes (they are passed into payToAddress-function )

1. PayToPubKeyHashAddress (for P2PKH) 
BitWasp\Bitcoin\Address\PayToPubKeyHashAddress class

2. ScriptHashAddress (for P2SH P2WPKH) 
BitWasp\Bitcoin\Address\ScriptHashAddress class

3. SegwitAddress (for P2SH P2WPKH) 
BitWasp\Bitcoin\Address\SegwitAddress class

Pease, have a look to the code, which (I hope anyway) is detecting the type of address. Is it correct?

```php
<?php

require_once __DIR__ . "/vendor/autoload.php";

use BitWasp\Bitcoin\Address\Address;
use BitWasp\Bitcoin\Address\AddressCreator;
use BitWasp\Bitcoin\Address\PayToPubKeyHashAddress;
use BitWasp\Bitcoin\Address\ScriptHashAddress;
use BitWasp\Bitcoin\Address\SegwitAddress;
use BitWasp\Bitcoin\Script\WitnessProgram;
use BitWasp\Bitcoin\Bitcoin;
use BitWasp\Bitcoin\Network\NetworkFactory;
$addressStrings = [
        '18Qbd5RWyQ6vmARZRNauXBjzs2xQDHa5Vo',
        '3HnkejzGjAYzRuUt7o2sKRxuba2UKXMjdn',
        'bc1q2yl4j003q8hml5p3wyc9l7lzcmaej4gnwyfpxd'
];

Bitcoin::setNetwork(NetworkFactory::bitcoin());
$network = Bitcoin::getNetwork();
$ecAdapter = Bitcoin::getEcAdapter();
$addressCreator = new AddressCreator();
$addressObjectForPaying = null;

foreach ($addressStrings as $addressString) {
        echo "SRC:" . $addressString . PHP_EOL;
        $address = $addressCreator->fromString($addressString);
        echo 'class: ' . get_class($address) . PHP_EOL;

        $p2pkh = new PayToPubKeyHashAddress($address->getHash());

        if ($address instanceof PayToPubKeyHashAddress) {
                $addressObjectForPaying = $p2pkh;
        }
        if ($address instanceof ScriptHashAddress) {
                $p2wpkhWP1 = WitnessProgram::v0($p2pkh->getHash());
                $p2shP2wsh2 = new ScriptHashAddress($p2wpkhWP1->getProgram());
                $addressObjectForPaying = $p2shP2wsh2;
        }
        if ($address instanceof SegwitAddress) {
                $p2wpkhWP1 = WitnessProgram::v0($p2pkh->getHash());
                $p2shP2wsh1 = new SegwitAddress($p2wpkhWP1);
                $addressObjectForPaying = $p2shP2wsh1;
        }

        echo "DST:" . $addressObjectForPaying->getAddress() . PHP_EOL . PHP_EOL;
}

//After $addressObjectForPaying object will be passed to TransactionFactory::build()->payToAddress function
```

**Comment by afk11** [comment]
no need for witness program in ScriptHash?
```
        if ($address instanceof ScriptHashAddress) {
                $p2wpkhWP1 = WitnessProgram::v0($p2pkh->getHash());
```

BTW, since $address is already an Address object, why do you have to take the hash and re-create the address object as $addressObjectForPaying? It should be the exact same object you're creating, unless I'm missing something else

**Comment by dbdeadka** [comment]
> no need for witness program in ScriptHash?
```php
$p2wpkhWP1 = WitnessProgram::v0($p2pkh->getHash());
$p2shP2wsh2 = new ScriptHashAddress($p2wpkhWP1->getProgram());
$addressObjectForPaying = $p2shP2wsh2;
```
But we use witnessProgram here? How could we avoid it? If I understand you correctly.
> 
> ```
>         if ($address instanceof ScriptHashAddress) {
>                 $p2wpkhWP1 = WitnessProgram::v0($p2pkh->getHash());
> ```
> 
> BTW, since $address is already an Address object, why do you have to take the hash and re-create the address object as $addressObjectForPaying? It should be the exact same object you're creating, unless I'm missing something else

Could I ask you to show your idea through the code? Otherwise it's difficult for me to understand you.

**Comment by afk11** [comment]
Maybe it's something application specific :) '3HnkejzGjAYzRuUt7o2sKRxuba2UKXMjdn' doesn't always mean v0_witness in P2SH, so when you mentioned paying to addresses, code converting the addresses to other formats  just seems out of place.

```php
// ...
foreach ($addressStrings as $addressString) {
        $addressObjectForPaying = null;
        echo "SRC:" . $addressString . PHP_EOL;
        $address = $addressCreator->fromString($addressString);
        echo 'class: ' . get_class($address) . PHP_EOL;

        echo "DST:" . $address->getAddress() . PHP_EOL . PHP_EOL;
}
```

**Comment by dbdeadka** [comment]
**afk11**, Thank you very much!

**Comment by afk11** [comment]
You're very welcome :)
