### ISSUE TITLE
Always throwing function: \BitWasp\Bitcoin\Transaction\Factory\Signer::setCheckerCreator

### ISSUE THREAD

**Issue by olegabr** [Bit-Wasp/bitcoin-php#818]
https://github.com/Bit-Wasp/bitcoin-php/blob/5e404b66c4b8386f978a44eeb1190098c3397bea/src/Transaction/Factory/Signer.php#L90

The `signatureCreator` member never equals `null`. The `setCheckerCreator` function always throws.

No way to set custom `checkerCreator` member.

I need it to upgrade the https://github.com/btccom/bitwasp-bitcoin-bch-addon to the latest `bitwasp/bitcoin` lib version.

**Comment by afk11** [comment]
@olegabr Hi! Thanks for opening this issue.

Yea I see what you mean - that's kind of annoying.. Wanna PR using `count($this->signatureCreator) === 0` or something that works?

Two quick tests as well if you can
 * pass the project default CheckerCreatorBase immediately after creating the TxSigner - should work
 * pass the project default CheckerCreatorBase after calling 'input' or 'sign', should throw that exception

If not I might get to it soon

**Comment by olegabr** [comment]
@afk11 Thank you for quick response, I'll see what I can do here.

**Comment by olegabr** [comment]
@afk11, the PR is sent. Check it please.

**Comment by afk11** [comment]
Hi @olegabr - I merged your commit to 1.0 and master, and it looks like 0.0.35 doesn't have this issue!

Now released as v1.0.4
