### ISSUE TITLE
Script evaluated without error but finished with a false/empty top stack element

### ISSUE THREAD

**Issue by zer0sOriginal** [Bit-Wasp/bitcoin-php#830]
Hi!

$network = BitWasp\Bitcoin\Network\NetworkFactory::bitcoinTestnet();
$privKeyFactory = new PrivateKeyFactory();
$privateKey = $privKeyFactory->fromWif("cV3TmryirjFK4BTpRPDQcKa5w1XtKEr1sXxJezrZAgXX3dhDVufr",$network);
      
$out = ScriptFactory::scriptPubKey()->payToPubKeyHash($privateKey->getPubKeyHash());
$txOut = new TransactionOutput(16697794, $out);

$addressCreator = new AddressCreator();
$transaction = TransactionFactory::build()
->input('603424609575675926415b13ec7b31379b1f76d273a8ab92369c968933292afc', 0)
->payToAddress(16687794, $addressCreator->fromString('2MxV67TTU4FB7U1NXdvEu1Zndsca5WnUYZZ',$network))
->get();
  
   $signer = new Signer($transaction);
   $signer -> sign (0, $privateKey, $txOut);
   $signed = $signer->get();

  echo $signed->getHex();

----------------------------------------------------------------------------------

HEX: 0100000001fc2a293389969c3692aba873d2761f9b37317bec135b41265967759560243460000000006b48304502210093231fdb33f2b9789861d9aab0ce97fcea755f1130a58e7a9a19eb24fd82e9b402207c956009df1fd751aacb3c59b43e44b0e20faf28ed82a9a70672f7418721e9a9012102d4c3d9b94ad940478b7b1ea4eac26863bf5bbb97dc2fd64294c0cbc104f322ffffffffff01b2a2fe000000000017a9143977e0a791719208f4081609040910f8004bce148700000000

------------------------------------------------------------------------------------

{
  "txid": "5e0db55f37669016781a32015f088582e9cbacbd9307048d67413308417a92b0",
  "hash": "5e0db55f37669016781a32015f088582e9cbacbd9307048d67413308417a92b0",
  "version": 1,
  "size": 190,
  "vsize": 190,
  "weight": 760,
  "locktime": 0,
  "vin": [
    {
      "txid": "603424609575675926415b13ec7b31379b1f76d273a8ab92369c968933292afc",
      "vout": 0,
      "scriptSig": {
        "asm": "304502210093231fdb33f2b9789861d9aab0ce97fcea755f1130a58e7a9a19eb24fd82e9b402207c956009df1fd751aacb3c59b43e44b0e20faf28ed82a9a70672f7418721e9a9[ALL] 02d4c3d9b94ad940478b7b1ea4eac26863bf5bbb97dc2fd64294c0cbc104f322ff",
        "hex": "48304502210093231fdb33f2b9789861d9aab0ce97fcea755f1130a58e7a9a19eb24fd82e9b402207c956009df1fd751aacb3c59b43e44b0e20faf28ed82a9a70672f7418721e9a9012102d4c3d9b94ad940478b7b1ea4eac26863bf5bbb97dc2fd64294c0cbc104f322ff"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.16687794,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_HASH160 3977e0a791719208f4081609040910f8004bce14 OP_EQUAL",
        "hex": "a9143977e0a791719208f4081609040910f8004bce1487",
        "reqSigs": 1,
        "type": "scripthash",
        "addresses": [
          "2MxV67TTU4FB7U1NXdvEu1Zndsca5WnUYZZ"
        ]
      }
    }
  ]
}

-------------------------------------------------------------------------

When I try to sendrawtransaction  I get an error - mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element) (code 16) (code -26).

What could be my mistake?

**Comment by afk11** [comment]
```php
$privKeyFactory->fromWif("cV3TmryirjFK4BTpRPDQcKa5w1XtKEr1sXxJezrZAgXX3dhDVufr",$network);

$out = ScriptFactory::scriptPubKey()->payToPubKeyHash($privateKey->getPubKeyHash());
$txOut = new TransactionOutput(16697794, $out);
```
`$out` isn't generated correctly here. The addresses are all P2SH testnet addresses, hence there's no way you could be spending a pay-to-pub-key-hash script.

How did you generate 2N4jbP5LuEoZrY1i8i7z4iWMvxEx2vYUmJN? Since it's P2SH, we'll need to know the redeemScript for it as well if you want to be able to sign.

**Comment by zer0sOriginal** [comment]
Thanks for the quick response.
> How did you generate 2N4jbP5LuEoZrY1i8i7z4iWMvxEx2vYUmJN? 
Received address generated in bitcoin core. getnewaddress.

**Comment by zer0sOriginal** [comment]
Thank you for your help in solving the problem and for your work.

Here is the working code.

-------------------------------------------------------------------------------------------

$network = BitWasp\Bitcoin\Network\NetworkFactory::bitcoinTestnet();
$privKeyFactory = new PrivateKeyFactory();
$privateKey = $privKeyFactory->fromWif("cV3TmryirjFK4BTpRPDQcKa5w1XtKEr1sXxJezrZAgXX3dhDVufr",$network);
$redeemScript = ScriptFactory::scriptPubKey()->p2wkh($privateKey->getPubKeyHash());
$p2shScript = new P2shScript($redeemScript);
$outpoint = new OutPoint(Buffer::hex('603424609575675926415b13ec7b31379b1f76d273a8ab92369c968933292afc', 32), 0);
$txOut = new TransactionOutput(16697794, $p2shScript->getOutputScript());
$addressCreator = new AddressCreator();
$tx = (new TxBuilder())
    ->spendOutPoint($outpoint)
    ->payToAddress(16687794, $addressCreator->fromString('2MxV67TTU4FB7U1NXdvEu1Zndsca5WnUYZZ',$network))
    ->get();

$signData = (new SignData())->p2sh($redeemScript);
$signer = new Signer($tx);
$input = $signer->input(0, $txOut, $signData);
$input->sign($privateKey);
$signed = $signer->get();

echo $signed->getHex();

**Comment by afk11** [comment]
Nice work!
