### ISSUE TITLE
Creating addresses based on that a user is sending?

### ISSUE THREAD

**Issue by tamerkalieh** [Bit-Wasp/bitcoin-php#833]
Hello, I am working on a project in which I want to generate BTC addresses for users, so that they can receive and send BTC's. 

To be honest, I don't get along with this myself. I have come so far: 

---
Okay stop. The one who gave me the job said, it's not safe for users to generate those on the backend and send it to the frontend. So I don't need to do that task anymore 😂😅

**Comment by afk11** [comment]
bitcoin-php doesn't provide a wallet, you have to work it out yourself exactly how to go about that. The last one, while appearing to work, doesn't save private keys anywhere! so any funds sent there will be lost unless securely saved.

You need to design your application in a secure way, so I suggest looking the bitcoin BIP's for wallets (BIP39, BIP32, and something like BIP44/84/etc for the address derivation), and isolating any machine or application that deals with private keys. 

The design is pretty much up to you, but if you've a specific question maybe we'll be able to help!
