### ISSUE TITLE
0x8c OR 0x8b

### ISSUE THREAD

**Issue by vvpgrp** [Bit-Wasp/bitcoin-php#834]
According "_Dash Developer Reference_" (see section ["_Address Conversion_"](https://dash-docs.github.io/en/developer-reference#address-conversion) ) a value **0x8c** is a prefix for P2PKH addresses on the Dash testing network (testnet). 

In [this line](https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/src/Network/Networks/DashTestnet.php#L15), the prefix value is **0x8b**.

**How right?**

**Comment by afk11** [comment]
All altcoin NetworkInterfaces are going to be removed in a future release. (They get changed by the cryptocurrency, then this lib is out of date, and developers complain that it doesn't work). You should copy it into your own project, and manage the constants yourself
