### ISSUE TITLE
Can you write a template, how to build a complete send transaction

### ISSUE THREAD

**Issue by wartw** [Bit-Wasp/bitcoin-php#836]
Can you write a template, how to build a complete send transaction

**Comment by afk11** [comment]
Sorry, I feel this is answered between the examples and the documentation. 
https://github.com/Bit-Wasp/bitcoin-php/tree/1.0/examples
https://github.com/Bit-Wasp/bitcoin-php/tree/1.0/doc/documentation

If there's something missing, you'll need to let me know what you want to do, what you tried, and what went wrong.

**Comment by wartw** [comment]
I try to get Private key from https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/privatekey.php
Establish sending transactions using https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/transactionBuilder.php

But I found that the address I transferred into p2pkh address was automatically transferred to other addresses, but the address of p2wpkh address was received normally.

How do I now set up a transaction from the address of p2wpkh and go to another address?
The content line of your https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/transactionBuilder.php recommends remarks to better understand what you are writing!

**Comment by wartw** [comment]
This is the p2pkh address I created
https://www.blockchain.com/btc/address/16i3yfHqGD1Anwy8mGf2vT6tPXaCxNwi6Y You can check (the transfer is not my operation, the transfer will be automatically transferred immediately
P2wpkh address is received normally under the same private key
https://www.blockchain.com/btc/address/bc1q86wzkxyym298gzz3ly47x9vyvycec7uxhpk00v But I don't know how to transfer the BTC under p2wpkh address, can you help me? thank you

**Comment by afk11** [comment]
> the address I transferred into p2pkh address was automatically transferred to other addresses

> the transfer is not my operation

That sounds weird. Are you sure it was a freshly generated private key? (based on usage it seems it is).. It's highly possible random addresses from the chain made it into examples over the years.. Otherwise, you've got some big problems if someone can spend from your private key.

> But I don't know how to transfer the BTC under p2wpkh address,

Did you try the spend P2WPKH example? https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/tx.spend.p2wpkh.php

**Comment by wartw** [comment]
I don't understand you
https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/doc/tx/004_create_tx.php
How was the 24-line HEX obtained?

**Comment by afk11** [comment]
That example just shows how you can go from objects to the tx hex if you want to build it that way. 

It's the input scriptSig, so it has signatures. You get it by signing the transaction (covered more later)
https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/doc/tx/004_create_tx.php#L24

**Comment by wartw** [comment]
If it is convenient to write a complete detailed trading instruction for P2WPKH?  Because the proxy broadcast of the offline transaction part of P2PKH is no longer accepted
For example: https://www.blockchain.com/

**Comment by afk11** [comment]
1. Download bitcoind, and get it running in regtest mode
2. Generate a private key and create the p2wpkh address
3. Send regtest BTC to the address
4. Get the details of the UTXO you created
5. Put the details of the UTXO in here: https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/tx.spend.p2wpkh.php
6. Take the witness serialized transaction and try broadcast using bitcoin-cli sendrawtransaction. If it fails, you probably entered incorrect data in the script, go back and try 6 again.

**Comment by wartw** [comment]
txid: 9af78d52480376adbf578e4fae959153e242b7ca308ac64f8a741f6e79195c51
raw: 0100000001523307d637a690493d8ef97bf72ac3677e3027209cbf7ccfa909015d585afae4000000006a47304402204b15749bdc63cddcbd79dab2c6367d5458500561eff600bd42ba942e6367e0d602207039ab7b7e46251ecf1200f0de8a70e88a445264a21695d85b9424127041967c01210344104eb449400433ed122828b2e3dc04843e1e7ce99bc8e670b93a6bec5699eeffffffff01e8030000000000001976a914443a70c814b14ede9e7d52628bc0dd51b51d4a4b88ac00000000
input valid? true

Appears when broadcasting: Error: Missing inputs
Can you help me see what is the reason?

**Comment by afk11** [comment]
This repo doesn't provide support for bitcoind. I'll tell you this time, but in future, _do your own research_. 

It means those coins are already spent.

**Comment by wartw** [comment]
@afk11 
I researched for a while. Is there anything wrong with my understanding?
https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/transactionBuilder.php
input is the TXID of the last transaction, to whom payToAddress is issued
Generated unsigned transaction content
Can I broadcast it after signing?
