### ISSUE TITLE
Can I get a redeem script from segwit address without public key?

### ISSUE THREAD

**Issue by vvpgrp** [Bit-Wasp/bitcoin-php#838]
**Can I get a redeem script from segwit address without public key and how can I do it?**

**Comment by afk11** [comment]
No, addresses contain hashes of scripts (or pubkeys), and you can't reverse the hash function.

**Comment by vvpgrp** [comment]
> No, addresses contain hashes of scripts (or pubkeys), and you can't reverse the hash function.

Thanks :)
