### ISSUE TITLE
zpub.parse.php derive address via zpub

### ISSUE THREAD

**Issue by anonproject** [Bit-Wasp/bitcoin-php#839]
I am trying to figure out how to use bitwasp framework to derive an address via zpub.  In the example provided (zpub.parse.php) zpriv was used.  I tried to use zpub instead but got an error that I can't a hardened key by using just a public key.

That said I was able to generate bc1 address via xpub "derived" from 84'/0'/0 path.  Still I wonder how to generate addresses just by using zpub.

**Comment by afk11** [comment]
It's correct - you can't do a hardened derivation on a public key. 

xpub refers to public bip32 key, so deriving stuff like 84'/0'/0' wouldn't work. Probably, you were using a private key (xprv) then as well :)
