### ISSUE TITLE
Can the addresses generated by "addresstypes.php" not be the same?

### ISSUE THREAD

**Issue by wartw** [Bit-Wasp/bitcoin-php#842]
Can the addresses generated by "addresstypes.php" not be the same?

**Comment by afk11** [comment]
The example has a fixed private key. You want a random one instead? https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/privatekey.php

**Comment by wartw** [comment]
I want to generate multiple isolated addresses using a fixed set of private keys. Is there a way to do this?

**Comment by afk11** [comment]
Look into bip32

**Comment by wartw** [comment]
Am I misunderstanding?
https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/bip32.php
```
//Generate private key
$hdFactory = new HierarchicalKeyFactory();
$master = $hdFactory->generateMasterKey($random);
//Main address
echo "Master key (m)\n";
echo "   " . $master->toExtendedPrivateKey($network) . "\n";
```

```
//Generate public key
$masterAddr = new PayToPubKeyHashAddress($master->getPublicKey()->getPubKeyHash());
```

```
//Block address
$key1 = $master->deriveChild(0);
//Block 999999 address
$key2 = $key1->deriveChild(999999);
```

**Comment by afk11** [comment]
Is there an error? share it?

You should check out BIP44 as well by the way (or bip49, or bip84) They all do the same thing, but the difference is the address types.

Electrum supports these wallet formats too!

**Comment by wartw** [comment]
I get up and continue to study, now it is 3 am in Taiwan time (I should take a break

**Comment by wartw** [comment]
Fatal error: Uncaught TypeError: Argument 1 passed to BitWasp\Bitcoin\Transaction\Factory\InputSigner::sign() must implement interface BitWasp\Bitcoin\Crypto\EcAdapter\Key\PrivateKeyInterface, string given, called in /var/www/admin/corn/test.php on line 61 and defined in /var/www/admin/corn/vendor/bitwasp/bitcoin/src/Transaction/Factory/InputSigner.php:1021
Stack trace:
#0 /var/www/admin/corn/test.php(61): BitWasp\Bitcoin\Transaction\Factory\InputSigner->sign('xprv9vk7fGTQx3o...')
#1 {main}
  thrown in /var/www/admin/corn/vendor/bitwasp/bitcoin/src/Transaction/Factory/InputSigner.php on line 1021

**Comment by wartw** [comment]
Am I misunderstanding something?

**Comment by afk11** [comment]
Did you read the error message?

**Comment by wartw** [comment]
I don't understand which sign of bip2 should I use to sign the transaction

**Comment by afk11** [comment]
Mate.. I'm not here to explain bitcoin or PHP errors to you.. You need to read the error and fix your code - it's telling you what is wrong.

**Comment by wartw** [comment]
Google translation, may misunderstand what I mean!  My address is generated by bip32. I have successfully received the money. I need to transfer it now, but I do n’t know what to get the signed key.

**Comment by afk11** [comment]
`$key1->getPrivateKey()` gets the privkey from a HD key. Then you sign as normal.

**Comment by wartw** [comment]
```
OK, if I use
 $ key0 = $ hdFactory-> fromExtended ("xprv9vk7fGTQx3oxxxxxx"); // existing xprv $ key = $ key0-> toExtendedPrivateKey ($ network); 
$ key1 = $ key0-> deriveChild (0); 
$ key2  = $ key1-> deriveChild (999999);
 Use "$ key2-> getPrivateKey ();" to sign?
```

**Comment by afk11** [comment]
It depends where you sent the funds. If you made the address from key2, then you should sign with key2.

**Comment by wartw** [comment]
I'll get up tomorrow and try it out, thank you for helping me speed up a lot of development time.  I have also studied for more than half a month before I understand that OUTX is the last transaction TXID (I know this is funny

**Comment by wartw** [comment]
I succeeded! !!
