### ISSUE TITLE
Error: Missing inputs

### ISSUE THREAD

**Issue by samyan** [Bit-Wasp/bitcoin-php#846]
Hello.

I have installed bitcoin core in regtest mode and i'm connecting via RPC Client. I'm trying to push the signed transaction but i get "Missing inputs" error.

My code:

```php
$addressCreator = new AddressCreator();
$transactionBuilder = TransactionFactory::build();
$privKeyFactory = new PrivateKeyFactory();

$bitcoin = new BaseBitcoin();
$bitcoin->setNetwork(NetworkFactory::bitcoinRegtest()); // Regtest

$privateKey = $privKeyFactory->fromWif($sourceAddressKey, $bitcoin->getNetwork());
$txOuts = [];

// Adding inputs
foreach ($txInputs as $txInput) {
	$transactionBuilder->input($txInput['hash'], $txInput['idx']);

	array_push($txOuts, new TransactionOutput(
		$txInput['value'],
		ScriptFactory::fromHex($txInput['script'])
	));
}

// Adding destination address
$transactionBuilder->payToAddress(
	$spendAmount,
	$addressCreator->fromString($destAddreess)
);

// Adding own address for receive change
$transactionBuilder->payToAddress(
	$changeAmount,
	$addressCreator->fromString($sourceAddress)
);

$transaction = $transactionBuilder->get();

$signer = new Signer($transaction);
$signed = null;

// Signing
foreach ($txOuts as $key => $txOut) {
	$signer->sign($key, $privateKey, $txOut);
}

$signed = $signer->get();

return $signed->getHex();
```

Result example:

- Balance: 200000000 (Satoshi)
- Spend amount: 100000000 (Satoshi)
- Fee amount: 3616 (Satoshi)
- change amount: 99996384 (Satoshi)

Also you can see In this particular example that the fee is 3616 but as you can see in "fees: 0" in transaction.

Decoded raw transaction:
```json
{
    "addresses": [
        "mzBYfxBuuuPxzW5fmGKX9hhkBCs256NhVL", 
        "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer"
    ], 
    "block_height": -1, 
    "block_index": -1, 
    "confirmations": 0, 
    "double_spend": false, 
    "fees": 0, 
    "hash": "28937e3f382c58274ebd4af1450104e74171d981a1a6a9fab5f518ec3c3d360f", 
    "inputs": [
        {
            "age": 0, 
            "output_index": 1, 
            "prev_hash": "8e04e0a940344e300d5800cf918a84d234e501d85bf91738f4426108ffcbd3fc", 
            "script": "473044022065218756d5f4c0f77cdcb6ed27f087cec67acd8d8b21a2fc23c9f5982f1397f2022053e8e30a4f6e321c5809ee3b48329e32c1bb0088cc9604b028341a0b42a469f9014104efde4c2e41e03f38e74d31b3ab6abb294de28d1c9cf068655a1033d9686a706031eeeaee0ab72c0254901f77d3cf0a47e80da05b57fcb59ee7e0c429b6996def", 
            "script_type": "empty", 
            "sequence": 4294967295
        }
    ], 
    "outputs": [
        {
            "addresses": [
                "mzBYfxBuuuPxzW5fmGKX9hhkBCs256NhVL"
            ], 
            "script": "76a914ccbec481242b07d48685367206dea401c390d6e788ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 100000000
        }, 
        {
            "addresses": [
                "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer"
            ], 
            "script": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 99996384
        }
    ], 
    "preference": "low", 
    "received": "2020-04-07T15:53:37.066069908Z", 
    "relayed_by": "18.234.50.70", 
    "size": 257, 
    "total": 199996384, 
    "ver": 1, 
    "vin_sz": 1, 
    "vout_sz": 2
}
```

**So, what's the problem, my code or bitcoin core?**

**Comment by afk11** [comment]
Where did you get this example from it's totally wrong? 

Btw, 'missing inputs' means the inputs were already spent, or don't exist - either way, the inputs not available to be spent..

**Comment by afk11** [comment]
```
{
    "addresses": [
        "mzBYfxBuuuPxzW5fmGKX9hhkBCs256NhVL", 
        "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer"
    ], 
    "block_height": -1, 
    "block_index": -1, 
    "confirmations": 0, 
    "double_spend": false, 
    "fees": 0, 
    "hash": "0839557e0525ba89e2e0f66cee5559b9aed2618485458a87e8cce601565cf5a0", 
    "inputs": [
        {
            "age": 0, 
            "output_index": 1, 
            "prev_hash": "4a04bd13ebee9114715175bc6a8d47148df6a8c71e3e87f0530526e9dfbeb0d5", 
            "script": "483045022100b2f77d15873b905654681fd091dcf8015b1c374329438b2cb5d965ae61234c030220687ca66c098cbe82a5fda29f3536e6163b0a318c15c3982e09a808851284c118014104efde4c2e41e03f38e74d31b3ab6abb294de28d1c9cf068655a1033d9686a706031eeeaee0ab72c0254901f77d3cf0a47e80da05b57fcb59ee7e0c429b6996def", 
            "script_type": "empty", 
            "sequence": 4294967295
        }, 
        {
            "age": 0, 
            "output_index": 1, 
            "prev_hash": "b3acb1a7d9d2b94175b3539fc33689afb61cbcbb1b18a38d92654a2c663531fd", 
            "script": "483045022100824e4b5fec0bdb3d1aae5ae668a15cd07739b2f7f26089e61a56567de554948a02207ec1f8adfb5e1db0487bbbf29a8cf489149a452c5c73a96b4033ae531c122789014104efde4c2e41e03f38e74d31b3ab6abb294de28d1c9cf068655a1033d9686a706031eeeaee0ab72c0254901f77d3cf0a47e80da05b57fcb59ee7e0c429b6996def", 
            "script_type": "empty", 
            "sequence": 4294967295
        }
    ], 
    "outputs": [
        {
            "addresses": [
                "mzBYfxBuuuPxzW5fmGKX9hhkBCs256NhVL"
            ], 
            "script": "76a914ccbec481242b07d48685367206dea401c390d6e788ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 100000000
        }, 
        {
            "addresses": [
                "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer"
            ], 
            "script": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 499998504
        }
    ], 
    "preference": "low", 
    "received": "2020-04-07T12:10:12.853287816Z", 
    "relayed_by": "3.91.160.208", 
    "size": 438, 
    "total": 599998504, 
    "ver": 1, 
    "vin_sz": 2, 
    "vout_sz": 2
}
```

How could a regtest transaction have been relayed to.. is that blockcypher?

**Comment by samyan** [comment]
Hi @afk11. Thank you for response. Look, i have installed the bitcoin core in my PC. First, i have generated 101 blocks to the wallet address:

`generatetoaddress 101 2N6kkXkAXi7aBdacZuG1KtnoaLBaa7A5U1g`

After that i have sent X BTC to other address (**mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer**)

I have check unspents of that address via:

`listunspent 0 9999999 [\"mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer\"]`

I get: 

```json
[
  {
    "txid": "58c60beb4d2e8c700b5322223c87c1f068c380ae43eee5b7335af64093893041",
    "vout": 1,
    "address": "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer",
    "label": "",
    "scriptPubKey": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
    "amount": 2.00000000,
    "confirmations": 209,
    "spendable": false,
    "solvable": false,
    "safe": true
  },
  {
    "txid": "919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75",
    "vout": 0,
    "address": "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer",
    "label": "",
    "scriptPubKey": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
    "amount": 5.00000000,
    "confirmations": 215,
    "spendable": false,
    "solvable": false,
    "safe": true
  },
  {
    "txid": "0992e43ed64cc52f3a6a1ed3b4140fad820c9de0b77205fa07c4045b6ddd4edf",
    "vout": 0,
    "address": "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer",
    "label": "",
    "scriptPubKey": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
    "amount": 10.00000000,
    "confirmations": 204,
    "spendable": false,
    "solvable": false,
    "safe": true
  }
]
```

After that i have connected via **RPC client** to **Bitcoin Core** and i have tried to send funds from **mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer** to **mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer**

The result what that so, "missing input".

**Comment by samyan** [comment]
> ```
> {
>     "addresses": [
>         "mzBYfxBuuuPxzW5fmGKX9hhkBCs256NhVL", 
>         "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer"
>     ], 
>     "block_height": -1, 
>     "block_index": -1, 
>     "confirmations": 0, 
>     "double_spend": false, 
>     "fees": 0, 
>     "hash": "0839557e0525ba89e2e0f66cee5559b9aed2618485458a87e8cce601565cf5a0", 
>     "inputs": [
>         {
>             "age": 0, 
>             "output_index": 1, 
>             "prev_hash": "4a04bd13ebee9114715175bc6a8d47148df6a8c71e3e87f0530526e9dfbeb0d5", 
>             "script": "483045022100b2f77d15873b905654681fd091dcf8015b1c374329438b2cb5d965ae61234c030220687ca66c098cbe82a5fda29f3536e6163b0a318c15c3982e09a808851284c118014104efde4c2e41e03f38e74d31b3ab6abb294de28d1c9cf068655a1033d9686a706031eeeaee0ab72c0254901f77d3cf0a47e80da05b57fcb59ee7e0c429b6996def", 
>             "script_type": "empty", 
>             "sequence": 4294967295
>         }, 
>         {
>             "age": 0, 
>             "output_index": 1, 
>             "prev_hash": "b3acb1a7d9d2b94175b3539fc33689afb61cbcbb1b18a38d92654a2c663531fd", 
>             "script": "483045022100824e4b5fec0bdb3d1aae5ae668a15cd07739b2f7f26089e61a56567de554948a02207ec1f8adfb5e1db0487bbbf29a8cf489149a452c5c73a96b4033ae531c122789014104efde4c2e41e03f38e74d31b3ab6abb294de28d1c9cf068655a1033d9686a706031eeeaee0ab72c0254901f77d3cf0a47e80da05b57fcb59ee7e0c429b6996def", 
>             "script_type": "empty", 
>             "sequence": 4294967295
>         }
>     ], 
>     "outputs": [
>         {
>             "addresses": [
>                 "mzBYfxBuuuPxzW5fmGKX9hhkBCs256NhVL"
>             ], 
>             "script": "76a914ccbec481242b07d48685367206dea401c390d6e788ac", 
>             "script_type": "pay-to-pubkey-hash", 
>             "value": 100000000
>         }, 
>         {
>             "addresses": [
>                 "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer"
>             ], 
>             "script": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac", 
>             "script_type": "pay-to-pubkey-hash", 
>             "value": 499998504
>         }
>     ], 
>     "preference": "low", 
>     "received": "2020-04-07T12:10:12.853287816Z", 
>     "relayed_by": "3.91.160.208", 
>     "size": 438, 
>     "total": 599998504, 
>     "ver": 1, 
>     "vin_sz": 2, 
>     "vout_sz": 2
> }
> ```
> 
> How could a regtest transaction have been relayed to.. is that blockcypher?

yes in decode raw of blockcypher

**Comment by samyan** [comment]
check the main comment please, i updated the raw transaction data

**Comment by afk11** [comment]
Ok - try this and see if it gives you a different result - I changed the 0 to a 1 so it should only show coins with a confirmation. maybe one is spent at some time but it's not confirmed?

`listunspent 1 9999999 [\"mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer\"]`

Also - try using `testmempoolaccept` it might explain which input is wrong.

**Comment by afk11** [comment]
Cool, refreshed. It looks like this input isn't in your `listunspent` output
```
            "output_index": 1, 
            "prev_hash": "8e04e0a940344e300d5800cf918a84d234e501d85bf91738f4426108ffcbd3fc",
```

**Comment by samyan** [comment]
> Ok - try this and see if it gives you a different result - I changed the 0 to a 1 so it should only show coins with a confirmation. maybe one is spent at some time but it's not confirmed?
> 
> `listunspent 1 9999999 [\"mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer\"]`
> 
> Also - try using `testmempoolaccept` it might explain which input is wrong.



```
18:06:59
￼
listunspent 1 9999999 [\"mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer\"]


18:06:59
￼
[
  {
    "txid": "58c60beb4d2e8c700b5322223c87c1f068c380ae43eee5b7335af64093893041",
    "vout": 1,
    "address": "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer",
    "label": "",
    "scriptPubKey": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
    "amount": 2.00000000,
    "confirmations": 209,
    "spendable": false,
    "solvable": false,
    "safe": true
  },
  {
    "txid": "919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75",
    "vout": 0,
    "address": "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer",
    "label": "",
    "scriptPubKey": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
    "amount": 5.00000000,
    "confirmations": 215,
    "spendable": false,
    "solvable": false,
    "safe": true
  },
  {
    "txid": "0992e43ed64cc52f3a6a1ed3b4140fad820c9de0b77205fa07c4045b6ddd4edf",
    "vout": 0,
    "address": "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer",
    "label": "",
    "scriptPubKey": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
    "amount": 10.00000000,
    "confirmations": 204,
    "spendable": false,
    "solvable": false,
    "safe": true
  }
]
```


```
18:08:26
￼
testmempoolaccept [\"0100000001fcd3cbff086142f43817f95bd801e534d2848a91cf00580d304e3440a9e0048e010000008a473044022065218756d5f4c0f77cdcb6ed27f087cec67acd8d8b21a2fc23c9f5982f1397f2022053e8e30a4f6e321c5809ee3b48329e32c1bb0088cc9604b028341a0b42a469f9014104efde4c2e41e03f38e74d31b3ab6abb294de28d1c9cf068655a1033d9686a706031eeeaee0ab72c0254901f77d3cf0a47e80da05b57fcb59ee7e0c429b6996defffffffff0200e1f505000000001976a914ccbec481242b07d48685367206dea401c390d6e788ace0d2f505000000001976a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac00000000\"]


18:08:26
￼
[
  {
    "txid": "28937e3f382c58274ebd4af1450104e74171d981a1a6a9fab5f518ec3c3d360f",
    "allowed": false,
    "reject-reason": "missing-inputs"
  }
]

```

**Comment by samyan** [comment]
> Cool, refreshed. It looks like this input isn't in your `listunspent` output
> 
> ```
>             "output_index": 1, 
>             "prev_hash": "8e04e0a940344e300d5800cf918a84d234e501d85bf91738f4426108ffcbd3fc",
> ```
> 
> ```
> [
>   {
>     "txid": "58c60beb4d2e8c700b5322223c87c1f068c380ae43eee5b7335af64093893041",
>     "vout": 1,
> ......
>   },
>   {
>     "txid": "919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75",
>     "vout": 0,
> .....
>   },
>   {
>     "txid": "0992e43ed64cc52f3a6a1ed3b4140fad820c9de0b77205fa07c4045b6ddd4edf",
>     "vout": 0,
> .....
>   }
> ]
> ```


Bitcoin Core

```
decoderawtransaction 02000000000101759e4fd09811d7afa35a45e8ba95de9c4faa34ee943d9b14da888ea07b4e9b910100000017160014d46a52dcdf8573dbf5dbcffe346fef8917bb7739fdffffff028cb24c000100000017a914fb73907f9abee34bdb077432920edc344b1f011e8700c2eb0b000000001976a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac02473044022024e774e49d76cd425568cdb01599fda1f73ca319a7d13d4ec00f9404f2fc27880220494c3c31d832d2cae3486c32006a4ceb302ca613f0d8651596519cb943651bd60121025f41c0f76ab8a0d0dbf584ef16f1759741450fe704e17206c045b9ac3ab2d1b16b000000
```


```
18:14:15
￼
{
  "txid": "58c60beb4d2e8c700b5322223c87c1f068c380ae43eee5b7335af64093893041",
  "hash": "8e04e0a940344e300d5800cf918a84d234e501d85bf91738f4426108ffcbd3fc",
  "version": 2,
  "size": 249,
  "vsize": 168,
  "weight": 669,
  "locktime": 107,
  "vin": [
    {
      "txid": "919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75",
      "vout": 1,
      "scriptSig": {
        "asm": "0014d46a52dcdf8573dbf5dbcffe346fef8917bb7739",
        "hex": "160014d46a52dcdf8573dbf5dbcffe346fef8917bb7739"
      },
      "txinwitness": [
        "3044022024e774e49d76cd425568cdb01599fda1f73ca319a7d13d4ec00f9404f2fc27880220494c3c31d832d2cae3486c32006a4ceb302ca613f0d8651596519cb943651bd601",
        "025f41c0f76ab8a0d0dbf584ef16f1759741450fe704e17206c045b9ac3ab2d1b1"
      ],
      "sequence": 4294967293
    }
  ],
  "vout": [
    {
      "value": 42.99993740,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_HASH160 fb73907f9abee34bdb077432920edc344b1f011e OP_EQUAL",
        "hex": "a914fb73907f9abee34bdb077432920edc344b1f011e87",
        "reqSigs": 1,
        "type": "scripthash",
        "addresses": [
          "2NGAn2zV8sWLrw2VFMgm9oQxaS8eS2UdJLZ"
        ]
      }
    },
    {
      "value": 2.00000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 4070045522f66b038a0ac7cdcd4fe42c6191024e OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer"
        ]
      }
    }
  ]
}

```

**Comment by afk11** [comment]
```
      "txid": "919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75",
      "vout": 1,
```

```
    "txid": "919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75",
    "vout": 0,
```
they're not the same - both have to be correct. a utxo is the txid + vout combination, $vout is the index of the output in the tx you wanna spend

**Comment by samyan** [comment]
> your tx
> 
> ```
>       "txid": "919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75",
>       "vout": 1,
> ```
> 
> listunspent
> 
> ```
>     "txid": "919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75",
>     "vout": 0,
> ```
> 
> they're not the same - both have to be correct. a utxo is the txid + vout combination, $vout is the index of the output in the tx you wanna spend

Trying now:


```
18:24:24
￼
listunspent 1 9999999 [\"mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer\"]


18:24:24
￼
[
  {
    "txid": "58c60beb4d2e8c700b5322223c87c1f068c380ae43eee5b7335af64093893041",
    "vout": 1,
    "address": "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer",
    "label": "",
    "scriptPubKey": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
    "amount": 2.00000000,
    "confirmations": 209,
    "spendable": false,
    "solvable": false,
    "safe": true
  },
  {
    "txid": "919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75",
    "vout": 0,
    "address": "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer",
    "label": "",
    "scriptPubKey": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
    "amount": 5.00000000,
    "confirmations": 215,
    "spendable": false,
    "solvable": false,
    "safe": true
  },
  {
    "txid": "0992e43ed64cc52f3a6a1ed3b4140fad820c9de0b77205fa07c4045b6ddd4edf",
    "vout": 0,
    "address": "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer",
    "label": "",
    "scriptPubKey": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
    "amount": 10.00000000,
    "confirmations": 204,
    "spendable": false,
    "solvable": false,
    "safe": true
  }
]

```

I dont understand why now

```
"txid": "919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75",
"vout": 0,
```

**Comment by afk11** [comment]
yea, based on your code, it looks like it should have come out as 0. 919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75 create two outputs (0 and 1) to the same address? maybe you already spent 1 and 0 is all that's left now?

**Comment by samyan** [comment]
> yea, based on your code, it looks like it should have come out as 0. 919b4e7ba08e88da149b3d94ee34aa4f9cde95bae8455aa3afd71198d04f9e75 create two outputs (0 and 1) to the same address? maybe you already spent 1 and 0 is all that's left now?
> 
> The transaction would have 3 inputs if the loop worked correctly i suppose?

I'm trying to use the first input:

```
{
    "txid": "58c60beb4d2e8c700b5322223c87c1f068c380ae43eee5b7335af64093893041",
    "vout": 1,
    "address": "mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer",
    "label": "",
    "scriptPubKey": "76a9144070045522f66b038a0ac7cdcd4fe42c6191024e88ac",
    "amount": 2.00000000,
    "confirmations": 209,
    "spendable": false,
    "solvable": false,
    "safe": true
}
```

Because i want to send 1 BTC + Comission and the rest (change amount) get back so it would be **1 input** and **2 outputs** (destination: **mzBYfxBuuuPxzW5fmGKX9hhkBCs256NhVL** and origin: **mmPfjQMdFG82pjZmb4VH5WamNefPsAhGer**).

**Comment by samyan** [comment]
@afk11 ÇSorry, no idea?

**Comment by afk11** [comment]
I thought the issue was solved - your code needs to spend the right input. I don't have a lot of time to help otherwise.

**Comment by samyan** [comment]
> I thought the issue was solved - your code needs to spend the right input. I don't have a lot of time to help otherwise.

If the first input has 2 BTC and i want to spend only 1 BTC, Why is this not the correct input?

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/issues/846#issuecomment-610483300

Because your code set the wrong value for the vout field - once you fix that the errors should go away.

**Comment by samyan** [comment]
I got the problem... I have assigned to **tx_big_endian_hash** the **hash of previous transaction**. Now works okey. Thank @afk11 for your time.
