### ISSUE TITLE
ScriptPubKey to Address

### ISSUE THREAD

**Issue by samyan** [Bit-Wasp/bitcoin-php#851]
Hi, Is it possible to get the address from **scriptPubKey**? And can anyone share any example because i not found nothing in Internet.

**Comment by afk11** [comment]
AddressCreator::fromOutputScript https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/src/Address/AddressCreator.php#L73

**Comment by samyan** [comment]
Thank you very much!
