### ISSUE TITLE
How to retrieve the private key of a derived address?

### ISSUE THREAD

**Issue by finmetal** [Bit-Wasp/bitcoin-php#852]
Hello, that's not an issue, or better, it's an issue for my brain :)

I'm trying to retrieve the private key of a specific derived address, let's say I have my mnemonic phrase stored in variable $mnemonic and i derive the seed and can 'echo' the derived address for a specific path as follow:
$seedGen = new Bip39SeedGenerator();
$seed = $seedGen->getSeed($mnemonic, '');
$hkf = new HierarchicalKeyFactory();
$root = $hkf->fromEntropy($seed);
//bip44 third derived address
$addressPriv = $root->derivePath("44'/0'/0'/0/2");
$address = new PayToPubKeyHashAddress($addressPriv->getPublicKey()->getPubKeyHash());
echo $address->getAddress().PHP_EOL;

I double check on iancoleman.io 's Mnemonic Code Converter and the address i get is correct, so that part of the code is working as expected.
But... i'm missing the script part for 'echo' also the private key (wif format or hexadecimal) of that specific address.
Can someone help me out?

Thanks in advance!

**Comment by afk11** [comment]
```
$addressPriv->getPublicKey()
```

$addressPriv is a `HierarchicalKey`. It exposes getPublicKey, and getPrivateKey.

https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Key/Deterministic/HierarchicalKey.php#L166

https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Crypto/EcAdapter/Key/PrivateKeyInterface.php#L51

PrivateKeyInterface has toWif()

**Comment by finmetal** [comment]
That was my error, I was trying to get it from $address.
Thank you very much!
