### ISSUE TITLE
How to generate a transaction that is broadcastable

### ISSUE THREAD

**Issue by DengSihan** [Bit-Wasp/bitcoin-php#855]
Hello! Thanks for what a great job you have done.

I am trying to make a transaction that can be broadcasted by tools like [blockchain.com](https://www.blockchain.com/en/btc/pushtx).

First, I create a new Bitcoin wallet by [privatekey.php](https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/privatekey.php), sent some btc to it.

![image](https://user-images.githubusercontent.com/33658414/92569617-6f624380-f2b3-11ea-80c3-061a40c73fb1.png)
![image](https://user-images.githubusercontent.com/33658414/92569913-c8ca7280-f2b3-11ea-9d6b-dc151d2a6f52.png)

Then I follow [How to send payment from the address generated by addresstypes.script.php](https://github.com/Bit-Wasp/bitcoin-php/issues/841#issuecomment-596694636). I am new in bitcoin, I have some questions for it.

1. where is the first param of hex() come from? What does it means? How can I get it?
```
// Utxo
$outpoint = new OutPoint(Buffer::hex('44fd3a365aa0dbc0ccbcd61421757df3221e1403ef14e8141bb6986571c9be7c', 32), 0);
$txOut = new TransactionOutput(10000, $witnessScript->getOutputScript());
```

2. which one should I broadcast?
```
echo "Witness serialized transaction: " . $signed->getHex() . PHP_EOL. PHP_EOL;
echo "Base serialized transaction: " . $signed->getBaseSerialization()->getHex() . PHP_EOL;
```

3. where is the payee's address?
In [this code](https://github.com/Bit-Wasp/bitcoin-php/issues/841#issuecomment-596694636), I can't find the payee's address.
Also in [transactionBuilder.php](https://github.com/Bit-Wasp/bitcoin-php/blob/1.0/examples/transactionBuilder.php), payees' addresses is clear, but how can I broadcost?

Thank you very much! I am not good at English, please forgive me.

**Comment by afk11** [comment]
Cool. Well there's lots of examples of transactions in that directory. I suggest you create an electrum wallet, then use the trezor.bip32 example to get the same addresses. On testnet or regtest you can send some funds, and then tweak the sign transaction example to spend the test coins.Post a code snippet if you get stuckOn 9 Sep 2020 08:22, Sihan Deng <notifications@github.com> wrote:
Hello! Thanks for what a great job you have done.
I am trying to make a transaction that can be broadcasted by tool like blockchain.com.

**Comment by DengSihan** [comment]
Thanks for your reply！

After reading [the code](https://github.com/Bit-Wasp/bitcoin-php/issues/841#issuecomment-596694636) and examples, I already knew that the first param of hex() is the lastest txid of the payer's wallet, also I should broadcast the `Base serialized transaction`

But I wonder where is the payee's address? Is the below code means pay to yourself?
```php
// Setup network and private key to segnet
$privKeyFactory = new PrivateKeyFactory;
$key = $privKeyFactory->fromWif('xxx');

$dest = new SegwitAddress(
    WitnessProgram::v0($key->getPublicKey()->getPubKeyHash())
);

$outpoint = new OutPoint(Buffer::hex('4c7a031a31fe794e64ef5ca2714bdd9dd10ceae44650bce025952282bdeeda8b', 32), 0);

$builder = (new TxBuilder())
    ->spendOutPoint($outpoint)
    ->payToAddress(10000, $dest);
```

Thanks a lot!

**Comment by afk11** [comment]
>  where is the first param of hex() come from? What does it means? How can I get it?

```
// Utxo
$outpoint = new OutPoint(Buffer::hex('44fd3a365aa0dbc0ccbcd61421757df3221e1403ef14e8141bb6986571c9be7c', 32), 0);
```

The hex parameter is the transaction ID that paid you some funds, and you're trying to spend those funds. The last number `0`' shows us the funds being spent are the first 'output' from transcation '44df3a.....'

>  which one should I broadcast?

If your transaction uses segwit (your coins received on a segwit address), you use the witness version. Otherwise use the normal version


> where is the payee's address? In this code, I can't find the payee's address. Also in transactionBuilder.php, payees' addresses is clear, but how can I broadcost?

The payeees address is set in an output. To broadcast you take the tx hex and send it through blockchain info or your node

**Comment by afk11** [comment]
> But I wonder where is the payee's address? Is the below code means pay to yourself?

Yea that code is pay to self! The address is set in the outputs of your transaction. Don't forget to add a change output, or any 'leftover' coins will go to the fee.

**Comment by afk11** [comment]
@DengSihan by the way - there are integration tests in bitcoin-php that work with a bitcoind regtest node. Fork this project and setup travis-ci, then the tests will run every time you push. Or you can try the setup locally. It's a good way to test signing code because you find out if the transaction is valid and accepted.

**Comment by DengSihan** [comment]
Thanks a lot!

Finally, I generated a transaction which can be broadcasted successfully.
![image](https://user-images.githubusercontent.com/33658414/92899776-b0905a00-f451-11ea-9731-370a26357437.png)

And here is my code for others who may have the same question
```php
$wif = 'KxwUMCtXXXXXXXXXXXXXXXXXXXXXXXXXEGooz';
$txid = '4c7a031a31fe794e64ef5ca2714bdd9dd10ceae44650bce025952282bdeeda8b';
$address = '1LRqwmjqLNNybJ3M2zQHiwvyA6ikbQQkyS';

// Setup network and private key to segnet
$privKeyFactory = new PrivateKeyFactory;
$key = $privKeyFactory->fromWif($wif);

$witnessScript = new WitnessScript(
    ScriptFactory::scriptPubKey()->payToPubKeyHash($key->getPubKeyHash())
);

$dest = new SegwitAddress(
    WitnessProgram::v0(
        (new AddressCreator())->fromString($address)->getHash()
    )
);

// UTXO
$outpoint = new OutPoint(Buffer::hex($txid, 32), 0);
$txOut = new TransactionOutput(100000, $witnessScript);

// Move UTXO to pub-key-hash
$builder = (new TxBuilder())
    ->spendOutPoint($outpoint)
    ->payToAddress(90000, $dest);

// Sign the transaction
$signer = new Signer($builder->get(), Bitcoin::getEcAdapter());
$input = $signer->input(0, $txOut);
$input->sign($key);

$signed = $signer->get();

// Verify what we've produced
$consensus = ScriptFactory::consensus();
echo "Script validation result: " . ($input->verify(I::VERIFY_P2SH | I::VERIFY_WITNESS) ? "yay\n" : "nay\n");

echo PHP_EOL;
echo "Witness serialized transaction: " . $signed->getHex() . PHP_EOL. PHP_EOL;
echo "Base serialized transaction: " . $signed->getBaseSerialization()->getHex() . PHP_EOL;
```
