### ISSUE TITLE
Electrum mnemonic generated, address differs from the ones listed if mnemonic imported on electrum wallet

### ISSUE THREAD

**Issue by finmetal** [Bit-Wasp/bitcoin-php#859]
Hello, i am probably (let's say 100% sure) doing something wrong and I need your help on track it down, if possible.

That's what I'm doing:
- i am generating a random electrum seed
$entropy = Buffer::hex("$new_random_key");
$elect = MnemonicFactory::electrum();
$seedGenerator = new Bip39SeedGenerator();
$mnemonic = $elect->entropyToMnemonic($entropy);
$seed = $seedGenerator->getSeed($mnemonic, '');

and I got for example this mnemonic:
"master hum odd beaten spell shame tangle juice naked someday rough pity"

- then i create a HierarchicalKeyFactory and derivate path as following for generating the hardened wallet:
$root = $hkFactory->fromEntropy($seed);
$addressPriv = $root->derivePath("44'/0'/0'/0/0'");
PayToPubKeyHashAddress($addressPriv->getPublicKey()->getPubKeyHash());
$address->getAddress();

the resulting address i get is that one:
139nngB6sr4RkSggQynViVCrd8XheQTY7z

Here come the problem: if i use the new/restore procedure in Electrum software and i use that mnemonic, i get the following one as first address:
1EKg8gzE3f4q1E5unYMmKWxC7NzD96PX4z

It's driving me mad :)

Thank you in advance!

**Comment by afk11** [comment]
Electrum used two standards over the years. a custom electrum format (the older one, but referred to as ElectrumMnemonic in this project), and eventually bip39. I figured the seed might be super old, so I stuck it into https://iancoleman.io/bip39/ and it complained about 'hum' not being in the word list. 

Unfortunately you'll need to switch up the second code block as well, the old electrum format used a different derivation (ElectrumKey) if you check out the tests for those electrum derivations for deriving seed->mpk and mpk->address

**Comment by finmetal** [comment]
Oh right, for what I recollect old electrum had different wordlist from BIP39 so the the first part of code generates the old electrum mnemonic and if I import that mnemonic into Electrum wallet it's a valid one.
I modified as you have suggested and it seems it's working fine, thank you very much!

**Comment by afk11** [comment]
Yep! Take care with that those as they have no checksum and if you miswrite a word on paper and it's in the word list you won't get a warning..
