### ISSUE TITLE
Support for Dogecoin and Urocoin

### ISSUE THREAD

**Issue by josecelano** [Bit-Wasp/bitcoin-php#97]
I am trying to find out values in

https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Network/NetworkFactory.php

for Dogecoin and Urocoin

**Comment by afk11** [comment]
Normally these can be found in the chainparams.cpp file, of 0.10+ clients. 

Looks like they can be scattered all over the place :/ https://github.com/urocoin/uro/blob/319de97bbd56a10a3b2dca5b36be0c7a9c6603ae/src/main.cpp#L3233 0.9 - 0.10 saw a big reorganization of it all

**Comment by afk11** [comment]
Just fyi - instead of always parameterizing the Network class (can't continue stuffing things in the constructor), you can have a class implement NetworkInterface and pass those instances around if it's any use.

**Comment by afk11** [comment]
Did ya get sorted?

**Comment by josecelano** [comment]
hey @afk11 thank you for your reply and sorry for the delay.

I have used your static contructor to get a Doge Network:
https://github.com/blockcypher/php-client/blob/master/lib/BlockCypher/Crypto/CoinSymbolNetworkMapping.php#L36

**Comment by afk11** [comment]
Yeah that looks correct - they really hid those constants ;) 

If this is all good I'll close this issue?

**Comment by josecelano** [comment]
It's OK. Thanks.
